// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {behavior} from '../models';
import {backend} from '../models';
import {backup} from '../models';
import {config} from '../models';
import {browser} from '../models';
import {events} from '../models';
import {logger} from '../models';
import {launchcode} from '../models';

export function ActiveRecordingStatus():Promise<behavior.ActiveRecordingStatus>;

export function AutomationRuleCreate(arg1:backend.AutomationRuleInput):Promise<backend.AutomationRuleInfo>;

export function AutomationRuleDelete(arg1:string):Promise<void>;

export function AutomationRuleList():Promise<Array<backend.AutomationRuleInfo>>;

export function AutomationRuleTestFire(arg1:string):Promise<void>;

export function AutomationRuleToggle(arg1:string,arg2:boolean):Promise<void>;

export function AutomationRuleUpdate(arg1:string,arg2:backend.AutomationRuleInput):Promise<backend.AutomationRuleInfo>;

export function BackupExportPackage():Promise<Record<string, any>>;

export function BackupGetManifestTemplate():Promise<backup.Manifest>;

export function BackupGetScopeDefinition():Promise<backup.Scope>;

export function BackupImportPackage(arg1:boolean):Promise<Record<string, any>>;

export function BackupInitializeSystem():Promise<Record<string, any>>;

export function BehaviorGetRecording(arg1:string):Promise<behavior.Recording>;

export function BehaviorGetRecordingDetail(arg1:string,arg2:number,arg3:number):Promise<behavior.RecordingDetailPage>;

export function BehaviorPlayRecording(arg1:string,arg2:string,arg3:behavior.VariationConfig):Promise<void>;

export function BehaviorPlaybackReview(arg1:string,arg2:string):Promise<void>;

export function BehaviorPresetList():Promise<Array<backend.BehaviorPresetInfo>>;

export function BehaviorQuickRecord(arg1:string):Promise<behavior.Recording>;

export function BehaviorRecordingDelete(arg1:string):Promise<void>;

export function BehaviorRecordingCopy(arg1:string,arg2:string):Promise<behavior.Recording>;

export function BehaviorRecordingExport(arg1:string):Promise<behavior.RecordingExportBundle>;

export function BehaviorRecordingImport(arg1:string,arg2:string):Promise<behavior.Recording>;

export function BehaviorRecordingList():Promise<Array<behavior.Recording>>;

export function BehaviorRecordingRename(arg1:string,arg2:string):Promise<void>;

export function BehaviorRecordingStatus():Promise<behavior.ActiveRecordingStatus>;

export function BehaviorRecordingSummaryList():Promise<Array<behavior.RecordingSummary>>;

export function BehaviorRecordingTrim(arg1:string,arg2:number,arg3:number,arg4:string):Promise<behavior.Recording>;

export function BehaviorStartRecording(arg1:string):Promise<void>;

export function BehaviorStopPlayback(arg1:string):Promise<void>;

export function BehaviorStopRecording(arg1:string,arg2:string):Promise<behavior.Recording>;

export function BookmarkList():Promise<Array<config.BrowserBookmark>>;

export function BookmarkReset():Promise<void>;

export function BookmarkSave(arg1:Array<config.BrowserBookmark>):Promise<void>;

export function BrowserClearCookies(arg1:string):Promise<void>;

export function BrowserCoreDelete(arg1:string):Promise<void>;

export function BrowserCoreDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowserCoreExtendedInfo():Promise<Array<browser.CoreExtendedInfo>>;

export function BrowserCoreList():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSave(arg1:browser.CoreInput):Promise<void>;

export function BrowserCoreScan():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSetDefault(arg1:string):Promise<void>;

export function BrowserCoreValidate(arg1:string):Promise<browser.CoreValidateResult>;

export function BrowserCoreValidateForKind(arg1:string,arg2:string):Promise<browser.CoreValidateResult>;

export function BrowserExportCookies(arg1:string):Promise<string>;

export function BrowserGetAllTags():Promise<Array<string>>;

export function BrowserGetCookies(arg1:string):Promise<Array<backend.CookieInfo>>;

export function BrowserInstanceGetTabs(arg1:string):Promise<Array<browser.Tab>>;

export function BrowserInstanceOpenUrl(arg1:string,arg2:string):Promise<boolean>;

export function BrowserInstanceRestart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartByCode(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartWithParams(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<browser.Profile>;

export function BrowserInstanceStatus(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStop(arg1:string):Promise<browser.Profile>;

export function BrowserProfileBatchRemoveTags(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function BrowserProfileBatchSetTags(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<void>;

export function BrowserProfileCopy(arg1:string,arg2:string):Promise<browser.Profile>;

export function BrowserProfileCreate(arg1:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProfileDelete(arg1:string):Promise<void>;

export function BrowserProfileGetCode(arg1:string):Promise<string>;

export function BrowserProfileList():Promise<Array<browser.Profile>>;

export function BrowserProfileListByTag(arg1:string):Promise<Array<browser.Profile>>;

export function BrowserProfileRegenerateCode(arg1:string):Promise<string>;

export function BrowserProfileSetCode(arg1:string,arg2:string):Promise<string>;

export function BrowserProfileSetKeywords(arg1:string,arg2:Array<string>):Promise<browser.Profile>;

export function BrowserProfileUpdate(arg1:string,arg2:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProxyBatchCheckIPHealth(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyIPHealthResult>>;

export function BrowserProxyBatchTestSpeed(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyTestResult>>;

export function BrowserProxyCheckIPHealth(arg1:string):Promise<backend.ProxyIPHealthResult>;

export function BrowserProxyDelete(arg1:string):Promise<void>;

export function BrowserProxyFetchClashByURL(arg1:string):Promise<Record<string, any>>;

export function BrowserProxyFixNames():Promise<Record<string, any>>;

export function BrowserProxyImportSubscriptionByURL(arg1:string,arg2:string):Promise<Record<string, any>>;

export function BrowserProxyList():Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListByGroup(arg1:string):Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListGroups():Promise<Array<string>>;

export function BrowserProxyTestSpeed(arg1:string):Promise<backend.ProxyTestResult>;

export function BrowserRenameTag(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotCreate(arg1:string,arg2:string):Promise<backend.SnapshotInfo>;

export function BrowserSnapshotDelete(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotList(arg1:string):Promise<Array<backend.SnapshotInfo>>;

export function BrowserSnapshotRestore(arg1:string,arg2:string):Promise<void>;

export function CleanupStaleRecordingSessions():Promise<void>;

export function CleanupStaleSessions():Promise<void>;

export function ClearAppLogs():Promise<void>;

export function CreateGroup(arg1:browser.GroupInput):Promise<browser.Group>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteRecording(arg1:string):Promise<void>;

export function EmitAndLogEvent(arg1:string,arg2:Record<string, any>):Promise<void>;

export function EventLogCount(arg1:backend.EventLogQueryInput):Promise<number>;

export function EventLogExport(arg1:backend.EventLogQueryInput):Promise<string>;

export function EventLogPrune(arg1:string):Promise<number>;

export function EventLogQuery(arg1:backend.EventLogQueryInput):Promise<Array<events.EventLogEntry>>;

export function FetchRemoteAuthorProfile(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ForceQuit():Promise<void>;

export function GenerateCDKeys(arg1:number):Promise<Array<string>>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetAppLogs():Promise<Array<logger.MemoryLogEntry>>;

export function GetBehaviorPresets():Promise<Array<behavior.Profile>>;

export function GetBrowserSettings():Promise<browser.Settings>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetInterceptor():Promise<logger.MethodInterceptor>;

export function GetLaunchServerInfo():Promise<Record<string, any>>;

export function GetLicenseStatus():Promise<backend.LicenseStatus>;

export function GetLogLevel():Promise<string>;

export function GetMemoryStats():Promise<Record<string, any>>;

export function GetRecording(arg1:string):Promise<behavior.Recording>;

export function GetRecordingDetail(arg1:string,arg2:number,arg3:number):Promise<behavior.RecordingDetailPage>;

export function GetRunningInstances():Promise<Array<browser.Profile>>;

export function IdentityReportProfile(arg1:string):Promise<browser.IdentityStrengthReport>;

export function ListGroups():Promise<Array<browser.GroupWithCount>>;

export function ListRecordingSummaries():Promise<Array<behavior.RecordingSummary>>;

export function ListRecordings():Promise<Array<behavior.Recording>>;

export function MoveInstancesToGroup(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenCorePath(arg1:string):Promise<void>;

export function OpenUserDataDir(arg1:string):Promise<void>;

export function PlayRecording(arg1:string,arg2:string,arg3:behavior.VariationConfig):Promise<void>;

export function QuickRecord(arg1:string):Promise<behavior.Recording>;

export function QuitAppOnly():Promise<void>;

export function RedeemCDKey(arg1:string):Promise<void>;

export function RedeemGithubStar():Promise<void>;

export function ReloadConfig():Promise<void>;

export function SaveBrowserProxies(arg1:Array<config.BrowserProxy>):Promise<void>;

export function SaveBrowserSettings(arg1:browser.Settings):Promise<void>;

export function SchedulerAddTask(arg1:backend.SchedulerTaskInput):Promise<backend.SchedulerTaskInfo>;

export function SchedulerGetEventNames():Promise<Array<string>>;

export function SchedulerListTasks():Promise<Array<backend.SchedulerTaskInfo>>;

export function SchedulerRemoveTask(arg1:string):Promise<void>;

export function SchedulerRunTaskNow(arg1:string):Promise<void>;

export function SchedulerTriggerEvent(arg1:string):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function StartInstance(arg1:string):Promise<browser.Profile>;

export function StartInstanceWithParams(arg1:string,arg2:launchcode.LaunchRequestParams):Promise<browser.Profile>;

export function StartRecording(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<browser.Profile>;

export function StopPlayback(arg1:string):Promise<void>;

export function StopRecording(arg1:string,arg2:string):Promise<behavior.Recording>;

export function SynchronizerActivateProfile(arg1:string):Promise<void>;

export function SynchronizerArrangeProfiles(arg1:Array<string>,arg2:string):Promise<Array<backend.SyncWindowPlacement>>;

export function SynchronizerBroadcastNavigate(arg1:string,arg2:string):Promise<void>;

export function SynchronizerBroadcastRefresh(arg1:string):Promise<void>;

export function SynchronizerCaptureScreenshot(arg1:string):Promise<string>;

export function SynchronizerGetOperationLog(arg1:number):Promise<Array<backend.SyncOperation>>;

export function SynchronizerListGroups():Promise<Array<backend.SyncGroup>>;

export function SynchronizerListTasks(arg1:number):Promise<Array<backend.WorkbenchTask>>;

export function SynchronizerNavigateProfile(arg1:string,arg2:string):Promise<void>;

export function SynchronizerRefreshProfile(arg1:string):Promise<void>;

export function SynchronizerSaveTasks(arg1:Array<backend.WorkbenchTask>):Promise<void>;

export function TestProxyConnectivity(arg1:string,arg2:string):Promise<backend.ProxyTestResult>;

export function TestProxyRealConnectivity(arg1:string):Promise<backend.ProxyTestResult>;

export function TriggerGC():Promise<void>;

export function UpdateGroup(arg1:string,arg2:browser.GroupInput):Promise<browser.Group>;

export function ValidateProxyConfig(arg1:string,arg2:string):Promise<backend.ProxyValidationResult>;

export function WorkbenchActivateProfile(arg1:string):Promise<void>;

export function WorkbenchArrangeProfiles(arg1:Array<string>,arg2:string):Promise<Array<launchcode.WorkbenchWindowPlacement>>;

export function WorkbenchCaptureScreenshot(arg1:string):Promise<string>;

export function WorkbenchNavigateProfile(arg1:string,arg2:string):Promise<void>;

export function WorkbenchRefreshProfile(arg1:string):Promise<void>;
