// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveRecordingStatus() {
  return window['go']['main']['App']['ActiveRecordingStatus']();
}

export function AutomationRuleCreate(arg1) {
  return window['go']['main']['App']['AutomationRuleCreate'](arg1);
}

export function AutomationRuleDelete(arg1) {
  return window['go']['main']['App']['AutomationRuleDelete'](arg1);
}

export function AutomationRuleList() {
  return window['go']['main']['App']['AutomationRuleList']();
}

export function AutomationRuleTestFire(arg1) {
  return window['go']['main']['App']['AutomationRuleTestFire'](arg1);
}

export function AutomationRuleToggle(arg1, arg2) {
  return window['go']['main']['App']['AutomationRuleToggle'](arg1, arg2);
}

export function AutomationRuleUpdate(arg1, arg2) {
  return window['go']['main']['App']['AutomationRuleUpdate'](arg1, arg2);
}

export function BackupExportPackage() {
  return window['go']['main']['App']['BackupExportPackage']();
}

export function BackupExportPackageToPath(arg1) {
  return window['go']['main']['App']['BackupExportPackageToPath'](arg1);
}

export function BackupGetManifestTemplate() {
  return window['go']['main']['App']['BackupGetManifestTemplate']();
}

export function BackupGetScopeDefinition() {
  return window['go']['main']['App']['BackupGetScopeDefinition']();
}

export function BackupImportPackage(arg1) {
  return window['go']['main']['App']['BackupImportPackage'](arg1);
}

export function BackupImportPackageFromPath(arg1, arg2) {
  return window['go']['main']['App']['BackupImportPackageFromPath'](arg1, arg2);
}

export function BackupInitializeSystem() {
  return window['go']['main']['App']['BackupInitializeSystem']();
}

export function BehaviorGetRecording(arg1) {
  return window['go']['main']['App']['BehaviorGetRecording'](arg1);
}

export function BehaviorGetRecordingDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['BehaviorGetRecordingDetail'](arg1, arg2, arg3);
}

export function BehaviorPlayRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['BehaviorPlayRecording'](arg1, arg2, arg3);
}

export function BehaviorPresetList() {
  return window['go']['main']['App']['BehaviorPresetList']();
}

export function BehaviorQuickRecord(arg1) {
  return window['go']['main']['App']['BehaviorQuickRecord'](arg1);
}

export function BehaviorRecordingCopy(arg1, arg2) {
  return window['go']['main']['App']['BehaviorRecordingCopy'](arg1, arg2);
}

export function BehaviorRecordingDelete(arg1) {
  return window['go']['main']['App']['BehaviorRecordingDelete'](arg1);
}

export function BehaviorRecordingExport(arg1) {
  return window['go']['main']['App']['BehaviorRecordingExport'](arg1);
}

export function BehaviorRecordingImport(arg1, arg2) {
  return window['go']['main']['App']['BehaviorRecordingImport'](arg1, arg2);
}

export function BehaviorRecordingList() {
  return window['go']['main']['App']['BehaviorRecordingList']();
}

export function BehaviorRecordingRename(arg1, arg2) {
  return window['go']['main']['App']['BehaviorRecordingRename'](arg1, arg2);
}

export function BehaviorRecordingStatus() {
  return window['go']['main']['App']['BehaviorRecordingStatus']();
}

export function BehaviorRecordingSummaryList() {
  return window['go']['main']['App']['BehaviorRecordingSummaryList']();
}

export function BehaviorRecordingTrim(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BehaviorRecordingTrim'](arg1, arg2, arg3, arg4);
}

export function BehaviorStartRecording(arg1) {
  return window['go']['main']['App']['BehaviorStartRecording'](arg1);
}

export function BehaviorStopPlayback(arg1) {
  return window['go']['main']['App']['BehaviorStopPlayback'](arg1);
}

export function BehaviorStopRecording(arg1, arg2) {
  return window['go']['main']['App']['BehaviorStopRecording'](arg1, arg2);
}

export function BookmarkList() {
  return window['go']['main']['App']['BookmarkList']();
}

export function BookmarkReset() {
  return window['go']['main']['App']['BookmarkReset']();
}

export function BookmarkSave(arg1) {
  return window['go']['main']['App']['BookmarkSave'](arg1);
}

export function BrowserClearCookies(arg1) {
  return window['go']['main']['App']['BrowserClearCookies'](arg1);
}

export function BrowserCoreDelete(arg1) {
  return window['go']['main']['App']['BrowserCoreDelete'](arg1);
}

export function BrowserCoreDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserCoreDownload'](arg1, arg2, arg3);
}

export function BrowserCoreExtendedInfo() {
  return window['go']['main']['App']['BrowserCoreExtendedInfo']();
}

export function BrowserCoreList() {
  return window['go']['main']['App']['BrowserCoreList']();
}

export function BrowserCoreSave(arg1) {
  return window['go']['main']['App']['BrowserCoreSave'](arg1);
}

export function BrowserCoreScan() {
  return window['go']['main']['App']['BrowserCoreScan']();
}

export function BrowserCoreSetDefault(arg1) {
  return window['go']['main']['App']['BrowserCoreSetDefault'](arg1);
}

export function BrowserCoreValidate(arg1) {
  return window['go']['main']['App']['BrowserCoreValidate'](arg1);
}

export function BrowserExportCookies(arg1) {
  return window['go']['main']['App']['BrowserExportCookies'](arg1);
}

export function BrowserGetAllTags() {
  return window['go']['main']['App']['BrowserGetAllTags']();
}

export function BrowserGetCookies(arg1) {
  return window['go']['main']['App']['BrowserGetCookies'](arg1);
}

export function BrowserInstanceGetTabs(arg1) {
  return window['go']['main']['App']['BrowserInstanceGetTabs'](arg1);
}

export function BrowserInstanceOpenUrl(arg1, arg2) {
  return window['go']['main']['App']['BrowserInstanceOpenUrl'](arg1, arg2);
}

export function BrowserInstanceRestart(arg1) {
  return window['go']['main']['App']['BrowserInstanceRestart'](arg1);
}

export function BrowserInstanceStart(arg1) {
  return window['go']['main']['App']['BrowserInstanceStart'](arg1);
}

export function BrowserInstanceStartByCode(arg1) {
  return window['go']['main']['App']['BrowserInstanceStartByCode'](arg1);
}

export function BrowserInstanceStartWithParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserInstanceStartWithParams'](arg1, arg2, arg3, arg4);
}

export function BrowserInstanceStatus(arg1) {
  return window['go']['main']['App']['BrowserInstanceStatus'](arg1);
}

export function BrowserInstanceStop(arg1) {
  return window['go']['main']['App']['BrowserInstanceStop'](arg1);
}

export function BrowserProfileBatchRemoveTags(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileBatchRemoveTags'](arg1, arg2);
}

export function BrowserProfileBatchSetTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileBatchSetTags'](arg1, arg2, arg3);
}

export function BrowserProfileCopy(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileCopy'](arg1, arg2);
}

export function BrowserProfileCreate(arg1) {
  return window['go']['main']['App']['BrowserProfileCreate'](arg1);
}

export function BrowserProfileDelete(arg1) {
  return window['go']['main']['App']['BrowserProfileDelete'](arg1);
}

export function BrowserProfileGetCode(arg1) {
  return window['go']['main']['App']['BrowserProfileGetCode'](arg1);
}

export function BrowserProfileList() {
  return window['go']['main']['App']['BrowserProfileList']();
}

export function BrowserProfileListByTag(arg1) {
  return window['go']['main']['App']['BrowserProfileListByTag'](arg1);
}

export function BrowserProfileRegenerateCode(arg1) {
  return window['go']['main']['App']['BrowserProfileRegenerateCode'](arg1);
}

export function BrowserProfileSetCode(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetCode'](arg1, arg2);
}

export function BrowserProfileSetKeywords(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetKeywords'](arg1, arg2);
}

export function BrowserProfileUpdate(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileUpdate'](arg1, arg2);
}

export function BrowserProxyBatchCheckIPHealth(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchCheckIPHealth'](arg1, arg2);
}

export function BrowserProxyBatchTestSpeed(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchTestSpeed'](arg1, arg2);
}

export function BrowserProxyCheckIPHealth(arg1) {
  return window['go']['main']['App']['BrowserProxyCheckIPHealth'](arg1);
}

export function BrowserProxyFetchClashByURL(arg1) {
  return window['go']['main']['App']['BrowserProxyFetchClashByURL'](arg1);
}

export function BrowserProxyList() {
  return window['go']['main']['App']['BrowserProxyList']();
}

export function BrowserProxyListByGroup(arg1) {
  return window['go']['main']['App']['BrowserProxyListByGroup'](arg1);
}

export function BrowserProxyListGroups() {
  return window['go']['main']['App']['BrowserProxyListGroups']();
}

export function BrowserProxyTestSpeed(arg1) {
  return window['go']['main']['App']['BrowserProxyTestSpeed'](arg1);
}

export function BrowserRenameTag(arg1, arg2) {
  return window['go']['main']['App']['BrowserRenameTag'](arg1, arg2);
}

export function BrowserSnapshotCreate(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotCreate'](arg1, arg2);
}

export function BrowserSnapshotDelete(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotDelete'](arg1, arg2);
}

export function BrowserSnapshotList(arg1) {
  return window['go']['main']['App']['BrowserSnapshotList'](arg1);
}

export function BrowserSnapshotRestore(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotRestore'](arg1, arg2);
}

export function CleanupStaleRecordingSessions() {
  return window['go']['main']['App']['CleanupStaleRecordingSessions']();
}

export function CleanupStaleSessions() {
  return window['go']['main']['App']['CleanupStaleSessions']();
}

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteRecording(arg1) {
  return window['go']['main']['App']['DeleteRecording'](arg1);
}

export function EmitAndLogEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitAndLogEvent'](arg1, arg2);
}

export function EventLogCount(arg1) {
  return window['go']['main']['App']['EventLogCount'](arg1);
}

export function EventLogExport(arg1) {
  return window['go']['main']['App']['EventLogExport'](arg1);
}

export function EventLogPrune(arg1) {
  return window['go']['main']['App']['EventLogPrune'](arg1);
}

export function EventLogQuery(arg1) {
  return window['go']['main']['App']['EventLogQuery'](arg1);
}

export function FetchRemoteAuthorProfile(arg1, arg2) {
  return window['go']['main']['App']['FetchRemoteAuthorProfile'](arg1, arg2);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GenerateCDKeys(arg1) {
  return window['go']['main']['App']['GenerateCDKeys'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetAppLogsPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAppLogsPage'](arg1, arg2, arg3, arg4);
}

export function GetBehaviorPresets() {
  return window['go']['main']['App']['GetBehaviorPresets']();
}

export function GetBrowserSettings() {
  return window['go']['main']['App']['GetBrowserSettings']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetInterceptor() {
  return window['go']['main']['App']['GetInterceptor']();
}

export function GetLaunchServerInfo() {
  return window['go']['main']['App']['GetLaunchServerInfo']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetRecording(arg1) {
  return window['go']['main']['App']['GetRecording'](arg1);
}

export function GetRecordingDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRecordingDetail'](arg1, arg2, arg3);
}

export function GetRunningInstances() {
  return window['go']['main']['App']['GetRunningInstances']();
}

export function InitLLMClient() {
  return window['go']['main']['App']['InitLLMClient']();
}

export function LLMExecuteTask(arg1, arg2) {
  return window['go']['main']['App']['LLMExecuteTask'](arg1, arg2);
}

export function LLMGetOffsetLibrary() {
  return window['go']['main']['App']['LLMGetOffsetLibrary']();
}

export function LLMHasKey() {
  return window['go']['main']['App']['LLMHasKey']();
}

export function LLMPlanOnly(arg1) {
  return window['go']['main']['App']['LLMPlanOnly'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListRecordingSummaries() {
  return window['go']['main']['App']['ListRecordingSummaries']();
}

export function ListRecordings() {
  return window['go']['main']['App']['ListRecordings']();
}

export function MoveInstancesToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveInstancesToGroup'](arg1, arg2);
}

export function OpenCorePath(arg1) {
  return window['go']['main']['App']['OpenCorePath'](arg1);
}

export function OpenUserDataDir(arg1) {
  return window['go']['main']['App']['OpenUserDataDir'](arg1);
}

export function PlayRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlayRecording'](arg1, arg2, arg3);
}

export function QuickRecord(arg1) {
  return window['go']['main']['App']['QuickRecord'](arg1);
}

export function QuitAppOnly() {
  return window['go']['main']['App']['QuitAppOnly']();
}

export function RedeemCDKey(arg1) {
  return window['go']['main']['App']['RedeemCDKey'](arg1);
}

export function RedeemGithubStar() {
  return window['go']['main']['App']['RedeemGithubStar']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveBrowserProxies(arg1) {
  return window['go']['main']['App']['SaveBrowserProxies'](arg1);
}

export function SaveBrowserSettings(arg1) {
  return window['go']['main']['App']['SaveBrowserSettings'](arg1);
}

export function SchedulerAddTask(arg1) {
  return window['go']['main']['App']['SchedulerAddTask'](arg1);
}

export function SchedulerGetEventNames() {
  return window['go']['main']['App']['SchedulerGetEventNames']();
}

export function SchedulerListTasks() {
  return window['go']['main']['App']['SchedulerListTasks']();
}

export function SchedulerRemoveTask(arg1) {
  return window['go']['main']['App']['SchedulerRemoveTask'](arg1);
}

export function SchedulerRunTaskNow(arg1) {
  return window['go']['main']['App']['SchedulerRunTaskNow'](arg1);
}

export function SchedulerTriggerEvent(arg1) {
  return window['go']['main']['App']['SchedulerTriggerEvent'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StartInstanceWithParams(arg1, arg2) {
  return window['go']['main']['App']['StartInstanceWithParams'](arg1, arg2);
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function StopPlayback(arg1) {
  return window['go']['main']['App']['StopPlayback'](arg1);
}

export function StopRecording(arg1, arg2) {
  return window['go']['main']['App']['StopRecording'](arg1, arg2);
}

export function SynchronizerActivateProfile(arg1) {
  return window['go']['main']['App']['SynchronizerActivateProfile'](arg1);
}

export function SynchronizerArrangeProfiles(arg1, arg2) {
  return window['go']['main']['App']['SynchronizerArrangeProfiles'](arg1, arg2);
}

export function SynchronizerBroadcastNavigate(arg1, arg2) {
  return window['go']['main']['App']['SynchronizerBroadcastNavigate'](arg1, arg2);
}

export function SynchronizerBroadcastRefresh(arg1) {
  return window['go']['main']['App']['SynchronizerBroadcastRefresh'](arg1);
}

export function SynchronizerCaptureScreenshot(arg1) {
  return window['go']['main']['App']['SynchronizerCaptureScreenshot'](arg1);
}

export function SynchronizerGetOperationLog(arg1) {
  return window['go']['main']['App']['SynchronizerGetOperationLog'](arg1);
}

export function SynchronizerListGroups() {
  return window['go']['main']['App']['SynchronizerListGroups']();
}

export function SynchronizerListTasks(arg1) {
  return window['go']['main']['App']['SynchronizerListTasks'](arg1);
}

export function SynchronizerNavigateProfile(arg1, arg2) {
  return window['go']['main']['App']['SynchronizerNavigateProfile'](arg1, arg2);
}

export function SynchronizerRefreshProfile(arg1) {
  return window['go']['main']['App']['SynchronizerRefreshProfile'](arg1);
}

export function SynchronizerSaveTasks(arg1) {
  return window['go']['main']['App']['SynchronizerSaveTasks'](arg1);
}

export function TestProxyConnectivity(arg1, arg2) {
  return window['go']['main']['App']['TestProxyConnectivity'](arg1, arg2);
}

export function TestProxyRealConnectivity(arg1) {
  return window['go']['main']['App']['TestProxyRealConnectivity'](arg1);
}

export function TriggerGC() {
  return window['go']['main']['App']['TriggerGC']();
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2);
}

export function ValidateProxyConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateProxyConfig'](arg1, arg2);
}

export function WorkbenchActivateProfile(arg1) {
  return window['go']['main']['App']['WorkbenchActivateProfile'](arg1);
}

export function WorkbenchArrangeProfiles(arg1, arg2) {
  return window['go']['main']['App']['WorkbenchArrangeProfiles'](arg1, arg2);
}

export function WorkbenchCaptureScreenshot(arg1) {
  return window['go']['main']['App']['WorkbenchCaptureScreenshot'](arg1);
}

export function WorkbenchFingerprintProfile(arg1) {
  return window['go']['main']['App']['WorkbenchFingerprintProfile'](arg1);
}

export function WorkbenchNavigateProfile(arg1, arg2) {
  return window['go']['main']['App']['WorkbenchNavigateProfile'](arg1, arg2);
}

export function WorkbenchRefreshProfile(arg1) {
  return window['go']['main']['App']['WorkbenchRefreshProfile'](arg1);
}
