// Code generated by backend/cmd/gen-events. DO NOT EDIT.
// Source: backend/internal/events/registry.go

package events

// Phase 2 event name constants (generated).
const (
	// EventAccountFollowBlock is generated from registry.
	EventAccountFollowBlock = "account:follow:block"
	// EventAccountFollowFollow is generated from registry.
	EventAccountFollowFollow = "account:follow:follow"
	// EventAccountFollowMute is generated from registry.
	EventAccountFollowMute = "account:follow:mute"
	// EventAccountFollowUnfollow is generated from registry.
	EventAccountFollowUnfollow = "account:follow:unfollow"
	// EventAccountLoginAttempt is generated from registry.
	EventAccountLoginAttempt = "account:login:attempt"
	// EventAccountLoginBlocked is generated from registry.
	EventAccountLoginBlocked = "account:login:blocked"
	// EventAccountLoginCaptcha is generated from registry.
	EventAccountLoginCaptcha = "account:login:captcha"
	// EventAccountLoginFailed is generated from registry.
	EventAccountLoginFailed = "account:login:failed"
	// EventAccountLoginSessionExpired is generated from registry.
	EventAccountLoginSessionExpired = "account:login:session-expired"
	// EventAccountLoginSuccess is generated from registry.
	EventAccountLoginSuccess = "account:login:success"
	// EventAccountLoginTimeout is generated from registry.
	EventAccountLoginTimeout = "account:login:timeout"
	// EventAccountLoginVerify is generated from registry.
	EventAccountLoginVerify = "account:login:verify"
	// EventAccountProfileAvatarChanged is generated from registry.
	EventAccountProfileAvatarChanged = "account:profile:avatar-changed"
	// EventAccountProfileReported is generated from registry.
	EventAccountProfileReported = "account:profile:reported"
	// EventAccountProfileUpdated is generated from registry.
	EventAccountProfileUpdated = "account:profile:updated"
	// EventAccountProfileVerified is generated from registry.
	EventAccountProfileVerified = "account:profile:verified"
	// EventAutomationBatchFailed is generated from registry.
	EventAutomationBatchFailed = "automation:batch:failed"
	// EventAutomationBatchItemComplete is generated from registry.
	EventAutomationBatchItemComplete = "automation:batch:item-complete"
	// EventAutomationBatchStarted is generated from registry.
	EventAutomationBatchStarted = "automation:batch:started"
	// EventAutomationBatchSummary is generated from registry.
	EventAutomationBatchSummary = "automation:batch:summary"
	// EventAutomationRuleCooldownSkipped is generated from registry.
	EventAutomationRuleCooldownSkipped = "automation:rule:cooldown-skipped"
	// EventAutomationRuleTriggered is generated from registry.
	EventAutomationRuleTriggered = "automation:rule:triggered"
	// EventAutomationScriptActionCompleted is generated from registry.
	EventAutomationScriptActionCompleted = "automation:script:action-completed"
	// EventAutomationScriptActionFailed is generated from registry.
	EventAutomationScriptActionFailed = "automation:script:action-failed"
	// EventAutomationScriptActionStarting is generated from registry.
	EventAutomationScriptActionStarting = "automation:script:action-starting"
	// EventAutomationScriptCancelled is generated from registry.
	EventAutomationScriptCancelled = "automation:script:cancelled"
	// EventAutomationScriptCompleted is generated from registry.
	EventAutomationScriptCompleted = "automation:script:completed"
	// EventAutomationScriptFailed is generated from registry.
	EventAutomationScriptFailed = "automation:script:failed"
	// EventAutomationScriptPaused is generated from registry.
	EventAutomationScriptPaused = "automation:script:paused"
	// EventAutomationScriptResumed is generated from registry.
	EventAutomationScriptResumed = "automation:script:resumed"
	// EventAutomationScriptRetrying is generated from registry.
	EventAutomationScriptRetrying = "automation:script:retrying"
	// EventAutomationScriptStarted is generated from registry.
	EventAutomationScriptStarted = "automation:script:started"
	// EventAutomationTaskCancelled is generated from registry.
	EventAutomationTaskCancelled = "automation:task:cancelled"
	// EventAutomationTaskCompleted is generated from registry.
	EventAutomationTaskCompleted = "automation:task:completed"
	// EventAutomationTaskCreated is generated from registry.
	EventAutomationTaskCreated = "automation:task:created"
	// EventAutomationTaskExpired is generated from registry.
	EventAutomationTaskExpired = "automation:task:expired"
	// EventAutomationTaskFailed is generated from registry.
	EventAutomationTaskFailed = "automation:task:failed"
	// EventAutomationTaskPaused is generated from registry.
	EventAutomationTaskPaused = "automation:task:paused"
	// EventAutomationTaskProgress is generated from registry.
	EventAutomationTaskProgress = "automation:task:progress"
	// EventAutomationTaskResumed is generated from registry.
	EventAutomationTaskResumed = "automation:task:resumed"
	// EventAutomationTaskRetried is generated from registry.
	EventAutomationTaskRetried = "automation:task:retried"
	// EventAutomationTaskStarted is generated from registry.
	EventAutomationTaskStarted = "automation:task:started"
	// EventBackupExportCollecting is generated from registry.
	EventBackupExportCollecting = "backup:export:collecting"
	// EventBackupExportCompleted is generated from registry.
	EventBackupExportCompleted = "backup:export:completed"
	// EventBackupExportCompressing is generated from registry.
	EventBackupExportCompressing = "backup:export:compressing"
	// EventBackupExportStarted is generated from registry.
	EventBackupExportStarted = "backup:export:started"
	// EventBackupImportCompleted is generated from registry.
	EventBackupImportCompleted = "backup:import:completed"
	// EventBackupImportRestoring is generated from registry.
	EventBackupImportRestoring = "backup:import:restoring"
	// EventBackupImportStarted is generated from registry.
	EventBackupImportStarted = "backup:import:started"
	// EventBackupImportValidating is generated from registry.
	EventBackupImportValidating = "backup:import:validating"
	// EventBrowserInstanceStartCdpAttached is generated from registry.
	EventBrowserInstanceStartCdpAttached = "browser:instance:start:cdp-attached"
	// EventBrowserInstanceStartCdpAttaching is generated from registry.
	EventBrowserInstanceStartCdpAttaching = "browser:instance:start:cdp-attaching"
	// EventBrowserInstanceStartCheckingRunning is generated from registry.
	EventBrowserInstanceStartCheckingRunning = "browser:instance:start:checking-running"
	// EventBrowserInstanceStartCompleted is generated from registry.
	EventBrowserInstanceStartCompleted = "browser:instance:start:completed"
	// EventBrowserInstanceStartCoreReady is generated from registry.
	EventBrowserInstanceStartCoreReady = "browser:instance:start:core-ready"
	// EventBrowserInstanceStartCoreValidating is generated from registry.
	EventBrowserInstanceStartCoreValidating = "browser:instance:start:core-validating"
	// EventBrowserInstanceStartLauncherSpawned is generated from registry.
	EventBrowserInstanceStartLauncherSpawned = "browser:instance:start:launcher-spawned"
	// EventBrowserInstanceStartLauncherSpawning is generated from registry.
	EventBrowserInstanceStartLauncherSpawning = "browser:instance:start:launcher-spawning"
	// EventBrowserInstanceStartPortAllocated is generated from registry.
	EventBrowserInstanceStartPortAllocated = "browser:instance:start:port-allocated"
	// EventBrowserInstanceStartPortAllocating is generated from registry.
	EventBrowserInstanceStartPortAllocating = "browser:instance:start:port-allocating"
	// EventBrowserInstanceStartProxyReady is generated from registry.
	EventBrowserInstanceStartProxyReady = "browser:instance:start:proxy-ready"
	// EventBrowserInstanceStartProxyStarting is generated from registry.
	EventBrowserInstanceStartProxyStarting = "browser:instance:start:proxy-starting"
	// EventBrowserInstanceStartWindowOpened is generated from registry.
	EventBrowserInstanceStartWindowOpened = "browser:instance:start:window-opened"
	// EventBrowserInstanceStartWindowOpening is generated from registry.
	EventBrowserInstanceStartWindowOpening = "browser:instance:start:window-opening"
	// EventBrowserInstanceStopCdpDetaching is generated from registry.
	EventBrowserInstanceStopCdpDetaching = "browser:instance:stop:cdp-detaching"
	// EventBrowserInstanceStopCleaning is generated from registry.
	EventBrowserInstanceStopCleaning = "browser:instance:stop:cleaning"
	// EventBrowserInstanceStopCompleted is generated from registry.
	EventBrowserInstanceStopCompleted = "browser:instance:stop:completed"
	// EventBrowserInstanceStopDispatching is generated from registry.
	EventBrowserInstanceStopDispatching = "browser:instance:stop:dispatching"
	// EventBrowserInstanceStopProcessKilling is generated from registry.
	EventBrowserInstanceStopProcessKilling = "browser:instance:stop:process-killing"
	// EventBrowserInstanceStopProxyStopping is generated from registry.
	EventBrowserInstanceStopProxyStopping = "browser:instance:stop:proxy-stopping"
	// EventContentCommentDelete is generated from registry.
	EventContentCommentDelete = "content:comment:delete"
	// EventContentCommentPost is generated from registry.
	EventContentCommentPost = "content:comment:post"
	// EventContentCommentReply is generated from registry.
	EventContentCommentReply = "content:comment:reply"
	// EventContentCommentReport is generated from registry.
	EventContentCommentReport = "content:comment:report"
	// EventContentImageDone is generated from registry.
	EventContentImageDone = "content:image:done"
	// EventContentImageFailed is generated from registry.
	EventContentImageFailed = "content:image:failed"
	// EventContentImageProgress is generated from registry.
	EventContentImageProgress = "content:image:progress"
	// EventContentImageUploadStart is generated from registry.
	EventContentImageUploadStart = "content:image:upload-start"
	// EventContentLikeLike is generated from registry.
	EventContentLikeLike = "content:like:like"
	// EventContentLikeUnlike is generated from registry.
	EventContentLikeUnlike = "content:like:unlike"
	// EventContentPublishDeleted is generated from registry.
	EventContentPublishDeleted = "content:publish:deleted"
	// EventContentPublishDraft is generated from registry.
	EventContentPublishDraft = "content:publish:draft"
	// EventContentPublishFailed is generated from registry.
	EventContentPublishFailed = "content:publish:failed"
	// EventContentPublishProcessing is generated from registry.
	EventContentPublishProcessing = "content:publish:processing"
	// EventContentPublishPublished is generated from registry.
	EventContentPublishPublished = "content:publish:published"
	// EventContentPublishReviewed is generated from registry.
	EventContentPublishReviewed = "content:publish:reviewed"
	// EventContentPublishScheduled is generated from registry.
	EventContentPublishScheduled = "content:publish:scheduled"
	// EventContentPublishSubmitted is generated from registry.
	EventContentPublishSubmitted = "content:publish:submitted"
	// EventCoreDownloadCompleted is generated from registry.
	EventCoreDownloadCompleted = "core:download:completed"
	// EventCoreDownloadExtracting is generated from registry.
	EventCoreDownloadExtracting = "core:download:extracting"
	// EventCoreDownloadFailed is generated from registry.
	EventCoreDownloadFailed = "core:download:failed"
	// EventCoreDownloadProgress is generated from registry.
	EventCoreDownloadProgress = "core:download:progress"
	// EventCoreDownloadStarted is generated from registry.
	EventCoreDownloadStarted = "core:download:started"
	// EventCoreDownloadVerifying is generated from registry.
	EventCoreDownloadVerifying = "core:download:verifying"
	// EventDataExportCookiesCompleted is generated from registry.
	EventDataExportCookiesCompleted = "data:export:cookies-completed"
	// EventDataExportCookiesStarted is generated from registry.
	EventDataExportCookiesStarted = "data:export:cookies-started"
	// EventDataExportLogsCompleted is generated from registry.
	EventDataExportLogsCompleted = "data:export:logs-completed"
	// EventDataExportLogsStarted is generated from registry.
	EventDataExportLogsStarted = "data:export:logs-started"
	// EventDataExportProfilesCompleted is generated from registry.
	EventDataExportProfilesCompleted = "data:export:profiles-completed"
	// EventDataExportProfilesStarted is generated from registry.
	EventDataExportProfilesStarted = "data:export:profiles-started"
	// EventDataExportProxiesCompleted is generated from registry.
	EventDataExportProxiesCompleted = "data:export:proxies-completed"
	// EventDataExportProxiesStarted is generated from registry.
	EventDataExportProxiesStarted = "data:export:proxies-started"
	// EventDataScrapeCompleted is generated from registry.
	EventDataScrapeCompleted = "data:scrape:completed"
	// EventDataScrapeExported is generated from registry.
	EventDataScrapeExported = "data:scrape:exported"
	// EventDataScrapePageDone is generated from registry.
	EventDataScrapePageDone = "data:scrape:page-done"
	// EventDataScrapeProgress is generated from registry.
	EventDataScrapeProgress = "data:scrape:progress"
	// EventDataScrapeRateLimited is generated from registry.
	EventDataScrapeRateLimited = "data:scrape:rate-limited"
	// EventDataScrapeStarted is generated from registry.
	EventDataScrapeStarted = "data:scrape:started"
	// EventLicenseActivated is generated from registry.
	EventLicenseActivated = "license:activated"
	// EventLicenseCdkeyInvalid is generated from registry.
	EventLicenseCdkeyInvalid = "license:cdkey-invalid"
	// EventLicenseCdkeyRedeemed is generated from registry.
	EventLicenseCdkeyRedeemed = "license:cdkey-redeemed"
	// EventLicenseExpired is generated from registry.
	EventLicenseExpired = "license:expired"
	// EventLicenseExpiring is generated from registry.
	EventLicenseExpiring = "license:expiring"
	// EventLicenseRenewed is generated from registry.
	EventLicenseRenewed = "license:renewed"
	// EventProxyBridgeClashStarted is generated from registry.
	EventProxyBridgeClashStarted = "proxy:bridge:clash:started"
	// EventProxyBridgeClashStarting is generated from registry.
	EventProxyBridgeClashStarting = "proxy:bridge:clash:starting"
	// EventProxyBridgeReconnected is generated from registry.
	EventProxyBridgeReconnected = "proxy:bridge:reconnected"
	// EventProxyBridgeReconnecting is generated from registry.
	EventProxyBridgeReconnecting = "proxy:bridge:reconnecting"
	// EventProxyBridgeSingboxStarted is generated from registry.
	EventProxyBridgeSingboxStarted = "proxy:bridge:singbox:started"
	// EventProxyBridgeSingboxStarting is generated from registry.
	EventProxyBridgeSingboxStarting = "proxy:bridge:singbox:starting"
	// EventProxyBridgeXrayStarted is generated from registry.
	EventProxyBridgeXrayStarted = "proxy:bridge:xray:started"
	// EventProxyBridgeXrayStarting is generated from registry.
	EventProxyBridgeXrayStarting = "proxy:bridge:xray:starting"
	// EventProxyQualityBestNode is generated from registry.
	EventProxyQualityBestNode = "proxy:quality:best-node"
	// EventProxyQualityHealthDrop is generated from registry.
	EventProxyQualityHealthDrop = "proxy:quality:health-drop"
	// EventProxyQualityLatencySpike is generated from registry.
	EventProxyQualityLatencySpike = "proxy:quality:latency-spike"
	// EventProxyQualityNodeAdded is generated from registry.
	EventProxyQualityNodeAdded = "proxy:quality:node-added"
	// EventProxyQualityNodeRemoved is generated from registry.
	EventProxyQualityNodeRemoved = "proxy:quality:node-removed"
	// EventProxyQualityNodeRotated is generated from registry.
	EventProxyQualityNodeRotated = "proxy:quality:node-rotated"
	// EventProxyQualityPoolExhausted is generated from registry.
	EventProxyQualityPoolExhausted = "proxy:quality:pool-exhausted"
	// EventProxyQualityScoreChange is generated from registry.
	EventProxyQualityScoreChange = "proxy:quality:score-change"
	// EventProxyRotationCompleted is generated from registry.
	EventProxyRotationCompleted = "proxy:rotation:completed"
	// EventProxyRotationFailed is generated from registry.
	EventProxyRotationFailed = "proxy:rotation:failed"
	// EventProxyRotationSkipped is generated from registry.
	EventProxyRotationSkipped = "proxy:rotation:skipped"
	// EventProxyRotationTriggered is generated from registry.
	EventProxyRotationTriggered = "proxy:rotation:triggered"
	// EventSettingsChangeAppConfig is generated from registry.
	EventSettingsChangeAppConfig = "settings:change:app-config"
	// EventSettingsChangeBackupScope is generated from registry.
	EventSettingsChangeBackupScope = "settings:change:backup-scope"
	// EventSettingsChangeBookmark is generated from registry.
	EventSettingsChangeBookmark = "settings:change:bookmark"
	// EventSettingsChangeBrowserCore is generated from registry.
	EventSettingsChangeBrowserCore = "settings:change:browser-core"
	// EventSettingsChangeBrowserProxy is generated from registry.
	EventSettingsChangeBrowserProxy = "settings:change:browser-proxy"
	// EventSettingsChangeGroupSort is generated from registry.
	EventSettingsChangeGroupSort = "settings:change:group-sort"
	// EventSettingsChangeInterceptor is generated from registry.
	EventSettingsChangeInterceptor = "settings:change:interceptor"
	// EventSettingsChangeLaunchDefaults is generated from registry.
	EventSettingsChangeLaunchDefaults = "settings:change:launch-defaults"
	// EventSettingsChangeLaunchServer is generated from registry.
	EventSettingsChangeLaunchServer = "settings:change:launch-server"
	// EventSettingsChangeLogLevel is generated from registry.
	EventSettingsChangeLogLevel = "settings:change:log-level"
	// EventSettingsChangeProfileDefaults is generated from registry.
	EventSettingsChangeProfileDefaults = "settings:change:profile-defaults"
	// EventSettingsChangeRuntimeConfig is generated from registry.
	EventSettingsChangeRuntimeConfig = "settings:change:runtime-config"
	// EventSystemHealthConfigReload is generated from registry.
	EventSystemHealthConfigReload = "system:health:config-reload"
	// EventSystemHealthCpuHigh is generated from registry.
	EventSystemHealthCpuHigh = "system:health:cpu-high"
	// EventSystemHealthCpuNormal is generated from registry.
	EventSystemHealthCpuNormal = "system:health:cpu-normal"
	// EventSystemHealthDbSize is generated from registry.
	EventSystemHealthDbSize = "system:health:db-size"
	// EventSystemHealthDbVacuum is generated from registry.
	EventSystemHealthDbVacuum = "system:health:db-vacuum"
	// EventSystemHealthDiskCritical is generated from registry.
	EventSystemHealthDiskCritical = "system:health:disk-critical"
	// EventSystemHealthDiskLow is generated from registry.
	EventSystemHealthDiskLow = "system:health:disk-low"
	// EventSystemHealthGcTriggered is generated from registry.
	EventSystemHealthGcTriggered = "system:health:gc-triggered"
	// EventSystemHealthGoroutineCount is generated from registry.
	EventSystemHealthGoroutineCount = "system:health:goroutine-count"
	// EventSystemHealthMemoryCritical is generated from registry.
	EventSystemHealthMemoryCritical = "system:health:memory-critical"
	// EventSystemHealthMemoryHigh is generated from registry.
	EventSystemHealthMemoryHigh = "system:health:memory-high"
	// EventSystemHealthMemoryNormal is generated from registry.
	EventSystemHealthMemoryNormal = "system:health:memory-normal"
	// EventSystemHealthPanicRecovered is generated from registry.
	EventSystemHealthPanicRecovered = "system:health:panic-recovered"
	// EventSystemHealthProcessCount is generated from registry.
	EventSystemHealthProcessCount = "system:health:process-count"
	// EventSystemHealthShutdownInitiated is generated from registry.
	EventSystemHealthShutdownInitiated = "system:health:shutdown-initiated"
	// EventSystemHealthStartupComplete is generated from registry.
	EventSystemHealthStartupComplete = "system:health:startup-complete"
	// EventSystemRecoveryAutoRestart is generated from registry.
	EventSystemRecoveryAutoRestart = "system:recovery:auto-restart"
	// EventSystemRecoveryAutoStop is generated from registry.
	EventSystemRecoveryAutoStop = "system:recovery:auto-stop"
	// EventSystemRecoveryCrashLoopDetected is generated from registry.
	EventSystemRecoveryCrashLoopDetected = "system:recovery:crash-loop-detected"
	// EventSystemRecoveryDbRecovered is generated from registry.
	EventSystemRecoveryDbRecovered = "system:recovery:db-recovered"
	// EventSystemRecoveryLockfileCleaned is generated from registry.
	EventSystemRecoveryLockfileCleaned = "system:recovery:lockfile-cleaned"
	// EventSystemRecoveryOrphanCleanup is generated from registry.
	EventSystemRecoveryOrphanCleanup = "system:recovery:orphan-cleanup"
	// EventSystemRecoveryPortReleased is generated from registry.
	EventSystemRecoveryPortReleased = "system:recovery:port-released"
	// EventSystemRecoveryProfileRepaired is generated from registry.
	EventSystemRecoveryProfileRepaired = "system:recovery:profile-repaired"
)
