// Code generated by backend/cmd/gen-events. DO NOT EDIT.
// Source: backend/internal/events/registry.go

package events

import (
	"context"
	"encoding/json"
)

// ─── Payload Types ──────────────────────────────────────────────

// AccountFollowBlockPayload is the payload for event "account:follow:block".
type AccountFollowBlockPayload struct {
	ProfileId string `json:"profileId"`
	TargetUserId string `json:"targetUserId"`
}

// AccountFollowFollowPayload is the payload for event "account:follow:follow".
type AccountFollowFollowPayload struct {
	ProfileId string `json:"profileId"`
	TargetUserId string `json:"targetUserId"`
	TargetUserName string `json:"targetUserName"`
}

// AccountFollowMutePayload is the payload for event "account:follow:mute".
type AccountFollowMutePayload struct {
	ProfileId string `json:"profileId"`
	TargetUserId string `json:"targetUserId"`
}

// AccountFollowUnfollowPayload is the payload for event "account:follow:unfollow".
type AccountFollowUnfollowPayload struct {
	ProfileId string `json:"profileId"`
	TargetUserId string `json:"targetUserId"`
}

// AccountLoginAttemptPayload is the payload for event "account:login:attempt".
type AccountLoginAttemptPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
	LoginMethod string `json:"loginMethod"`
}

// AccountLoginBlockedPayload is the payload for event "account:login:blocked".
type AccountLoginBlockedPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
	BlockReason string `json:"blockReason"`
	BlockUntil string `json:"blockUntil"`
}

// AccountLoginCaptchaPayload is the payload for event "account:login:captcha".
type AccountLoginCaptchaPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
	CaptchaType string `json:"captchaType"`
}

// AccountLoginFailedPayload is the payload for event "account:login:failed".
type AccountLoginFailedPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
	Reason string `json:"reason"`
}

// AccountLoginSessionExpiredPayload is the payload for event "account:login:session-expired".
type AccountLoginSessionExpiredPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
}

// AccountLoginSuccessPayload is the payload for event "account:login:success".
type AccountLoginSuccessPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
	AccountId string `json:"accountId"`
	LoginDuration int64 `json:"loginDuration"`
}

// AccountLoginTimeoutPayload is the payload for event "account:login:timeout".
type AccountLoginTimeoutPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
	TimeoutSeconds int `json:"timeoutSeconds"`
}

// AccountLoginVerifyPayload is the payload for event "account:login:verify".
type AccountLoginVerifyPayload struct {
	ProfileId string `json:"profileId"`
	AccountName string `json:"accountName"`
	VerifyMethod string `json:"verifyMethod"`
}

// AccountProfileAvatarChangedPayload is the payload for event "account:profile:avatar-changed".
type AccountProfileAvatarChangedPayload struct {
	ProfileId string `json:"profileId"`
}

// AccountProfileReportedPayload is the payload for event "account:profile:reported".
type AccountProfileReportedPayload struct {
	ProfileId string `json:"profileId"`
	ReportReason string `json:"reportReason"`
}

// AccountProfileUpdatedPayload is the payload for event "account:profile:updated".
type AccountProfileUpdatedPayload struct {
	ProfileId string `json:"profileId"`
	Fields []string `json:"fields"`
}

// AccountProfileVerifiedPayload is the payload for event "account:profile:verified".
type AccountProfileVerifiedPayload struct {
	ProfileId string `json:"profileId"`
	VerifyType string `json:"verifyType"`
	Status string `json:"status"`
}

// AutomationBatchFailedPayload is the payload for event "automation:batch:failed".
type AutomationBatchFailedPayload struct {
	BatchId string `json:"batchId"`
	Error string `json:"error"`
}

// AutomationBatchItemCompletePayload is the payload for event "automation:batch:item-complete".
type AutomationBatchItemCompletePayload struct {
	BatchId string `json:"batchId"`
	TaskId string `json:"taskId"`
	Completed int `json:"completed"`
	Total int `json:"total"`
}

// AutomationBatchStartedPayload is the payload for event "automation:batch:started".
type AutomationBatchStartedPayload struct {
	BatchId string `json:"batchId"`
	TotalTasks int `json:"totalTasks"`
}

// AutomationBatchSummaryPayload is the payload for event "automation:batch:summary".
type AutomationBatchSummaryPayload struct {
	BatchId string `json:"batchId"`
	Total int `json:"total"`
	Success int `json:"success"`
	Failed int `json:"failed"`
	Duration int64 `json:"duration"`
}

// AutomationRuleCooldownSkippedPayload is the payload for event "automation:rule:cooldown-skipped".
type AutomationRuleCooldownSkippedPayload struct {
	RuleId string `json:"ruleId"`
	RuleName string `json:"ruleName"`
}

// AutomationRuleTriggeredPayload is the payload for event "automation:rule:triggered".
type AutomationRuleTriggeredPayload struct {
	RuleId string `json:"ruleId"`
	RuleName string `json:"ruleName"`
	TriggerEvent string `json:"triggerEvent"`
}

// AutomationScriptActionCompletedPayload is the payload for event "automation:script:action-completed".
type AutomationScriptActionCompletedPayload struct {
	TaskId string `json:"taskId"`
	ActionType string `json:"actionType"`
	DurationMs int64 `json:"durationMs"`
}

// AutomationScriptActionFailedPayload is the payload for event "automation:script:action-failed".
type AutomationScriptActionFailedPayload struct {
	TaskId string `json:"taskId"`
	ActionType string `json:"actionType"`
	Error string `json:"error"`
}

// AutomationScriptActionStartingPayload is the payload for event "automation:script:action-starting".
type AutomationScriptActionStartingPayload struct {
	TaskId string `json:"taskId"`
	ActionType string `json:"actionType"`
	Target string `json:"target"`
}

// AutomationScriptCancelledPayload is the payload for event "automation:script:cancelled".
type AutomationScriptCancelledPayload struct {
	TaskId string `json:"taskId"`
}

// AutomationScriptCompletedPayload is the payload for event "automation:script:completed".
type AutomationScriptCompletedPayload struct {
	TaskId string `json:"taskId"`
	DurationMs int64 `json:"durationMs"`
}

// AutomationScriptFailedPayload is the payload for event "automation:script:failed".
type AutomationScriptFailedPayload struct {
	TaskId string `json:"taskId"`
	Error string `json:"error"`
}

// AutomationScriptPausedPayload is the payload for event "automation:script:paused".
type AutomationScriptPausedPayload struct {
	TaskId string `json:"taskId"`
	Reason string `json:"reason"`
}

// AutomationScriptResumedPayload is the payload for event "automation:script:resumed".
type AutomationScriptResumedPayload struct {
	TaskId string `json:"taskId"`
}

// AutomationScriptRetryingPayload is the payload for event "automation:script:retrying".
type AutomationScriptRetryingPayload struct {
	TaskId string `json:"taskId"`
	Attempt int `json:"attempt"`
	MaxRetries int `json:"maxRetries"`
}

// AutomationScriptStartedPayload is the payload for event "automation:script:started".
type AutomationScriptStartedPayload struct {
	TaskId string `json:"taskId"`
	TaskName string `json:"taskName"`
}

// AutomationTaskCancelledPayload is the payload for event "automation:task:cancelled".
type AutomationTaskCancelledPayload struct {
	TaskId string `json:"taskId"`
}

// AutomationTaskCompletedPayload is the payload for event "automation:task:completed".
type AutomationTaskCompletedPayload struct {
	TaskId string `json:"taskId"`
	Duration int64 `json:"duration"`
	Result map[string]interface{} `json:"result"`
}

// AutomationTaskCreatedPayload is the payload for event "automation:task:created".
type AutomationTaskCreatedPayload struct {
	TaskId string `json:"taskId"`
	TaskName string `json:"taskName"`
	TriggerType string `json:"triggerType"`
	ProfileId string `json:"profileId"`
}

// AutomationTaskExpiredPayload is the payload for event "automation:task:expired".
type AutomationTaskExpiredPayload struct {
	TaskId string `json:"taskId"`
	ExpiredAt string `json:"expiredAt"`
}

// AutomationTaskFailedPayload is the payload for event "automation:task:failed".
type AutomationTaskFailedPayload struct {
	TaskId string `json:"taskId"`
	Error string `json:"error"`
	Step string `json:"step"`
}

// AutomationTaskPausedPayload is the payload for event "automation:task:paused".
type AutomationTaskPausedPayload struct {
	TaskId string `json:"taskId"`
}

// AutomationTaskProgressPayload is the payload for event "automation:task:progress".
type AutomationTaskProgressPayload struct {
	TaskId string `json:"taskId"`
	Progress int `json:"progress"`
	CurrentStep string `json:"currentStep"`
}

// AutomationTaskResumedPayload is the payload for event "automation:task:resumed".
type AutomationTaskResumedPayload struct {
	TaskId string `json:"taskId"`
}

// AutomationTaskRetriedPayload is the payload for event "automation:task:retried".
type AutomationTaskRetriedPayload struct {
	TaskId string `json:"taskId"`
	Attempt int `json:"attempt"`
	MaxRetries int `json:"maxRetries"`
}

// AutomationTaskStartedPayload is the payload for event "automation:task:started".
type AutomationTaskStartedPayload struct {
	TaskId string `json:"taskId"`
	TaskName string `json:"taskName"`
	ProfileId string `json:"profileId"`
}

// BackupExportCollectingPayload is the payload for event "backup:export:collecting".
type BackupExportCollectingPayload struct {
	Files int `json:"files"`
}

// BackupExportCompletedPayload is the payload for event "backup:export:completed".
type BackupExportCompletedPayload struct {
	Path string `json:"path"`
	SizeBytes int64 `json:"sizeBytes"`
}

// BackupExportCompressingPayload is the payload for event "backup:export:compressing".
type BackupExportCompressingPayload struct {
	SizeBytes int64 `json:"sizeBytes"`
}

// BackupExportStartedPayload is the payload for event "backup:export:started".
type BackupExportStartedPayload struct {
	Scope string `json:"scope"`
}

// BackupImportCompletedPayload is the payload for event "backup:import:completed".
type BackupImportCompletedPayload struct {
	Entries int `json:"entries"`
}

// BackupImportRestoringPayload is the payload for event "backup:import:restoring".
type BackupImportRestoringPayload struct {
	Entries int `json:"entries"`
}

// BackupImportStartedPayload is the payload for event "backup:import:started".
type BackupImportStartedPayload struct {
	Path string `json:"path"`
}

// BrowserInstanceCrashedPayload is the payload for event "browser:instance:crashed".
type BrowserInstanceCrashedPayload struct {
	ProfileId string `json:"profileId"`
	ProfileName string `json:"profileName"`
	Error string `json:"error"`
}

// BrowserInstanceStartCdpAttachedPayload is the payload for event "browser:instance:start:cdp-attached".
type BrowserInstanceStartCdpAttachedPayload struct {
	ProfileId string `json:"profileId"`
	CdpUrl string `json:"cdpUrl"`
}

// BrowserInstanceStartCdpAttachingPayload is the payload for event "browser:instance:start:cdp-attaching".
type BrowserInstanceStartCdpAttachingPayload struct {
	ProfileId string `json:"profileId"`
	DebugPort int `json:"debugPort"`
}

// BrowserInstanceStartCheckingRunningPayload is the payload for event "browser:instance:start:checking-running".
type BrowserInstanceStartCheckingRunningPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStartCompletedPayload is the payload for event "browser:instance:start:completed".
type BrowserInstanceStartCompletedPayload struct {
	ProfileId string `json:"profileId"`
	DurationMs int64 `json:"durationMs"`
	CdpUrl string `json:"cdpUrl"`
}

// BrowserInstanceStartCoreReadyPayload is the payload for event "browser:instance:start:core-ready".
type BrowserInstanceStartCoreReadyPayload struct {
	ProfileId string `json:"profileId"`
	CorePath string `json:"corePath"`
}

// BrowserInstanceStartCoreValidatingPayload is the payload for event "browser:instance:start:core-validating".
type BrowserInstanceStartCoreValidatingPayload struct {
	ProfileId string `json:"profileId"`
	CoreId string `json:"coreId"`
}

// BrowserInstanceStartLauncherSpawnedPayload is the payload for event "browser:instance:start:launcher-spawned".
type BrowserInstanceStartLauncherSpawnedPayload struct {
	ProfileId string `json:"profileId"`
	Pid int `json:"pid"`
}

// BrowserInstanceStartLauncherSpawningPayload is the payload for event "browser:instance:start:launcher-spawning".
type BrowserInstanceStartLauncherSpawningPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStartPortAllocatedPayload is the payload for event "browser:instance:start:port-allocated".
type BrowserInstanceStartPortAllocatedPayload struct {
	ProfileId string `json:"profileId"`
	DebugPort int `json:"debugPort"`
}

// BrowserInstanceStartPortAllocatingPayload is the payload for event "browser:instance:start:port-allocating".
type BrowserInstanceStartPortAllocatingPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStartProxyReadyPayload is the payload for event "browser:instance:start:proxy-ready".
type BrowserInstanceStartProxyReadyPayload struct {
	ProfileId string `json:"profileId"`
	ProxyPort int `json:"proxyPort"`
}

// BrowserInstanceStartProxyStartingPayload is the payload for event "browser:instance:start:proxy-starting".
type BrowserInstanceStartProxyStartingPayload struct {
	ProfileId string `json:"profileId"`
	ProxyId string `json:"proxyId"`
}

// BrowserInstanceStartWindowOpenedPayload is the payload for event "browser:instance:start:window-opened".
type BrowserInstanceStartWindowOpenedPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStartWindowOpeningPayload is the payload for event "browser:instance:start:window-opening".
type BrowserInstanceStartWindowOpeningPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStartedPayload is the payload for event "browser:instance:started".
type BrowserInstanceStartedPayload struct {
	ProfileId string `json:"profileId"`
	ProfileName string `json:"profileName"`
	DebugPort int `json:"debugPort"`
	DebugReady bool `json:"debugReady"`
	Pid int `json:"pid"`
	Reused bool `json:"reused"`
	Running bool `json:"running"`
	RuntimeWarning string `json:"runtimeWarning"`
}

// BrowserInstanceStopCdpDetachingPayload is the payload for event "browser:instance:stop:cdp-detaching".
type BrowserInstanceStopCdpDetachingPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStopCleaningPayload is the payload for event "browser:instance:stop:cleaning".
type BrowserInstanceStopCleaningPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStopCompletedPayload is the payload for event "browser:instance:stop:completed".
type BrowserInstanceStopCompletedPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStopDispatchingPayload is the payload for event "browser:instance:stop:dispatching".
type BrowserInstanceStopDispatchingPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStopProcessKillingPayload is the payload for event "browser:instance:stop:process-killing".
type BrowserInstanceStopProcessKillingPayload struct {
	ProfileId string `json:"profileId"`
	Pid int `json:"pid"`
}

// BrowserInstanceStopProxyStoppingPayload is the payload for event "browser:instance:stop:proxy-stopping".
type BrowserInstanceStopProxyStoppingPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceStoppedPayload is the payload for event "browser:instance:stopped".
type BrowserInstanceStoppedPayload struct {
	ProfileId string `json:"profileId"`
}

// BrowserInstanceUpdatedPayload is the payload for event "browser:instance:updated".
type BrowserInstanceUpdatedPayload struct {
	ProfileId string `json:"profileId"`
	ProfileName string `json:"profileName"`
	DebugPort int `json:"debugPort"`
	DebugReady bool `json:"debugReady"`
	Pid int `json:"pid"`
	Running bool `json:"running"`
	RuntimeWarning string `json:"runtimeWarning"`
}

// ContentCommentDeletePayload is the payload for event "content:comment:delete".
type ContentCommentDeletePayload struct {
	ProfileId string `json:"profileId"`
	CommentId string `json:"commentId"`
}

// ContentCommentPostPayload is the payload for event "content:comment:post".
type ContentCommentPostPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
	CommentId string `json:"commentId"`
}

// ContentCommentReplyPayload is the payload for event "content:comment:reply".
type ContentCommentReplyPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
	ParentCommentId string `json:"parentCommentId"`
}

// ContentCommentReportPayload is the payload for event "content:comment:report".
type ContentCommentReportPayload struct {
	ProfileId string `json:"profileId"`
	CommentId string `json:"commentId"`
	Reason string `json:"reason"`
}

// ContentImageDonePayload is the payload for event "content:image:done".
type ContentImageDonePayload struct {
	ProfileId string `json:"profileId"`
	ImageUrl string `json:"imageUrl"`
	ImageId string `json:"imageId"`
}

// ContentImageFailedPayload is the payload for event "content:image:failed".
type ContentImageFailedPayload struct {
	ProfileId string `json:"profileId"`
	FileName string `json:"fileName"`
	Reason string `json:"reason"`
}

// ContentImageProgressPayload is the payload for event "content:image:progress".
type ContentImageProgressPayload struct {
	ProfileId string `json:"profileId"`
	Progress int `json:"progress"`
	FileName string `json:"fileName"`
}

// ContentImageUploadStartPayload is the payload for event "content:image:upload-start".
type ContentImageUploadStartPayload struct {
	ProfileId string `json:"profileId"`
	FileName string `json:"fileName"`
	FileSize int64 `json:"fileSize"`
}

// ContentLikeLikePayload is the payload for event "content:like:like".
type ContentLikeLikePayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
}

// ContentLikeUnlikePayload is the payload for event "content:like:unlike".
type ContentLikeUnlikePayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
}

// ContentPublishDeletedPayload is the payload for event "content:publish:deleted".
type ContentPublishDeletedPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
}

// ContentPublishDraftPayload is the payload for event "content:publish:draft".
type ContentPublishDraftPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
	Title string `json:"title"`
}

// ContentPublishFailedPayload is the payload for event "content:publish:failed".
type ContentPublishFailedPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
	Reason string `json:"reason"`
}

// ContentPublishProcessingPayload is the payload for event "content:publish:processing".
type ContentPublishProcessingPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
}

// ContentPublishPublishedPayload is the payload for event "content:publish:published".
type ContentPublishPublishedPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
	NoteUrl string `json:"noteUrl"`
}

// ContentPublishReviewedPayload is the payload for event "content:publish:reviewed".
type ContentPublishReviewedPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
	Status string `json:"status"`
	ReviewNote string `json:"reviewNote"`
}

// ContentPublishScheduledPayload is the payload for event "content:publish:scheduled".
type ContentPublishScheduledPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
	ScheduledAt string `json:"scheduledAt"`
}

// ContentPublishSubmittedPayload is the payload for event "content:publish:submitted".
type ContentPublishSubmittedPayload struct {
	ProfileId string `json:"profileId"`
	NoteId string `json:"noteId"`
}

// CoreDownloadCompletedPayload is the payload for event "core:download:completed".
type CoreDownloadCompletedPayload struct {
	Version string `json:"version"`
	Path string `json:"path"`
}

// CoreDownloadExtractingPayload is the payload for event "core:download:extracting".
type CoreDownloadExtractingPayload struct {
	Path string `json:"path"`
}

// CoreDownloadFailedPayload is the payload for event "core:download:failed".
type CoreDownloadFailedPayload struct {
	Error string `json:"error"`
	Version string `json:"version"`
}

// CoreDownloadProgressPayload is the payload for event "core:download:progress".
type CoreDownloadProgressPayload struct {
	Percent float64 `json:"percent"`
	Downloaded int64 `json:"downloaded"`
	Total int64 `json:"total"`
}

// CoreDownloadStartedPayload is the payload for event "core:download:started".
type CoreDownloadStartedPayload struct {
	Version string `json:"version"`
	Url string `json:"url"`
}

// DataExportCookiesCompletedPayload is the payload for event "data:export:cookies-completed".
type DataExportCookiesCompletedPayload struct {
	ProfileId string `json:"profileId"`
	Count int `json:"count"`
}

// DataExportCookiesStartedPayload is the payload for event "data:export:cookies-started".
type DataExportCookiesStartedPayload struct {
	ProfileId string `json:"profileId"`
}

// DataExportLogsCompletedPayload is the payload for event "data:export:logs-completed".
type DataExportLogsCompletedPayload struct {
	Count int `json:"count"`
}

// DataExportProfilesCompletedPayload is the payload for event "data:export:profiles-completed".
type DataExportProfilesCompletedPayload struct {
	Count int `json:"count"`
	Path string `json:"path"`
}

// DataExportProfilesStartedPayload is the payload for event "data:export:profiles-started".
type DataExportProfilesStartedPayload struct {
	Count int `json:"count"`
}

// DataExportProxiesCompletedPayload is the payload for event "data:export:proxies-completed".
type DataExportProxiesCompletedPayload struct {
	Count int `json:"count"`
	Path string `json:"path"`
}

// DataExportProxiesStartedPayload is the payload for event "data:export:proxies-started".
type DataExportProxiesStartedPayload struct {
	Count int `json:"count"`
}

// DataScrapeCompletedPayload is the payload for event "data:scrape:completed".
type DataScrapeCompletedPayload struct {
	ProfileId string `json:"profileId"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
	Duration int64 `json:"duration"`
}

// DataScrapeExportedPayload is the payload for event "data:scrape:exported".
type DataScrapeExportedPayload struct {
	ProfileId string `json:"profileId"`
	Format string `json:"format"`
	FilePath string `json:"filePath"`
	ItemCount int `json:"itemCount"`
}

// DataScrapePageDonePayload is the payload for event "data:scrape:page-done".
type DataScrapePageDonePayload struct {
	ProfileId string `json:"profileId"`
	PageUrl string `json:"pageUrl"`
	ItemsOnPage int `json:"itemsOnPage"`
}

// DataScrapeProgressPayload is the payload for event "data:scrape:progress".
type DataScrapeProgressPayload struct {
	ProfileId string `json:"profileId"`
	PagesScraped int `json:"pagesScraped"`
	ItemsFound int `json:"itemsFound"`
}

// DataScrapeRateLimitedPayload is the payload for event "data:scrape:rate-limited".
type DataScrapeRateLimitedPayload struct {
	ProfileId string `json:"profileId"`
	RetryAfter string `json:"retryAfter"`
}

// DataScrapeStartedPayload is the payload for event "data:scrape:started".
type DataScrapeStartedPayload struct {
	ProfileId string `json:"profileId"`
	Target string `json:"target"`
	ExpectedPages int `json:"expectedPages"`
}

// DownloadProgressPayload is the payload for event "download:progress".
type DownloadProgressPayload struct {
	Phase string `json:"phase"`
	Progress int `json:"progress"`
	Message string `json:"message"`
}

// LicenseActivatedPayload is the payload for event "license:activated".
type LicenseActivatedPayload struct {
	MaxLimit int `json:"maxLimit"`
}

// LicenseCdkeyInvalidPayload is the payload for event "license:cdkey-invalid".
type LicenseCdkeyInvalidPayload struct {
	Reason string `json:"reason"`
}

// LicenseCdkeyRedeemedPayload is the payload for event "license:cdkey-redeemed".
type LicenseCdkeyRedeemedPayload struct {
	KeyPrefix string `json:"keyPrefix"`
}

// LicenseExpiringPayload is the payload for event "license:expiring".
type LicenseExpiringPayload struct {
	DaysLeft int `json:"daysLeft"`
}

// LicenseRenewedPayload is the payload for event "license:renewed".
type LicenseRenewedPayload struct {
	NewExpiry string `json:"newExpiry"`
}

// ProxyBridgeClashStartedPayload is the payload for event "proxy:bridge:clash:started".
type ProxyBridgeClashStartedPayload struct {
	ProfileId string `json:"profileId"`
	Port int `json:"port"`
}

// ProxyBridgeClashStartingPayload is the payload for event "proxy:bridge:clash:starting".
type ProxyBridgeClashStartingPayload struct {
	ProfileId string `json:"profileId"`
}

// ProxyBridgeDiedPayload is the payload for event "proxy:bridge:died".
type ProxyBridgeDiedPayload struct {
	Engine string `json:"engine"`
	Key string `json:"key"`
	Error string `json:"error"`
}

// ProxyBridgeFailedPayload is the payload for event "proxy:bridge:failed".
type ProxyBridgeFailedPayload struct {
	ProfileId string `json:"profileId"`
	ProfileName string `json:"profileName"`
	Error string `json:"error"`
}

// ProxyBridgeReconnectedPayload is the payload for event "proxy:bridge:reconnected".
type ProxyBridgeReconnectedPayload struct {
	ProfileId string `json:"profileId"`
	Attempts int `json:"attempts"`
}

// ProxyBridgeReconnectingPayload is the payload for event "proxy:bridge:reconnecting".
type ProxyBridgeReconnectingPayload struct {
	ProfileId string `json:"profileId"`
	Attempt int `json:"attempt"`
	BridgeType string `json:"bridgeType"`
}

// ProxyBridgeSingboxStartedPayload is the payload for event "proxy:bridge:singbox:started".
type ProxyBridgeSingboxStartedPayload struct {
	ProfileId string `json:"profileId"`
	Port int `json:"port"`
}

// ProxyBridgeSingboxStartingPayload is the payload for event "proxy:bridge:singbox:starting".
type ProxyBridgeSingboxStartingPayload struct {
	ProfileId string `json:"profileId"`
}

// ProxyBridgeXrayStartedPayload is the payload for event "proxy:bridge:xray:started".
type ProxyBridgeXrayStartedPayload struct {
	ProfileId string `json:"profileId"`
	Port int `json:"port"`
}

// ProxyBridgeXrayStartingPayload is the payload for event "proxy:bridge:xray:starting".
type ProxyBridgeXrayStartingPayload struct {
	ProfileId string `json:"profileId"`
}

// ProxyIphealthResultPayload is the payload for event "proxy:iphealth:result".
type ProxyIphealthResultPayload struct {
	ProxyId string `json:"proxyId"`
	Ok bool `json:"ok"`
	Ip string `json:"ip"`
	FraudScore int64 `json:"fraudScore"`
	IsResidential bool `json:"isResidential"`
	Country string `json:"country"`
	City string `json:"city"`
}

// ProxyQualityBestNodePayload is the payload for event "proxy:quality:best-node".
type ProxyQualityBestNodePayload struct {
	ProxyId string `json:"proxyId"`
	LatencyMs int64 `json:"latencyMs"`
}

// ProxyQualityHealthDropPayload is the payload for event "proxy:quality:health-drop".
type ProxyQualityHealthDropPayload struct {
	ProxyId string `json:"proxyId"`
	PreviousScore int64 `json:"previousScore"`
	CurrentScore int64 `json:"currentScore"`
}

// ProxyQualityLatencySpikePayload is the payload for event "proxy:quality:latency-spike".
type ProxyQualityLatencySpikePayload struct {
	ProxyId string `json:"proxyId"`
	PreviousMs int64 `json:"previousMs"`
	CurrentMs int64 `json:"currentMs"`
}

// ProxyQualityNodeAddedPayload is the payload for event "proxy:quality:node-added".
type ProxyQualityNodeAddedPayload struct {
	ProxyId string `json:"proxyId"`
	Ip string `json:"ip"`
}

// ProxyQualityNodeRemovedPayload is the payload for event "proxy:quality:node-removed".
type ProxyQualityNodeRemovedPayload struct {
	ProxyId string `json:"proxyId"`
	Reason string `json:"reason"`
}

// ProxyQualityNodeRotatedPayload is the payload for event "proxy:quality:node-rotated".
type ProxyQualityNodeRotatedPayload struct {
	ProxyId string `json:"proxyId"`
	OldIP string `json:"oldIP"`
	NewIP string `json:"newIP"`
}

// ProxyQualityPoolExhaustedPayload is the payload for event "proxy:quality:pool-exhausted".
type ProxyQualityPoolExhaustedPayload struct {
	SourceId string `json:"sourceId"`
	AvailableNodes int `json:"availableNodes"`
}

// ProxyQualityScoreChangePayload is the payload for event "proxy:quality:score-change".
type ProxyQualityScoreChangePayload struct {
	ProxyId string `json:"proxyId"`
	PreviousScore float64 `json:"previousScore"`
	CurrentScore float64 `json:"currentScore"`
}

// ProxyRotationCompletedPayload is the payload for event "proxy:rotation:completed".
type ProxyRotationCompletedPayload struct {
	ProfileId string `json:"profileId"`
	NewProxyId string `json:"newProxyId"`
}

// ProxyRotationFailedPayload is the payload for event "proxy:rotation:failed".
type ProxyRotationFailedPayload struct {
	ProfileId string `json:"profileId"`
	Error string `json:"error"`
}

// ProxyRotationSkippedPayload is the payload for event "proxy:rotation:skipped".
type ProxyRotationSkippedPayload struct {
	ProfileId string `json:"profileId"`
	Reason string `json:"reason"`
}

// ProxyRotationTriggeredPayload is the payload for event "proxy:rotation:triggered".
type ProxyRotationTriggeredPayload struct {
	ProfileId string `json:"profileId"`
	Reason string `json:"reason"`
}

// ProxySpeedResultPayload is the payload for event "proxy:speed:result".
type ProxySpeedResultPayload struct {
	ProxyId string `json:"proxyId"`
	Ok bool `json:"ok"`
	LatencyMs int64 `json:"latencyMs"`
	Error string `json:"error"`
}

// RiskBrowserCrashLoopPayload is the payload for event "risk:browser:crash-loop".
type RiskBrowserCrashLoopPayload struct {
	ProfileId string `json:"profileId"`
	ProfileName string `json:"profileName"`
	CrashCount int `json:"crashCount"`
	Window string `json:"window"`
}

// RiskCaptchaDetectedPayload is the payload for event "risk:captcha:detected".
type RiskCaptchaDetectedPayload struct {
	ProfileId string `json:"profileId"`
	Url string `json:"url"`
	CaptchaType string `json:"captchaType"`
}

// RiskCaptchaFailedPayload is the payload for event "risk:captcha:failed".
type RiskCaptchaFailedPayload struct {
	ProfileId string `json:"profileId"`
	CaptchaType string `json:"captchaType"`
	Error string `json:"error"`
}

// RiskDnsLeakPayload is the payload for event "risk:dns:leak".
type RiskDnsLeakPayload struct {
	ProfileId string `json:"profileId"`
	LeakedDomains []string `json:"leakedDomains"`
}

// RiskFingerprintMismatchPayload is the payload for event "risk:fingerprint:mismatch".
type RiskFingerprintMismatchPayload struct {
	ProfileId string `json:"profileId"`
	Mismatches []string `json:"mismatches"`
}

// RiskFingerprintTimezoneIpPayload is the payload for event "risk:fingerprint:timezone-ip".
type RiskFingerprintTimezoneIpPayload struct {
	ProfileId string `json:"profileId"`
	IpCountry string `json:"ipCountry"`
	IpCity string `json:"ipCity"`
	TimezoneIana string `json:"timezoneIana"`
	IsMismatch bool `json:"isMismatch"`
	MismatchScore int `json:"mismatchScore"`
}

// RiskNodeBannedPayload is the payload for event "risk:node:banned".
type RiskNodeBannedPayload struct {
	ProxyId string `json:"proxyId"`
	Ip string `json:"ip"`
	Reason string `json:"reason"`
}

// RiskNodeGeoJumpPayload is the payload for event "risk:node:geo-jump".
type RiskNodeGeoJumpPayload struct {
	ProxyId string `json:"proxyId"`
	OldIP string `json:"oldIP"`
	NewIP string `json:"newIP"`
}

// RiskNodeOfflinePayload is the payload for event "risk:node:offline".
type RiskNodeOfflinePayload struct {
	ProxyId string `json:"proxyId"`
	Error string `json:"error"`
}

// RiskProfileCorruptedPayload is the payload for event "risk:profile:corrupted".
type RiskProfileCorruptedPayload struct {
	ProfileId string `json:"profileId"`
	Error string `json:"error"`
}

// RiskProxyAuthFailurePayload is the payload for event "risk:proxy:auth-failure".
type RiskProxyAuthFailurePayload struct {
	ProxyId string `json:"proxyId"`
	Error string `json:"error"`
}

// RiskProxyDatacenterPayload is the payload for event "risk:proxy:datacenter".
type RiskProxyDatacenterPayload struct {
	ProxyId string `json:"proxyId"`
	Ip string `json:"ip"`
	FraudScore int64 `json:"fraudScore"`
	IsResidential bool `json:"isResidential"`
	Country string `json:"country"`
}

// RiskProxyHealthDropPayload is the payload for event "risk:proxy:health-drop".
type RiskProxyHealthDropPayload struct {
	ProxyId string `json:"proxyId"`
	Ip string `json:"ip"`
	FraudScore int64 `json:"fraudScore"`
}

// RiskProxyHighLatencyPayload is the payload for event "risk:proxy:high-latency".
type RiskProxyHighLatencyPayload struct {
	ProxyId string `json:"proxyId"`
	LatencyMs int64 `json:"latencyMs"`
}

// RiskSessionCookieClearedPayload is the payload for event "risk:session:cookie-cleared".
type RiskSessionCookieClearedPayload struct {
	ProfileId string `json:"profileId"`
	Domain string `json:"domain"`
}

// RiskSessionRateLimitPayload is the payload for event "risk:session:rate-limit".
type RiskSessionRateLimitPayload struct {
	ProfileId string `json:"profileId"`
	Url string `json:"url"`
	StatusCode int `json:"statusCode"`
}

// RiskSessionSecurityChallengePayload is the payload for event "risk:session:security-challenge".
type RiskSessionSecurityChallengePayload struct {
	ProfileId string `json:"profileId"`
	Url string `json:"url"`
	ChallengeType string `json:"challengeType"`
}

// RiskSystemLowDiskPayload is the payload for event "risk:system:low-disk".
type RiskSystemLowDiskPayload struct {
	DiskPath string `json:"diskPath"`
	FreePercent float64 `json:"freePercent"`
	FreeGB float64 `json:"freeGB"`
}

// RiskSystemMemoryPressurePayload is the payload for event "risk:system:memory-pressure".
type RiskSystemMemoryPressurePayload struct {
	UsedPercent float64 `json:"usedPercent"`
	UsedMB int64 `json:"usedMB"`
	TotalMB int64 `json:"totalMB"`
}

// RiskWebrtcLeakPayload is the payload for event "risk:webrtc:leak".
type RiskWebrtcLeakPayload struct {
	ProfileId string `json:"profileId"`
	LocalIP string `json:"localIP"`
	PublicIP string `json:"publicIP"`
}

// SettingsChangeAppConfigPayload is the payload for event "settings:change:app-config".
type SettingsChangeAppConfigPayload struct {
	Field string `json:"field"`
}

// SettingsChangeBookmarkPayload is the payload for event "settings:change:bookmark".
type SettingsChangeBookmarkPayload struct {
	Count int `json:"count"`
}

// SettingsChangeBrowserCorePayload is the payload for event "settings:change:browser-core".
type SettingsChangeBrowserCorePayload struct {
	CoreId string `json:"coreId"`
}

// SettingsChangeBrowserProxyPayload is the payload for event "settings:change:browser-proxy".
type SettingsChangeBrowserProxyPayload struct {
	ProxyCount int `json:"proxyCount"`
}

// SettingsChangeInterceptorPayload is the payload for event "settings:change:interceptor".
type SettingsChangeInterceptorPayload struct {
	Enabled bool `json:"enabled"`
}

// SettingsChangeLaunchServerPayload is the payload for event "settings:change:launch-server".
type SettingsChangeLaunchServerPayload struct {
	Port int `json:"port"`
}

// SettingsChangeLogLevelPayload is the payload for event "settings:change:log-level".
type SettingsChangeLogLevelPayload struct {
	From string `json:"from"`
	To string `json:"to"`
}

// SystemHealthCpuHighPayload is the payload for event "system:health:cpu-high".
type SystemHealthCpuHighPayload struct {
	Percent float64 `json:"percent"`
}

// SystemHealthDbSizePayload is the payload for event "system:health:db-size".
type SystemHealthDbSizePayload struct {
	SizeMB float64 `json:"sizeMB"`
}

// SystemHealthDbVacuumPayload is the payload for event "system:health:db-vacuum".
type SystemHealthDbVacuumPayload struct {
	BeforeMB float64 `json:"beforeMB"`
	AfterMB float64 `json:"afterMB"`
}

// SystemHealthDiskCriticalPayload is the payload for event "system:health:disk-critical".
type SystemHealthDiskCriticalPayload struct {
	FreeMB int64 `json:"freeMB"`
}

// SystemHealthDiskLowPayload is the payload for event "system:health:disk-low".
type SystemHealthDiskLowPayload struct {
	FreeMB int64 `json:"freeMB"`
	Path string `json:"path"`
}

// SystemHealthGcTriggeredPayload is the payload for event "system:health:gc-triggered".
type SystemHealthGcTriggeredPayload struct {
	BeforeMB int64 `json:"beforeMB"`
	AfterMB int64 `json:"afterMB"`
}

// SystemHealthGoroutineCountPayload is the payload for event "system:health:goroutine-count".
type SystemHealthGoroutineCountPayload struct {
	Count int `json:"count"`
}

// SystemHealthMemoryCriticalPayload is the payload for event "system:health:memory-critical".
type SystemHealthMemoryCriticalPayload struct {
	UsedMB int64 `json:"usedMB"`
	AvailableMB int64 `json:"availableMB"`
}

// SystemHealthMemoryHighPayload is the payload for event "system:health:memory-high".
type SystemHealthMemoryHighPayload struct {
	UsedMB int64 `json:"usedMB"`
	TotalMB int64 `json:"totalMB"`
}

// SystemHealthMemoryNormalPayload is the payload for event "system:health:memory-normal".
type SystemHealthMemoryNormalPayload struct {
	UsedMB int64 `json:"usedMB"`
}

// SystemHealthPanicRecoveredPayload is the payload for event "system:health:panic-recovered".
type SystemHealthPanicRecoveredPayload struct {
	Stack string `json:"stack"`
}

// SystemHealthProcessCountPayload is the payload for event "system:health:process-count".
type SystemHealthProcessCountPayload struct {
	Count int `json:"count"`
}

// SystemHealthShutdownInitiatedPayload is the payload for event "system:health:shutdown-initiated".
type SystemHealthShutdownInitiatedPayload struct {
	Reason string `json:"reason"`
}

// SystemHealthStartupCompletePayload is the payload for event "system:health:startup-complete".
type SystemHealthStartupCompletePayload struct {
	DurationMs int64 `json:"durationMs"`
}

// SystemRecoveryAutoRestartPayload is the payload for event "system:recovery:auto-restart".
type SystemRecoveryAutoRestartPayload struct {
	ProfileId string `json:"profileId"`
}

// SystemRecoveryAutoStopPayload is the payload for event "system:recovery:auto-stop".
type SystemRecoveryAutoStopPayload struct {
	ProfileId string `json:"profileId"`
	Reason string `json:"reason"`
}

// SystemRecoveryCrashLoopDetectedPayload is the payload for event "system:recovery:crash-loop-detected".
type SystemRecoveryCrashLoopDetectedPayload struct {
	ProfileId string `json:"profileId"`
	Count int `json:"count"`
}

// SystemRecoveryLockfileCleanedPayload is the payload for event "system:recovery:lockfile-cleaned".
type SystemRecoveryLockfileCleanedPayload struct {
	Path string `json:"path"`
}

// SystemRecoveryOrphanCleanupPayload is the payload for event "system:recovery:orphan-cleanup".
type SystemRecoveryOrphanCleanupPayload struct {
	Count int `json:"count"`
}

// SystemRecoveryPortReleasedPayload is the payload for event "system:recovery:port-released".
type SystemRecoveryPortReleasedPayload struct {
	Port int `json:"port"`
}

// SystemRecoveryProfileRepairedPayload is the payload for event "system:recovery:profile-repaired".
type SystemRecoveryProfileRepairedPayload struct {
	ProfileId string `json:"profileId"`
}

// ─── Emitter Functions ──────────────────────────────────────────

// toMap converts a struct to map[string]interface{} via JSON round-trip.
func toMap(v interface{}) map[string]interface{} {
	data, _ := json.Marshal(v)
	var result map[string]interface{}
	_ = json.Unmarshal(data, &result)
	return result
}

// EmitAccountFollowBlock emits a "account:follow:block" event.
// 拉黑用户
func EmitAccountFollowBlock(ctx context.Context, data AccountFollowBlockPayload) {
	EmitAndLog(ctx, EventAccountFollowBlock, toMap(data))
}

// EmitAccountFollowFollow emits a "account:follow:follow" event.
// 关注用户
func EmitAccountFollowFollow(ctx context.Context, data AccountFollowFollowPayload) {
	EmitAndLog(ctx, EventAccountFollowFollow, toMap(data))
}

// EmitAccountFollowMute emits a "account:follow:mute" event.
// 静音用户
func EmitAccountFollowMute(ctx context.Context, data AccountFollowMutePayload) {
	EmitAndLog(ctx, EventAccountFollowMute, toMap(data))
}

// EmitAccountFollowUnfollow emits a "account:follow:unfollow" event.
// 取消关注用户
func EmitAccountFollowUnfollow(ctx context.Context, data AccountFollowUnfollowPayload) {
	EmitAndLog(ctx, EventAccountFollowUnfollow, toMap(data))
}

// EmitAccountLoginAttempt emits a "account:login:attempt" event.
// 账号登录尝试
func EmitAccountLoginAttempt(ctx context.Context, data AccountLoginAttemptPayload) {
	EmitAndLog(ctx, EventAccountLoginAttempt, toMap(data))
}

// EmitAccountLoginBlocked emits a "account:login:blocked" event.
// 账号被限制登录
func EmitAccountLoginBlocked(ctx context.Context, data AccountLoginBlockedPayload) {
	EmitAndLog(ctx, EventAccountLoginBlocked, toMap(data))
}

// EmitAccountLoginCaptcha emits a "account:login:captcha" event.
// 登录触发验证码
func EmitAccountLoginCaptcha(ctx context.Context, data AccountLoginCaptchaPayload) {
	EmitAndLog(ctx, EventAccountLoginCaptcha, toMap(data))
}

// EmitAccountLoginFailed emits a "account:login:failed" event.
// 账号登录失败
func EmitAccountLoginFailed(ctx context.Context, data AccountLoginFailedPayload) {
	EmitAndLog(ctx, EventAccountLoginFailed, toMap(data))
}

// EmitAccountLoginSessionExpired emits a "account:login:session-expired" event.
// 登录会话过期
func EmitAccountLoginSessionExpired(ctx context.Context, data AccountLoginSessionExpiredPayload) {
	EmitAndLog(ctx, EventAccountLoginSessionExpired, toMap(data))
}

// EmitAccountLoginSuccess emits a "account:login:success" event.
// 账号登录成功
func EmitAccountLoginSuccess(ctx context.Context, data AccountLoginSuccessPayload) {
	EmitAndLog(ctx, EventAccountLoginSuccess, toMap(data))
}

// EmitAccountLoginTimeout emits a "account:login:timeout" event.
// 登录超时
func EmitAccountLoginTimeout(ctx context.Context, data AccountLoginTimeoutPayload) {
	EmitAndLog(ctx, EventAccountLoginTimeout, toMap(data))
}

// EmitAccountLoginVerify emits a "account:login:verify" event.
// 需要二次验证（短信/扫码）
func EmitAccountLoginVerify(ctx context.Context, data AccountLoginVerifyPayload) {
	EmitAndLog(ctx, EventAccountLoginVerify, toMap(data))
}

// EmitAccountProfileAvatarChanged emits a "account:profile:avatar-changed" event.
// 头像已更换
func EmitAccountProfileAvatarChanged(ctx context.Context, data AccountProfileAvatarChangedPayload) {
	EmitAndLog(ctx, EventAccountProfileAvatarChanged, toMap(data))
}

// EmitAccountProfileReported emits a "account:profile:reported" event.
// 账号被举报
func EmitAccountProfileReported(ctx context.Context, data AccountProfileReportedPayload) {
	EmitAndLog(ctx, EventAccountProfileReported, toMap(data))
}

// EmitAccountProfileUpdated emits a "account:profile:updated" event.
// 账号资料已更新
func EmitAccountProfileUpdated(ctx context.Context, data AccountProfileUpdatedPayload) {
	EmitAndLog(ctx, EventAccountProfileUpdated, toMap(data))
}

// EmitAccountProfileVerified emits a "account:profile:verified" event.
// 账号认证状态变更
func EmitAccountProfileVerified(ctx context.Context, data AccountProfileVerifiedPayload) {
	EmitAndLog(ctx, EventAccountProfileVerified, toMap(data))
}

// EmitAppRequestClose emits a "app:request-close" event.
// 请求关闭应用
func EmitAppRequestClose(ctx context.Context) {
	EmitAndLog(ctx, EventAppRequestClose)
}

// EmitAutomationBatchFailed emits a "automation:batch:failed" event.
// 批量任务整体失败
func EmitAutomationBatchFailed(ctx context.Context, data AutomationBatchFailedPayload) {
	EmitAndLog(ctx, EventAutomationBatchFailed, toMap(data))
}

// EmitAutomationBatchItemComplete emits a "automation:batch:item-complete" event.
// 批量任务单项完成
func EmitAutomationBatchItemComplete(ctx context.Context, data AutomationBatchItemCompletePayload) {
	EmitAndLog(ctx, EventAutomationBatchItemComplete, toMap(data))
}

// EmitAutomationBatchStarted emits a "automation:batch:started" event.
// 批量任务开始
func EmitAutomationBatchStarted(ctx context.Context, data AutomationBatchStartedPayload) {
	EmitAndLog(ctx, EventAutomationBatchStarted, toMap(data))
}

// EmitAutomationBatchSummary emits a "automation:batch:summary" event.
// 批量任务汇总
func EmitAutomationBatchSummary(ctx context.Context, data AutomationBatchSummaryPayload) {
	EmitAndLog(ctx, EventAutomationBatchSummary, toMap(data))
}

// EmitAutomationRuleCooldownSkipped emits a "automation:rule:cooldown-skipped" event.
// 规则被冷却跳过
func EmitAutomationRuleCooldownSkipped(ctx context.Context, data AutomationRuleCooldownSkippedPayload) {
	EmitAndLog(ctx, EventAutomationRuleCooldownSkipped, toMap(data))
}

// EmitAutomationRuleTriggered emits a "automation:rule:triggered" event.
// 自动响应规则已触发
func EmitAutomationRuleTriggered(ctx context.Context, data AutomationRuleTriggeredPayload) {
	EmitAndLog(ctx, EventAutomationRuleTriggered, toMap(data))
}

// EmitAutomationScriptActionCompleted emits a "automation:script:action-completed" event.
// 脚本动作执行完成
func EmitAutomationScriptActionCompleted(ctx context.Context, data AutomationScriptActionCompletedPayload) {
	EmitAndLog(ctx, EventAutomationScriptActionCompleted, toMap(data))
}

// EmitAutomationScriptActionFailed emits a "automation:script:action-failed" event.
// 脚本动作执行失败
func EmitAutomationScriptActionFailed(ctx context.Context, data AutomationScriptActionFailedPayload) {
	EmitAndLog(ctx, EventAutomationScriptActionFailed, toMap(data))
}

// EmitAutomationScriptActionStarting emits a "automation:script:action-starting" event.
// 脚本动作开始执行
func EmitAutomationScriptActionStarting(ctx context.Context, data AutomationScriptActionStartingPayload) {
	EmitAndLog(ctx, EventAutomationScriptActionStarting, toMap(data))
}

// EmitAutomationScriptCancelled emits a "automation:script:cancelled" event.
// 自动化脚本已取消
func EmitAutomationScriptCancelled(ctx context.Context, data AutomationScriptCancelledPayload) {
	EmitAndLog(ctx, EventAutomationScriptCancelled, toMap(data))
}

// EmitAutomationScriptCompleted emits a "automation:script:completed" event.
// 自动化脚本执行完成
func EmitAutomationScriptCompleted(ctx context.Context, data AutomationScriptCompletedPayload) {
	EmitAndLog(ctx, EventAutomationScriptCompleted, toMap(data))
}

// EmitAutomationScriptFailed emits a "automation:script:failed" event.
// 自动化脚本执行失败
func EmitAutomationScriptFailed(ctx context.Context, data AutomationScriptFailedPayload) {
	EmitAndLog(ctx, EventAutomationScriptFailed, toMap(data))
}

// EmitAutomationScriptPaused emits a "automation:script:paused" event.
// 自动化脚本已暂停
func EmitAutomationScriptPaused(ctx context.Context, data AutomationScriptPausedPayload) {
	EmitAndLog(ctx, EventAutomationScriptPaused, toMap(data))
}

// EmitAutomationScriptResumed emits a "automation:script:resumed" event.
// 自动化脚本已恢复
func EmitAutomationScriptResumed(ctx context.Context, data AutomationScriptResumedPayload) {
	EmitAndLog(ctx, EventAutomationScriptResumed, toMap(data))
}

// EmitAutomationScriptRetrying emits a "automation:script:retrying" event.
// 脚本正在重试
func EmitAutomationScriptRetrying(ctx context.Context, data AutomationScriptRetryingPayload) {
	EmitAndLog(ctx, EventAutomationScriptRetrying, toMap(data))
}

// EmitAutomationScriptStarted emits a "automation:script:started" event.
// 自动化脚本已开始执行
func EmitAutomationScriptStarted(ctx context.Context, data AutomationScriptStartedPayload) {
	EmitAndLog(ctx, EventAutomationScriptStarted, toMap(data))
}

// EmitAutomationTaskCancelled emits a "automation:task:cancelled" event.
// 自动化任务已取消
func EmitAutomationTaskCancelled(ctx context.Context, data AutomationTaskCancelledPayload) {
	EmitAndLog(ctx, EventAutomationTaskCancelled, toMap(data))
}

// EmitAutomationTaskCompleted emits a "automation:task:completed" event.
// 自动化任务执行完成
func EmitAutomationTaskCompleted(ctx context.Context, data AutomationTaskCompletedPayload) {
	EmitAndLog(ctx, EventAutomationTaskCompleted, toMap(data))
}

// EmitAutomationTaskCreated emits a "automation:task:created" event.
// 自动化任务已创建
func EmitAutomationTaskCreated(ctx context.Context, data AutomationTaskCreatedPayload) {
	EmitAndLog(ctx, EventAutomationTaskCreated, toMap(data))
}

// EmitAutomationTaskExpired emits a "automation:task:expired" event.
// 自动化任务已过期
func EmitAutomationTaskExpired(ctx context.Context, data AutomationTaskExpiredPayload) {
	EmitAndLog(ctx, EventAutomationTaskExpired, toMap(data))
}

// EmitAutomationTaskFailed emits a "automation:task:failed" event.
// 自动化任务执行失败
func EmitAutomationTaskFailed(ctx context.Context, data AutomationTaskFailedPayload) {
	EmitAndLog(ctx, EventAutomationTaskFailed, toMap(data))
}

// EmitAutomationTaskPaused emits a "automation:task:paused" event.
// 自动化任务已暂停
func EmitAutomationTaskPaused(ctx context.Context, data AutomationTaskPausedPayload) {
	EmitAndLog(ctx, EventAutomationTaskPaused, toMap(data))
}

// EmitAutomationTaskProgress emits a "automation:task:progress" event.
// 自动化任务执行进度
func EmitAutomationTaskProgress(ctx context.Context, data AutomationTaskProgressPayload) {
	EmitAndLog(ctx, EventAutomationTaskProgress, toMap(data))
}

// EmitAutomationTaskResumed emits a "automation:task:resumed" event.
// 自动化任务已恢复
func EmitAutomationTaskResumed(ctx context.Context, data AutomationTaskResumedPayload) {
	EmitAndLog(ctx, EventAutomationTaskResumed, toMap(data))
}

// EmitAutomationTaskRetried emits a "automation:task:retried" event.
// 自动化任务重试
func EmitAutomationTaskRetried(ctx context.Context, data AutomationTaskRetriedPayload) {
	EmitAndLog(ctx, EventAutomationTaskRetried, toMap(data))
}

// EmitAutomationTaskStarted emits a "automation:task:started" event.
// 自动化任务开始执行
func EmitAutomationTaskStarted(ctx context.Context, data AutomationTaskStartedPayload) {
	EmitAndLog(ctx, EventAutomationTaskStarted, toMap(data))
}

// EmitBackupExportCollecting emits a "backup:export:collecting" event.
// 正在收集备份数据
func EmitBackupExportCollecting(ctx context.Context, data BackupExportCollectingPayload) {
	EmitAndLog(ctx, EventBackupExportCollecting, toMap(data))
}

// EmitBackupExportCompleted emits a "backup:export:completed" event.
// 备份导出已完成
func EmitBackupExportCompleted(ctx context.Context, data BackupExportCompletedPayload) {
	EmitAndLog(ctx, EventBackupExportCompleted, toMap(data))
}

// EmitBackupExportCompressing emits a "backup:export:compressing" event.
// 正在压缩备份包
func EmitBackupExportCompressing(ctx context.Context, data BackupExportCompressingPayload) {
	EmitAndLog(ctx, EventBackupExportCompressing, toMap(data))
}

// EmitBackupExportStarted emits a "backup:export:started" event.
// 备份导出已开始
func EmitBackupExportStarted(ctx context.Context, data BackupExportStartedPayload) {
	EmitAndLog(ctx, EventBackupExportStarted, toMap(data))
}

// EmitBackupImportCompleted emits a "backup:import:completed" event.
// 备份导入已完成
func EmitBackupImportCompleted(ctx context.Context, data BackupImportCompletedPayload) {
	EmitAndLog(ctx, EventBackupImportCompleted, toMap(data))
}

// EmitBackupImportRestoring emits a "backup:import:restoring" event.
// 正在还原数据
func EmitBackupImportRestoring(ctx context.Context, data BackupImportRestoringPayload) {
	EmitAndLog(ctx, EventBackupImportRestoring, toMap(data))
}

// EmitBackupImportStarted emits a "backup:import:started" event.
// 备份导入已开始
func EmitBackupImportStarted(ctx context.Context, data BackupImportStartedPayload) {
	EmitAndLog(ctx, EventBackupImportStarted, toMap(data))
}

// EmitBackupImportValidating emits a "backup:import:validating" event.
// 正在验证备份包完整性
func EmitBackupImportValidating(ctx context.Context) {
	EmitAndLog(ctx, EventBackupImportValidating)
}

// EmitBrowserInstanceCrashed emits a "browser:instance:crashed" event.
// 浏览器实例异常崩溃
func EmitBrowserInstanceCrashed(ctx context.Context, data BrowserInstanceCrashedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceCrashed, toMap(data))
}

// EmitBrowserInstanceStartCdpAttached emits a "browser:instance:start:cdp-attached" event.
// CDP 调试协议已连接
func EmitBrowserInstanceStartCdpAttached(ctx context.Context, data BrowserInstanceStartCdpAttachedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartCdpAttached, toMap(data))
}

// EmitBrowserInstanceStartCdpAttaching emits a "browser:instance:start:cdp-attaching" event.
// 正在连接 CDP 调试协议
func EmitBrowserInstanceStartCdpAttaching(ctx context.Context, data BrowserInstanceStartCdpAttachingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartCdpAttaching, toMap(data))
}

// EmitBrowserInstanceStartCheckingRunning emits a "browser:instance:start:checking-running" event.
// 检查是否已有实例在运行
func EmitBrowserInstanceStartCheckingRunning(ctx context.Context, data BrowserInstanceStartCheckingRunningPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartCheckingRunning, toMap(data))
}

// EmitBrowserInstanceStartCompleted emits a "browser:instance:start:completed" event.
// 实例启动流程全部完成
func EmitBrowserInstanceStartCompleted(ctx context.Context, data BrowserInstanceStartCompletedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartCompleted, toMap(data))
}

// EmitBrowserInstanceStartCoreReady emits a "browser:instance:start:core-ready" event.
// 浏览器内核校验完成
func EmitBrowserInstanceStartCoreReady(ctx context.Context, data BrowserInstanceStartCoreReadyPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartCoreReady, toMap(data))
}

// EmitBrowserInstanceStartCoreValidating emits a "browser:instance:start:core-validating" event.
// 正在校验浏览器内核
func EmitBrowserInstanceStartCoreValidating(ctx context.Context, data BrowserInstanceStartCoreValidatingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartCoreValidating, toMap(data))
}

// EmitBrowserInstanceStartLauncherSpawned emits a "browser:instance:start:launcher-spawned" event.
// 浏览器进程已创建
func EmitBrowserInstanceStartLauncherSpawned(ctx context.Context, data BrowserInstanceStartLauncherSpawnedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartLauncherSpawned, toMap(data))
}

// EmitBrowserInstanceStartLauncherSpawning emits a "browser:instance:start:launcher-spawning" event.
// 正在启动浏览器进程
func EmitBrowserInstanceStartLauncherSpawning(ctx context.Context, data BrowserInstanceStartLauncherSpawningPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartLauncherSpawning, toMap(data))
}

// EmitBrowserInstanceStartPortAllocated emits a "browser:instance:start:port-allocated" event.
// 调试端口分配完成
func EmitBrowserInstanceStartPortAllocated(ctx context.Context, data BrowserInstanceStartPortAllocatedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartPortAllocated, toMap(data))
}

// EmitBrowserInstanceStartPortAllocating emits a "browser:instance:start:port-allocating" event.
// 正在分配调试端口
func EmitBrowserInstanceStartPortAllocating(ctx context.Context, data BrowserInstanceStartPortAllocatingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartPortAllocating, toMap(data))
}

// EmitBrowserInstanceStartProxyReady emits a "browser:instance:start:proxy-ready" event.
// 代理桥接已就绪
func EmitBrowserInstanceStartProxyReady(ctx context.Context, data BrowserInstanceStartProxyReadyPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartProxyReady, toMap(data))
}

// EmitBrowserInstanceStartProxyStarting emits a "browser:instance:start:proxy-starting" event.
// 正在启动代理桥接
func EmitBrowserInstanceStartProxyStarting(ctx context.Context, data BrowserInstanceStartProxyStartingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartProxyStarting, toMap(data))
}

// EmitBrowserInstanceStartWindowOpened emits a "browser:instance:start:window-opened" event.
// 浏览器窗口已打开
func EmitBrowserInstanceStartWindowOpened(ctx context.Context, data BrowserInstanceStartWindowOpenedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartWindowOpened, toMap(data))
}

// EmitBrowserInstanceStartWindowOpening emits a "browser:instance:start:window-opening" event.
// 正在打开浏览器窗口
func EmitBrowserInstanceStartWindowOpening(ctx context.Context, data BrowserInstanceStartWindowOpeningPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStartWindowOpening, toMap(data))
}

// EmitBrowserInstanceStarted emits a "browser:instance:started" event.
// 浏览器实例已启动
func EmitBrowserInstanceStarted(ctx context.Context, data BrowserInstanceStartedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStarted, toMap(data))
}

// EmitBrowserInstanceStopCdpDetaching emits a "browser:instance:stop:cdp-detaching" event.
// 正在断开 CDP 连接
func EmitBrowserInstanceStopCdpDetaching(ctx context.Context, data BrowserInstanceStopCdpDetachingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStopCdpDetaching, toMap(data))
}

// EmitBrowserInstanceStopCleaning emits a "browser:instance:stop:cleaning" event.
// 正在清理临时文件
func EmitBrowserInstanceStopCleaning(ctx context.Context, data BrowserInstanceStopCleaningPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStopCleaning, toMap(data))
}

// EmitBrowserInstanceStopCompleted emits a "browser:instance:stop:completed" event.
// 实例停止流程全部完成
func EmitBrowserInstanceStopCompleted(ctx context.Context, data BrowserInstanceStopCompletedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStopCompleted, toMap(data))
}

// EmitBrowserInstanceStopDispatching emits a "browser:instance:stop:dispatching" event.
// 正在发送停止指令
func EmitBrowserInstanceStopDispatching(ctx context.Context, data BrowserInstanceStopDispatchingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStopDispatching, toMap(data))
}

// EmitBrowserInstanceStopProcessKilling emits a "browser:instance:stop:process-killing" event.
// 正在终止浏览器进程
func EmitBrowserInstanceStopProcessKilling(ctx context.Context, data BrowserInstanceStopProcessKillingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStopProcessKilling, toMap(data))
}

// EmitBrowserInstanceStopProxyStopping emits a "browser:instance:stop:proxy-stopping" event.
// 正在停止代理桥接
func EmitBrowserInstanceStopProxyStopping(ctx context.Context, data BrowserInstanceStopProxyStoppingPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStopProxyStopping, toMap(data))
}

// EmitBrowserInstanceStopped emits a "browser:instance:stopped" event.
// 浏览器实例已停止
func EmitBrowserInstanceStopped(ctx context.Context, data BrowserInstanceStoppedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceStopped, toMap(data))
}

// EmitBrowserInstanceUpdated emits a "browser:instance:updated" event.
// 浏览器实例状态更新
func EmitBrowserInstanceUpdated(ctx context.Context, data BrowserInstanceUpdatedPayload) {
	EmitAndLog(ctx, EventBrowserInstanceUpdated, toMap(data))
}

// EmitContentCommentDelete emits a "content:comment:delete" event.
// 删除评论
func EmitContentCommentDelete(ctx context.Context, data ContentCommentDeletePayload) {
	EmitAndLog(ctx, EventContentCommentDelete, toMap(data))
}

// EmitContentCommentPost emits a "content:comment:post" event.
// 发布评论
func EmitContentCommentPost(ctx context.Context, data ContentCommentPostPayload) {
	EmitAndLog(ctx, EventContentCommentPost, toMap(data))
}

// EmitContentCommentReply emits a "content:comment:reply" event.
// 回复评论
func EmitContentCommentReply(ctx context.Context, data ContentCommentReplyPayload) {
	EmitAndLog(ctx, EventContentCommentReply, toMap(data))
}

// EmitContentCommentReport emits a "content:comment:report" event.
// 举报评论
func EmitContentCommentReport(ctx context.Context, data ContentCommentReportPayload) {
	EmitAndLog(ctx, EventContentCommentReport, toMap(data))
}

// EmitContentImageDone emits a "content:image:done" event.
// 图片上传完成
func EmitContentImageDone(ctx context.Context, data ContentImageDonePayload) {
	EmitAndLog(ctx, EventContentImageDone, toMap(data))
}

// EmitContentImageFailed emits a "content:image:failed" event.
// 图片上传失败
func EmitContentImageFailed(ctx context.Context, data ContentImageFailedPayload) {
	EmitAndLog(ctx, EventContentImageFailed, toMap(data))
}

// EmitContentImageProgress emits a "content:image:progress" event.
// 图片上传进度
func EmitContentImageProgress(ctx context.Context, data ContentImageProgressPayload) {
	EmitAndLog(ctx, EventContentImageProgress, toMap(data))
}

// EmitContentImageUploadStart emits a "content:image:upload-start" event.
// 图片开始上传
func EmitContentImageUploadStart(ctx context.Context, data ContentImageUploadStartPayload) {
	EmitAndLog(ctx, EventContentImageUploadStart, toMap(data))
}

// EmitContentLikeLike emits a "content:like:like" event.
// 点赞笔记
func EmitContentLikeLike(ctx context.Context, data ContentLikeLikePayload) {
	EmitAndLog(ctx, EventContentLikeLike, toMap(data))
}

// EmitContentLikeUnlike emits a "content:like:unlike" event.
// 取消点赞
func EmitContentLikeUnlike(ctx context.Context, data ContentLikeUnlikePayload) {
	EmitAndLog(ctx, EventContentLikeUnlike, toMap(data))
}

// EmitContentPublishDeleted emits a "content:publish:deleted" event.
// 笔记已删除
func EmitContentPublishDeleted(ctx context.Context, data ContentPublishDeletedPayload) {
	EmitAndLog(ctx, EventContentPublishDeleted, toMap(data))
}

// EmitContentPublishDraft emits a "content:publish:draft" event.
// 笔记保存为草稿
func EmitContentPublishDraft(ctx context.Context, data ContentPublishDraftPayload) {
	EmitAndLog(ctx, EventContentPublishDraft, toMap(data))
}

// EmitContentPublishFailed emits a "content:publish:failed" event.
// 笔记发布失败
func EmitContentPublishFailed(ctx context.Context, data ContentPublishFailedPayload) {
	EmitAndLog(ctx, EventContentPublishFailed, toMap(data))
}

// EmitContentPublishProcessing emits a "content:publish:processing" event.
// 笔记审核中
func EmitContentPublishProcessing(ctx context.Context, data ContentPublishProcessingPayload) {
	EmitAndLog(ctx, EventContentPublishProcessing, toMap(data))
}

// EmitContentPublishPublished emits a "content:publish:published" event.
// 笔记发布成功
func EmitContentPublishPublished(ctx context.Context, data ContentPublishPublishedPayload) {
	EmitAndLog(ctx, EventContentPublishPublished, toMap(data))
}

// EmitContentPublishReviewed emits a "content:publish:reviewed" event.
// 笔记审核结果
func EmitContentPublishReviewed(ctx context.Context, data ContentPublishReviewedPayload) {
	EmitAndLog(ctx, EventContentPublishReviewed, toMap(data))
}

// EmitContentPublishScheduled emits a "content:publish:scheduled" event.
// 笔记已定时发布
func EmitContentPublishScheduled(ctx context.Context, data ContentPublishScheduledPayload) {
	EmitAndLog(ctx, EventContentPublishScheduled, toMap(data))
}

// EmitContentPublishSubmitted emits a "content:publish:submitted" event.
// 笔记已提交发布
func EmitContentPublishSubmitted(ctx context.Context, data ContentPublishSubmittedPayload) {
	EmitAndLog(ctx, EventContentPublishSubmitted, toMap(data))
}

// EmitCoreDownloadCompleted emits a "core:download:completed" event.
// 内核下载已完成
func EmitCoreDownloadCompleted(ctx context.Context, data CoreDownloadCompletedPayload) {
	EmitAndLog(ctx, EventCoreDownloadCompleted, toMap(data))
}

// EmitCoreDownloadExtracting emits a "core:download:extracting" event.
// 正在解压内核文件
func EmitCoreDownloadExtracting(ctx context.Context, data CoreDownloadExtractingPayload) {
	EmitAndLog(ctx, EventCoreDownloadExtracting, toMap(data))
}

// EmitCoreDownloadFailed emits a "core:download:failed" event.
// 内核下载失败
func EmitCoreDownloadFailed(ctx context.Context, data CoreDownloadFailedPayload) {
	EmitAndLog(ctx, EventCoreDownloadFailed, toMap(data))
}

// EmitCoreDownloadProgress emits a "core:download:progress" event.
// 内核下载进度更新
func EmitCoreDownloadProgress(ctx context.Context, data CoreDownloadProgressPayload) {
	EmitAndLog(ctx, EventCoreDownloadProgress, toMap(data))
}

// EmitCoreDownloadStarted emits a "core:download:started" event.
// 内核下载已开始
func EmitCoreDownloadStarted(ctx context.Context, data CoreDownloadStartedPayload) {
	EmitAndLog(ctx, EventCoreDownloadStarted, toMap(data))
}

// EmitCoreDownloadVerifying emits a "core:download:verifying" event.
// 正在校验内核文件
func EmitCoreDownloadVerifying(ctx context.Context) {
	EmitAndLog(ctx, EventCoreDownloadVerifying)
}

// EmitDataExportCookiesCompleted emits a "data:export:cookies-completed" event.
// Cookie 导出已完成
func EmitDataExportCookiesCompleted(ctx context.Context, data DataExportCookiesCompletedPayload) {
	EmitAndLog(ctx, EventDataExportCookiesCompleted, toMap(data))
}

// EmitDataExportCookiesStarted emits a "data:export:cookies-started" event.
// Cookie 导出已开始
func EmitDataExportCookiesStarted(ctx context.Context, data DataExportCookiesStartedPayload) {
	EmitAndLog(ctx, EventDataExportCookiesStarted, toMap(data))
}

// EmitDataExportLogsCompleted emits a "data:export:logs-completed" event.
// 事件日志导出已完成
func EmitDataExportLogsCompleted(ctx context.Context, data DataExportLogsCompletedPayload) {
	EmitAndLog(ctx, EventDataExportLogsCompleted, toMap(data))
}

// EmitDataExportLogsStarted emits a "data:export:logs-started" event.
// 事件日志导出已开始
func EmitDataExportLogsStarted(ctx context.Context) {
	EmitAndLog(ctx, EventDataExportLogsStarted)
}

// EmitDataExportProfilesCompleted emits a "data:export:profiles-completed" event.
// 实例数据导出已完成
func EmitDataExportProfilesCompleted(ctx context.Context, data DataExportProfilesCompletedPayload) {
	EmitAndLog(ctx, EventDataExportProfilesCompleted, toMap(data))
}

// EmitDataExportProfilesStarted emits a "data:export:profiles-started" event.
// 实例数据导出已开始
func EmitDataExportProfilesStarted(ctx context.Context, data DataExportProfilesStartedPayload) {
	EmitAndLog(ctx, EventDataExportProfilesStarted, toMap(data))
}

// EmitDataExportProxiesCompleted emits a "data:export:proxies-completed" event.
// 代理数据导出已完成
func EmitDataExportProxiesCompleted(ctx context.Context, data DataExportProxiesCompletedPayload) {
	EmitAndLog(ctx, EventDataExportProxiesCompleted, toMap(data))
}

// EmitDataExportProxiesStarted emits a "data:export:proxies-started" event.
// 代理数据导出已开始
func EmitDataExportProxiesStarted(ctx context.Context, data DataExportProxiesStartedPayload) {
	EmitAndLog(ctx, EventDataExportProxiesStarted, toMap(data))
}

// EmitDataScrapeCompleted emits a "data:scrape:completed" event.
// 数据采集完成
func EmitDataScrapeCompleted(ctx context.Context, data DataScrapeCompletedPayload) {
	EmitAndLog(ctx, EventDataScrapeCompleted, toMap(data))
}

// EmitDataScrapeExported emits a "data:scrape:exported" event.
// 采集数据已导出
func EmitDataScrapeExported(ctx context.Context, data DataScrapeExportedPayload) {
	EmitAndLog(ctx, EventDataScrapeExported, toMap(data))
}

// EmitDataScrapePageDone emits a "data:scrape:page-done" event.
// 单页数据采集完成
func EmitDataScrapePageDone(ctx context.Context, data DataScrapePageDonePayload) {
	EmitAndLog(ctx, EventDataScrapePageDone, toMap(data))
}

// EmitDataScrapeProgress emits a "data:scrape:progress" event.
// 数据采集进度
func EmitDataScrapeProgress(ctx context.Context, data DataScrapeProgressPayload) {
	EmitAndLog(ctx, EventDataScrapeProgress, toMap(data))
}

// EmitDataScrapeRateLimited emits a "data:scrape:rate-limited" event.
// 数据采集触发限流
func EmitDataScrapeRateLimited(ctx context.Context, data DataScrapeRateLimitedPayload) {
	EmitAndLog(ctx, EventDataScrapeRateLimited, toMap(data))
}

// EmitDataScrapeStarted emits a "data:scrape:started" event.
// 数据采集开始
func EmitDataScrapeStarted(ctx context.Context, data DataScrapeStartedPayload) {
	EmitAndLog(ctx, EventDataScrapeStarted, toMap(data))
}

// EmitDownloadProgress emits a "download:progress" event.
// 内核下载进度
func EmitDownloadProgress(ctx context.Context, data DownloadProgressPayload) {
	EmitAndLog(ctx, EventDownloadProgress, toMap(data))
}

// EmitLicenseActivated emits a "license:activated" event.
// 许可证已激活
func EmitLicenseActivated(ctx context.Context, data LicenseActivatedPayload) {
	EmitAndLog(ctx, EventLicenseActivated, toMap(data))
}

// EmitLicenseCdkeyInvalid emits a "license:cdkey-invalid" event.
// CDKey 无效
func EmitLicenseCdkeyInvalid(ctx context.Context, data LicenseCdkeyInvalidPayload) {
	EmitAndLog(ctx, EventLicenseCdkeyInvalid, toMap(data))
}

// EmitLicenseCdkeyRedeemed emits a "license:cdkey-redeemed" event.
// CDKey 已兑换
func EmitLicenseCdkeyRedeemed(ctx context.Context, data LicenseCdkeyRedeemedPayload) {
	EmitAndLog(ctx, EventLicenseCdkeyRedeemed, toMap(data))
}

// EmitLicenseExpired emits a "license:expired" event.
// 许可证已过期
func EmitLicenseExpired(ctx context.Context) {
	EmitAndLog(ctx, EventLicenseExpired)
}

// EmitLicenseExpiring emits a "license:expiring" event.
// 许可证即将过期
func EmitLicenseExpiring(ctx context.Context, data LicenseExpiringPayload) {
	EmitAndLog(ctx, EventLicenseExpiring, toMap(data))
}

// EmitLicenseRenewed emits a "license:renewed" event.
// 许可证已续期
func EmitLicenseRenewed(ctx context.Context, data LicenseRenewedPayload) {
	EmitAndLog(ctx, EventLicenseRenewed, toMap(data))
}

// EmitProxyBridgeClashStarted emits a "proxy:bridge:clash:started" event.
// Clash 桥接已启动
func EmitProxyBridgeClashStarted(ctx context.Context, data ProxyBridgeClashStartedPayload) {
	EmitAndLog(ctx, EventProxyBridgeClashStarted, toMap(data))
}

// EmitProxyBridgeClashStarting emits a "proxy:bridge:clash:starting" event.
// Clash 桥接正在启动
func EmitProxyBridgeClashStarting(ctx context.Context, data ProxyBridgeClashStartingPayload) {
	EmitAndLog(ctx, EventProxyBridgeClashStarting, toMap(data))
}

// EmitProxyBridgeDied emits a "proxy:bridge:died" event.
// 代理桥接进程死亡
func EmitProxyBridgeDied(ctx context.Context, data ProxyBridgeDiedPayload) {
	EmitAndLog(ctx, EventProxyBridgeDied, toMap(data))
}

// EmitProxyBridgeFailed emits a "proxy:bridge:failed" event.
// 代理桥接启动失败
func EmitProxyBridgeFailed(ctx context.Context, data ProxyBridgeFailedPayload) {
	EmitAndLog(ctx, EventProxyBridgeFailed, toMap(data))
}

// EmitProxyBridgeReconnected emits a "proxy:bridge:reconnected" event.
// 代理桥接重连成功
func EmitProxyBridgeReconnected(ctx context.Context, data ProxyBridgeReconnectedPayload) {
	EmitAndLog(ctx, EventProxyBridgeReconnected, toMap(data))
}

// EmitProxyBridgeReconnecting emits a "proxy:bridge:reconnecting" event.
// 代理桥接正在重连
func EmitProxyBridgeReconnecting(ctx context.Context, data ProxyBridgeReconnectingPayload) {
	EmitAndLog(ctx, EventProxyBridgeReconnecting, toMap(data))
}

// EmitProxyBridgeSingboxStarted emits a "proxy:bridge:singbox:started" event.
// SingBox 桥接已启动
func EmitProxyBridgeSingboxStarted(ctx context.Context, data ProxyBridgeSingboxStartedPayload) {
	EmitAndLog(ctx, EventProxyBridgeSingboxStarted, toMap(data))
}

// EmitProxyBridgeSingboxStarting emits a "proxy:bridge:singbox:starting" event.
// SingBox 桥接正在启动
func EmitProxyBridgeSingboxStarting(ctx context.Context, data ProxyBridgeSingboxStartingPayload) {
	EmitAndLog(ctx, EventProxyBridgeSingboxStarting, toMap(data))
}

// EmitProxyBridgeXrayStarted emits a "proxy:bridge:xray:started" event.
// Xray 桥接已启动
func EmitProxyBridgeXrayStarted(ctx context.Context, data ProxyBridgeXrayStartedPayload) {
	EmitAndLog(ctx, EventProxyBridgeXrayStarted, toMap(data))
}

// EmitProxyBridgeXrayStarting emits a "proxy:bridge:xray:starting" event.
// Xray 桥接正在启动
func EmitProxyBridgeXrayStarting(ctx context.Context, data ProxyBridgeXrayStartingPayload) {
	EmitAndLog(ctx, EventProxyBridgeXrayStarting, toMap(data))
}

// EmitProxyIphealthResult emits a "proxy:iphealth:result" event.
// 代理出口 IP 健康检测结果
func EmitProxyIphealthResult(ctx context.Context, data ProxyIphealthResultPayload) {
	EmitAndLog(ctx, EventProxyIPHealthResult, toMap(data))
}

// EmitProxyQualityBestNode emits a "proxy:quality:best-node" event.
// 最佳节点已更新
func EmitProxyQualityBestNode(ctx context.Context, data ProxyQualityBestNodePayload) {
	EmitAndLog(ctx, EventProxyQualityBestNode, toMap(data))
}

// EmitProxyQualityHealthDrop emits a "proxy:quality:health-drop" event.
// 代理健康评分下降
func EmitProxyQualityHealthDrop(ctx context.Context, data ProxyQualityHealthDropPayload) {
	EmitAndLog(ctx, EventProxyQualityHealthDrop, toMap(data))
}

// EmitProxyQualityLatencySpike emits a "proxy:quality:latency-spike" event.
// 代理延迟突增
func EmitProxyQualityLatencySpike(ctx context.Context, data ProxyQualityLatencySpikePayload) {
	EmitAndLog(ctx, EventProxyQualityLatencySpike, toMap(data))
}

// EmitProxyQualityNodeAdded emits a "proxy:quality:node-added" event.
// 新节点已加入代理池
func EmitProxyQualityNodeAdded(ctx context.Context, data ProxyQualityNodeAddedPayload) {
	EmitAndLog(ctx, EventProxyQualityNodeAdded, toMap(data))
}

// EmitProxyQualityNodeRemoved emits a "proxy:quality:node-removed" event.
// 节点已从代理池移除
func EmitProxyQualityNodeRemoved(ctx context.Context, data ProxyQualityNodeRemovedPayload) {
	EmitAndLog(ctx, EventProxyQualityNodeRemoved, toMap(data))
}

// EmitProxyQualityNodeRotated emits a "proxy:quality:node-rotated" event.
// 代理节点已轮换
func EmitProxyQualityNodeRotated(ctx context.Context, data ProxyQualityNodeRotatedPayload) {
	EmitAndLog(ctx, EventProxyQualityNodeRotated, toMap(data))
}

// EmitProxyQualityPoolExhausted emits a "proxy:quality:pool-exhausted" event.
// 代理池耗尽
func EmitProxyQualityPoolExhausted(ctx context.Context, data ProxyQualityPoolExhaustedPayload) {
	EmitAndLog(ctx, EventProxyQualityPoolExhausted, toMap(data))
}

// EmitProxyQualityScoreChange emits a "proxy:quality:score-change" event.
// 代理综合评分变化
func EmitProxyQualityScoreChange(ctx context.Context, data ProxyQualityScoreChangePayload) {
	EmitAndLog(ctx, EventProxyQualityScoreChange, toMap(data))
}

// EmitProxyRotationCompleted emits a "proxy:rotation:completed" event.
// 代理轮换完成
func EmitProxyRotationCompleted(ctx context.Context, data ProxyRotationCompletedPayload) {
	EmitAndLog(ctx, EventProxyRotationCompleted, toMap(data))
}

// EmitProxyRotationFailed emits a "proxy:rotation:failed" event.
// 代理轮换失败
func EmitProxyRotationFailed(ctx context.Context, data ProxyRotationFailedPayload) {
	EmitAndLog(ctx, EventProxyRotationFailed, toMap(data))
}

// EmitProxyRotationSkipped emits a "proxy:rotation:skipped" event.
// 代理轮换跳过（无可用节点）
func EmitProxyRotationSkipped(ctx context.Context, data ProxyRotationSkippedPayload) {
	EmitAndLog(ctx, EventProxyRotationSkipped, toMap(data))
}

// EmitProxyRotationTriggered emits a "proxy:rotation:triggered" event.
// 代理轮换已触发
func EmitProxyRotationTriggered(ctx context.Context, data ProxyRotationTriggeredPayload) {
	EmitAndLog(ctx, EventProxyRotationTriggered, toMap(data))
}

// EmitProxySpeedResult emits a "proxy:speed:result" event.
// 代理测速结果
func EmitProxySpeedResult(ctx context.Context, data ProxySpeedResultPayload) {
	EmitAndLog(ctx, EventProxySpeedResult, toMap(data))
}

// EmitRiskBrowserCrashLoop emits a "risk:browser:crash-loop" event.
// 同一实例 5 分钟内崩溃 3+ 次
func EmitRiskBrowserCrashLoop(ctx context.Context, data RiskBrowserCrashLoopPayload) {
	EmitAndLog(ctx, EventRiskBrowserCrashLoop, toMap(data))
}

// EmitRiskCaptchaDetected emits a "risk:captcha:detected" event.
// 浏览器出现验证码
func EmitRiskCaptchaDetected(ctx context.Context, data RiskCaptchaDetectedPayload) {
	EmitAndLog(ctx, EventRiskCaptchaDetected, toMap(data))
}

// EmitRiskCaptchaFailed emits a "risk:captcha:failed" event.
// 验证码解决失败
func EmitRiskCaptchaFailed(ctx context.Context, data RiskCaptchaFailedPayload) {
	EmitAndLog(ctx, EventRiskCaptchaFailed, toMap(data))
}

// EmitRiskDnsLeak emits a "risk:dns:leak" event.
// DNS 解析绕过了代理
func EmitRiskDnsLeak(ctx context.Context, data RiskDnsLeakPayload) {
	EmitAndLog(ctx, EventRiskDNSLeak, toMap(data))
}

// EmitRiskFingerprintMismatch emits a "risk:fingerprint:mismatch" event.
// CDP 指纹验证发现偏差
func EmitRiskFingerprintMismatch(ctx context.Context, data RiskFingerprintMismatchPayload) {
	EmitAndLog(ctx, EventRiskFingerprintMismatch, toMap(data))
}

// EmitRiskFingerprintTimezoneIp emits a "risk:fingerprint:timezone-ip" event.
// 浏览器时区与代理 IP 地理位置不匹配
func EmitRiskFingerprintTimezoneIp(ctx context.Context, data RiskFingerprintTimezoneIpPayload) {
	EmitAndLog(ctx, EventRiskFingerprintTimezoneIP, toMap(data))
}

// EmitRiskNodeBanned emits a "risk:node:banned" event.
// 代理节点被封
func EmitRiskNodeBanned(ctx context.Context, data RiskNodeBannedPayload) {
	EmitAndLog(ctx, EventRiskNodeBanned, toMap(data))
}

// EmitRiskNodeGeoJump emits a "risk:node:geo-jump" event.
// 节点出口 IP 跳变
func EmitRiskNodeGeoJump(ctx context.Context, data RiskNodeGeoJumpPayload) {
	EmitAndLog(ctx, EventRiskNodeGeoJump, toMap(data))
}

// EmitRiskNodeOffline emits a "risk:node:offline" event.
// 代理节点不可达
func EmitRiskNodeOffline(ctx context.Context, data RiskNodeOfflinePayload) {
	EmitAndLog(ctx, EventRiskNodeOffline, toMap(data))
}

// EmitRiskProfileCorrupted emits a "risk:profile:corrupted" event.
// Profile 目录损坏
func EmitRiskProfileCorrupted(ctx context.Context, data RiskProfileCorruptedPayload) {
	EmitAndLog(ctx, EventRiskProfileCorrupted, toMap(data))
}

// EmitRiskProxyAuthFailure emits a "risk:proxy:auth-failure" event.
// 代理认证被拒
func EmitRiskProxyAuthFailure(ctx context.Context, data RiskProxyAuthFailurePayload) {
	EmitAndLog(ctx, EventRiskProxyAuthFailure, toMap(data))
}

// EmitRiskProxyDatacenter emits a "risk:proxy:datacenter" event.
// 代理 IP 被识别为机房/托管
func EmitRiskProxyDatacenter(ctx context.Context, data RiskProxyDatacenterPayload) {
	EmitAndLog(ctx, EventRiskProxyDatacenter, toMap(data))
}

// EmitRiskProxyHealthDrop emits a "risk:proxy:health-drop" event.
// 代理 IP 欺诈分骤升（>=70）
func EmitRiskProxyHealthDrop(ctx context.Context, data RiskProxyHealthDropPayload) {
	EmitAndLog(ctx, EventRiskProxyHealthDrop, toMap(data))
}

// EmitRiskProxyHighLatency emits a "risk:proxy:high-latency" event.
// 代理延迟超过 3000ms
func EmitRiskProxyHighLatency(ctx context.Context, data RiskProxyHighLatencyPayload) {
	EmitAndLog(ctx, EventRiskProxyHighLatency, toMap(data))
}

// EmitRiskSessionCookieCleared emits a "risk:session:cookie-cleared" event.
// 会话 Cookie 意外清除
func EmitRiskSessionCookieCleared(ctx context.Context, data RiskSessionCookieClearedPayload) {
	EmitAndLog(ctx, EventRiskSessionCookieCleared, toMap(data))
}

// EmitRiskSessionRateLimit emits a "risk:session:rate-limit" event.
// 小红书返回限流响应
func EmitRiskSessionRateLimit(ctx context.Context, data RiskSessionRateLimitPayload) {
	EmitAndLog(ctx, EventRiskSessionRateLimit, toMap(data))
}

// EmitRiskSessionSecurityChallenge emits a "risk:session:security-challenge" event.
// 小红书触发安全验证
func EmitRiskSessionSecurityChallenge(ctx context.Context, data RiskSessionSecurityChallengePayload) {
	EmitAndLog(ctx, EventRiskSessionSecurityChallenge, toMap(data))
}

// EmitRiskSystemLowDisk emits a "risk:system:low-disk" event.
// 磁盘空间不足 5%
func EmitRiskSystemLowDisk(ctx context.Context, data RiskSystemLowDiskPayload) {
	EmitAndLog(ctx, EventRiskSystemLowDisk, toMap(data))
}

// EmitRiskSystemMemoryPressure emits a "risk:system:memory-pressure" event.
// 内存使用超过 80%
func EmitRiskSystemMemoryPressure(ctx context.Context, data RiskSystemMemoryPressurePayload) {
	EmitAndLog(ctx, EventRiskSystemMemoryPressure, toMap(data))
}

// EmitRiskWebrtcLeak emits a "risk:webrtc:leak" event.
// WebRTC 泄露了真实 IP
func EmitRiskWebrtcLeak(ctx context.Context, data RiskWebrtcLeakPayload) {
	EmitAndLog(ctx, EventRiskWebRTCLeak, toMap(data))
}

// EmitSettingsChangeAppConfig emits a "settings:change:app-config" event.
// 应用配置已变更
func EmitSettingsChangeAppConfig(ctx context.Context, data SettingsChangeAppConfigPayload) {
	EmitAndLog(ctx, EventSettingsChangeAppConfig, toMap(data))
}

// EmitSettingsChangeBackupScope emits a "settings:change:backup-scope" event.
// 备份范围配置已变更
func EmitSettingsChangeBackupScope(ctx context.Context) {
	EmitAndLog(ctx, EventSettingsChangeBackupScope)
}

// EmitSettingsChangeBookmark emits a "settings:change:bookmark" event.
// 书签配置已变更
func EmitSettingsChangeBookmark(ctx context.Context, data SettingsChangeBookmarkPayload) {
	EmitAndLog(ctx, EventSettingsChangeBookmark, toMap(data))
}

// EmitSettingsChangeBrowserCore emits a "settings:change:browser-core" event.
// 浏览器内核配置已变更
func EmitSettingsChangeBrowserCore(ctx context.Context, data SettingsChangeBrowserCorePayload) {
	EmitAndLog(ctx, EventSettingsChangeBrowserCore, toMap(data))
}

// EmitSettingsChangeBrowserProxy emits a "settings:change:browser-proxy" event.
// 浏览器代理配置已变更
func EmitSettingsChangeBrowserProxy(ctx context.Context, data SettingsChangeBrowserProxyPayload) {
	EmitAndLog(ctx, EventSettingsChangeBrowserProxy, toMap(data))
}

// EmitSettingsChangeGroupSort emits a "settings:change:group-sort" event.
// 分组排序已变更
func EmitSettingsChangeGroupSort(ctx context.Context) {
	EmitAndLog(ctx, EventSettingsChangeGroupSort)
}

// EmitSettingsChangeInterceptor emits a "settings:change:interceptor" event.
// 请求拦截器配置已变更
func EmitSettingsChangeInterceptor(ctx context.Context, data SettingsChangeInterceptorPayload) {
	EmitAndLog(ctx, EventSettingsChangeInterceptor, toMap(data))
}

// EmitSettingsChangeLaunchDefaults emits a "settings:change:launch-defaults" event.
// 默认启动参数已变更
func EmitSettingsChangeLaunchDefaults(ctx context.Context) {
	EmitAndLog(ctx, EventSettingsChangeLaunchDefaults)
}

// EmitSettingsChangeLaunchServer emits a "settings:change:launch-server" event.
// Launch Server 配置已变更
func EmitSettingsChangeLaunchServer(ctx context.Context, data SettingsChangeLaunchServerPayload) {
	EmitAndLog(ctx, EventSettingsChangeLaunchServer, toMap(data))
}

// EmitSettingsChangeLogLevel emits a "settings:change:log-level" event.
// 日志等级已变更
func EmitSettingsChangeLogLevel(ctx context.Context, data SettingsChangeLogLevelPayload) {
	EmitAndLog(ctx, EventSettingsChangeLogLevel, toMap(data))
}

// EmitSettingsChangeProfileDefaults emits a "settings:change:profile-defaults" event.
// 默认实例配置已变更
func EmitSettingsChangeProfileDefaults(ctx context.Context) {
	EmitAndLog(ctx, EventSettingsChangeProfileDefaults)
}

// EmitSettingsChangeRuntimeConfig emits a "settings:change:runtime-config" event.
// 运行时配置已变更
func EmitSettingsChangeRuntimeConfig(ctx context.Context) {
	EmitAndLog(ctx, EventSettingsChangeRuntimeConfig)
}

// EmitSystemHealthConfigReload emits a "system:health:config-reload" event.
// 配置已重载
func EmitSystemHealthConfigReload(ctx context.Context) {
	EmitAndLog(ctx, EventSystemHealthConfigReload)
}

// EmitSystemHealthCpuHigh emits a "system:health:cpu-high" event.
// CPU 使用率过高
func EmitSystemHealthCpuHigh(ctx context.Context, data SystemHealthCpuHighPayload) {
	EmitAndLog(ctx, EventSystemHealthCpuHigh, toMap(data))
}

// EmitSystemHealthCpuNormal emits a "system:health:cpu-normal" event.
// CPU 使用率恢复正常
func EmitSystemHealthCpuNormal(ctx context.Context) {
	EmitAndLog(ctx, EventSystemHealthCpuNormal)
}

// EmitSystemHealthDbSize emits a "system:health:db-size" event.
// 数据库大小告警
func EmitSystemHealthDbSize(ctx context.Context, data SystemHealthDbSizePayload) {
	EmitAndLog(ctx, EventSystemHealthDbSize, toMap(data))
}

// EmitSystemHealthDbVacuum emits a "system:health:db-vacuum" event.
// 数据库已执行 VACUUM
func EmitSystemHealthDbVacuum(ctx context.Context, data SystemHealthDbVacuumPayload) {
	EmitAndLog(ctx, EventSystemHealthDbVacuum, toMap(data))
}

// EmitSystemHealthDiskCritical emits a "system:health:disk-critical" event.
// 磁盘空间严重不足
func EmitSystemHealthDiskCritical(ctx context.Context, data SystemHealthDiskCriticalPayload) {
	EmitAndLog(ctx, EventSystemHealthDiskCritical, toMap(data))
}

// EmitSystemHealthDiskLow emits a "system:health:disk-low" event.
// 磁盘空间不足
func EmitSystemHealthDiskLow(ctx context.Context, data SystemHealthDiskLowPayload) {
	EmitAndLog(ctx, EventSystemHealthDiskLow, toMap(data))
}

// EmitSystemHealthGcTriggered emits a "system:health:gc-triggered" event.
// 手动触发 GC
func EmitSystemHealthGcTriggered(ctx context.Context, data SystemHealthGcTriggeredPayload) {
	EmitAndLog(ctx, EventSystemHealthGcTriggered, toMap(data))
}

// EmitSystemHealthGoroutineCount emits a "system:health:goroutine-count" event.
// 协程数量告警
func EmitSystemHealthGoroutineCount(ctx context.Context, data SystemHealthGoroutineCountPayload) {
	EmitAndLog(ctx, EventSystemHealthGoroutineCount, toMap(data))
}

// EmitSystemHealthMemoryCritical emits a "system:health:memory-critical" event.
// 系统内存严重不足
func EmitSystemHealthMemoryCritical(ctx context.Context, data SystemHealthMemoryCriticalPayload) {
	EmitAndLog(ctx, EventSystemHealthMemoryCritical, toMap(data))
}

// EmitSystemHealthMemoryHigh emits a "system:health:memory-high" event.
// 系统内存占用过高
func EmitSystemHealthMemoryHigh(ctx context.Context, data SystemHealthMemoryHighPayload) {
	EmitAndLog(ctx, EventSystemHealthMemoryHigh, toMap(data))
}

// EmitSystemHealthMemoryNormal emits a "system:health:memory-normal" event.
// 系统内存恢复正常
func EmitSystemHealthMemoryNormal(ctx context.Context, data SystemHealthMemoryNormalPayload) {
	EmitAndLog(ctx, EventSystemHealthMemoryNormal, toMap(data))
}

// EmitSystemHealthPanicRecovered emits a "system:health:panic-recovered" event.
// 已从 panic 中恢复
func EmitSystemHealthPanicRecovered(ctx context.Context, data SystemHealthPanicRecoveredPayload) {
	EmitAndLog(ctx, EventSystemHealthPanicRecovered, toMap(data))
}

// EmitSystemHealthProcessCount emits a "system:health:process-count" event.
// 浏览器进程数量告警
func EmitSystemHealthProcessCount(ctx context.Context, data SystemHealthProcessCountPayload) {
	EmitAndLog(ctx, EventSystemHealthProcessCount, toMap(data))
}

// EmitSystemHealthShutdownInitiated emits a "system:health:shutdown-initiated" event.
// 系统正在关闭
func EmitSystemHealthShutdownInitiated(ctx context.Context, data SystemHealthShutdownInitiatedPayload) {
	EmitAndLog(ctx, EventSystemHealthShutdownInitiated, toMap(data))
}

// EmitSystemHealthStartupComplete emits a "system:health:startup-complete" event.
// 系统启动完成
func EmitSystemHealthStartupComplete(ctx context.Context, data SystemHealthStartupCompletePayload) {
	EmitAndLog(ctx, EventSystemHealthStartupComplete, toMap(data))
}

// EmitSystemRecoveryAutoRestart emits a "system:recovery:auto-restart" event.
// 自动重启实例
func EmitSystemRecoveryAutoRestart(ctx context.Context, data SystemRecoveryAutoRestartPayload) {
	EmitAndLog(ctx, EventSystemRecoveryAutoRestart, toMap(data))
}

// EmitSystemRecoveryAutoStop emits a "system:recovery:auto-stop" event.
// 自动停止异常实例
func EmitSystemRecoveryAutoStop(ctx context.Context, data SystemRecoveryAutoStopPayload) {
	EmitAndLog(ctx, EventSystemRecoveryAutoStop, toMap(data))
}

// EmitSystemRecoveryCrashLoopDetected emits a "system:recovery:crash-loop-detected" event.
// 检测到崩溃循环
func EmitSystemRecoveryCrashLoopDetected(ctx context.Context, data SystemRecoveryCrashLoopDetectedPayload) {
	EmitAndLog(ctx, EventSystemRecoveryCrashLoopDetected, toMap(data))
}

// EmitSystemRecoveryDbRecovered emits a "system:recovery:db-recovered" event.
// 数据库已从备份恢复
func EmitSystemRecoveryDbRecovered(ctx context.Context) {
	EmitAndLog(ctx, EventSystemRecoveryDbRecovered)
}

// EmitSystemRecoveryLockfileCleaned emits a "system:recovery:lockfile-cleaned" event.
// 已清理残留锁文件
func EmitSystemRecoveryLockfileCleaned(ctx context.Context, data SystemRecoveryLockfileCleanedPayload) {
	EmitAndLog(ctx, EventSystemRecoveryLockfileCleaned, toMap(data))
}

// EmitSystemRecoveryOrphanCleanup emits a "system:recovery:orphan-cleanup" event.
// 清理孤儿进程
func EmitSystemRecoveryOrphanCleanup(ctx context.Context, data SystemRecoveryOrphanCleanupPayload) {
	EmitAndLog(ctx, EventSystemRecoveryOrphanCleanup, toMap(data))
}

// EmitSystemRecoveryPortReleased emits a "system:recovery:port-released" event.
// 已释放占用的端口
func EmitSystemRecoveryPortReleased(ctx context.Context, data SystemRecoveryPortReleasedPayload) {
	EmitAndLog(ctx, EventSystemRecoveryPortReleased, toMap(data))
}

// EmitSystemRecoveryProfileRepaired emits a "system:recovery:profile-repaired" event.
// 实例配置已修复
func EmitSystemRecoveryProfileRepaired(ctx context.Context, data SystemRecoveryProfileRepairedPayload) {
	EmitAndLog(ctx, EventSystemRecoveryProfileRepaired, toMap(data))
}

