package events

import "strings"

func init() {
	registerIdentityCatalog(identityCatalogEvents())
}

func registerIdentityCatalog(names []string) {
	for _, name := range names {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if _, exists := Registry[name]; exists {
			continue
		}
		Registry[name] = EventDef{
			Name:        name,
			Namespace:   catalogNamespace(name),
			Description: "Identity observability event: " + name,
			Payload: []EventField{
				{Name: "profileId", Type: "string", Required: false},
				{Name: "profileName", Type: "string", Required: false},
				{Name: "reportId", Type: "string", Required: false},
				{Name: "dimensionId", Type: "string", Required: false},
				{Name: "status", Type: "string", Required: false},
				{Name: "score", Type: "int", Required: false},
				{Name: "message", Type: "string", Required: false},
			},
			Severity: catalogSeverity(name),
		}
	}
}

func catalogNamespace(name string) string {
	if idx := strings.Index(name, ":"); idx > 0 {
		return name[:idx]
	}
	return "app"
}

func catalogSeverity(name string) string {
	lower := strings.ToLower(name)
	switch {
	case strings.Contains(lower, "failed"),
		strings.Contains(lower, "rejected"),
		strings.Contains(lower, "mismatch"),
		strings.Contains(lower, "exposed"),
		strings.Contains(lower, "cleared"),
		strings.Contains(lower, "corrupted"):
		return "error"
	case strings.Contains(lower, "warning"),
		strings.Contains(lower, "blocked"),
		strings.Contains(lower, "missing"),
		strings.Contains(lower, "low-confidence"),
		strings.Contains(lower, "unavailable"),
		strings.Contains(lower, "degraded"):
		return "warn"
	default:
		return "info"
	}
}

func identityCatalogEvents() []string {
	return []string{
		"identity:report:started",
		"identity:report:completed",
		"identity:report:failed",
		"identity:report:history-saved",
		"identity:report:history-pruned",
		"identity:score:changed",
		"identity:score:threshold-crossed",
		"identity:capsule:created",
		"identity:capsule:updated",
		"identity:capsule:copied",
		"identity:capsule:imported",
		"identity:capsule:exported",
		"identity:capsule:locked",
		"identity:capsule:unlocked",
		"identity:capsule:write-blocked",
		"identity:dimension:pass",
		"identity:dimension:warning",
		"identity:dimension:fail",
		"identity:subscore:changed",
		"identity:audit:hash-matched",
		"identity:audit:hash-mismatched",
		"identity:audit:missing",
		"identity:guard:pass",
		"identity:guard:warning",
		"identity:guard:fail",
		"identity:consistency:pass",
		"identity:consistency:warning",
		"identity:consistency:fail",
		"identity:profile:bound",
		"identity:profile:unbound",
		"identity:seed:bound",
		"identity:seed:rotation-blocked",
		"identity:summary:updated",
		"identity:risk:created",
		"identity:risk:resolved",
		"identity:risk:acknowledged",
		"identity:baseline:created",
		"identity:baseline:matched",
		"identity:baseline:drifted",
		"identity:baseline:reset-requested",

		"fingerprint:cdp:capture-started",
		"fingerprint:cdp:capture-completed",
		"fingerprint:cdp:capture-failed",
		"fingerprint:dimension:captured",
		"fingerprint:dimension:missing",
		"fingerprint:dimension:mismatch",
		"fingerprint:user-agent:captured",
		"fingerprint:user-agent:mismatch",
		"fingerprint:app-version:captured",
		"fingerprint:platform:captured",
		"fingerprint:platform:mismatch",
		"fingerprint:language:captured",
		"fingerprint:language:mismatch",
		"fingerprint:timezone:captured",
		"fingerprint:timezone:mismatch",
		"fingerprint:screen:captured",
		"fingerprint:screen:mismatch",
		"fingerprint:viewport:captured",
		"fingerprint:viewport:mismatch",
		"fingerprint:hardware:captured",
		"fingerprint:hardware:mismatch",
		"fingerprint:canvas:captured",
		"fingerprint:canvas:error",
		"fingerprint:canvas:vanilla-detected",
		"fingerprint:webgl:captured",
		"fingerprint:webgl:empty",
		"fingerprint:webgl:extensions-captured",
		"fingerprint:webgl:limits-captured",
		"fingerprint:audio:captured",
		"fingerprint:audio:error",
		"fingerprint:audio:unsupported",
		"fingerprint:fonts:captured",
		"fingerprint:fonts:error",
		"fingerprint:client-hints:captured",
		"fingerprint:client-hints:unavailable",
		"fingerprint:client-hints:mismatch",
		"fingerprint:webdriver:exposed",
		"fingerprint:webdriver:hidden",
		"fingerprint:storage:captured",
		"fingerprint:storage:unavailable",
		"fingerprint:media-query:captured",
		"fingerprint:plugins:captured",
		"fingerprint:mime-types:captured",
		"fingerprint:webgpu:available",
		"fingerprint:webgpu:unavailable",
		"fingerprint:webrtc-api:supported",
		"fingerprint:intl:captured",
		"fingerprint:date-format:captured",
		"fingerprint:number-format:captured",
		"fingerprint:network-info:captured",
		"fingerprint:network-info:unavailable",
		"fingerprint:do-not-track:captured",
		"fingerprint:pdf-viewer:captured",
		"fingerprint:touch:captured",
		"fingerprint:pointer:captured",
		"fingerprint:hover:captured",
		"fingerprint:color-scheme:captured",
		"fingerprint:reduced-motion:captured",

		"profile:guard:path-normalized",
		"profile:guard:path-rejected",
		"profile:guard:duplicate-user-data-dir",
		"profile:guard:symlink-rejected",
		"profile:guard:start-lock-conflict",
		"profile:user-data-dir:bound",
		"profile:user-data-dir:changed-blocked",
		"profile:create:started",
		"profile:create:completed",
		"profile:update:started",
		"profile:update:completed",
		"profile:delete:started",
		"profile:delete:completed",
		"profile:copy:started",
		"profile:copy:completed",
		"profile:export:started",
		"profile:export:completed",
		"profile:import:started",
		"profile:import:completed",
		"profile:path:confirmation-required",
		"profile:opened",
		"profile:closed",
		"profile:launch-audit:created",
		"profile:launch-audit:validated",
		"profile:launch-audit:rejected",
		"profile:core:bound",
		"profile:core:missing",
		"profile:humanize-seed:created",
		"profile:humanize-seed:preserved",
		"profile:humanize-seed:empty-repaired",
		"profile:preference:merged",
		"profile:tag:updated",
		"profile:group:moved",
		"profile:runtime-warning:set",
		"profile:runtime-warning:cleared",
		"profile:snapshot:preflight",
		"profile:snapshot:restored",

		"cookie:backup:started",
		"cookie:backup:completed",
		"cookie:backup:failed",
		"cookie:restore:started",
		"cookie:restore:completed",
		"cookie:restore:failed",
		"cookie:integrity:checked",
		"cookie:integrity:changed",
		"cookie:integrity:matched",
		"cookie:db:locked",
		"cookie:db:unlocked",
		"cookie:db:corrupted",
		"cookie:unexpected-cleared",
		"cookie:count:changed",
		"cookie:domain:exported",
		"cookie:domain:imported",
		"cookie:import:conflict",
		"cookie:encrypted-store:unavailable",
		"cookie:sqlite-wal:detected",
		"cookie:same-site:summary",
		"cookie:session-cookie:summary",
		"cookie:persistent-cookie:summary",
		"cookie:write:blocked",
		"cookie:read:completed",
		"cookie:value:redacted",
		"cookie:backup:manifest-written",
		"cookie:restore:manifest-read",
		"cookie:profile-binding:validated",
		"cookie:profile-binding:rejected",
		"cookie:retention:policy-applied",
		"cookie:retention:policy-skipped",

		"behavior:recording:started",
		"behavior:recording:stopped",
		"behavior:recording:saved",
		"behavior:recording:deleted",
		"behavior:recording:imported",
		"behavior:recording:exported",
		"behavior:recording:sensitive-redacted",
		"behavior:recording:event-page-loaded",
		"behavior:playback:started",
		"behavior:playback:progress",
		"behavior:playback:completed",
		"behavior:playback:failed",
		"behavior:playback:needs-review",
		"behavior:playback:decision-continue",
		"behavior:playback:decision-skip",
		"behavior:playback:decision-stop",
		"behavior:target:low-confidence",
		"behavior:target:resolved",
		"behavior:click:offset-applied",
		"behavior:move:degraded",
		"behavior:click:strict-failed",
		"behavior:cadence:human",
		"behavior:cadence:mixed",
		"behavior:cadence:bot-like",
		"behavior:human-boundary:detected",
		"behavior:takeover:requested",
		"behavior:template:created",
		"behavior:template:updated",
		"behavior:template:validated",
		"behavior:template:rejected",
		"behavior:permission-mode:changed",
		"behavior:typing-plan:generated",
		"behavior:scroll-plan:generated",
		"behavior:review:prompt-hidden-evidence",
		"behavior:review:timeout",
		"behavior:review:resumed",

		"workbench:identity-report:queued",
		"workbench:identity-report:started",
		"workbench:identity-report:completed",
		"workbench:identity-report:failed",
		"workbench:fingerprint-health:queued",
		"workbench:fingerprint-health:completed",
		"workbench:preview:captured",
		"workbench:preview:failed",
		"workbench:window:activate-requested",
		"workbench:window:activated",
		"workbench:window:arrange-requested",
		"workbench:window:arrange-completed",
		"workbench:task:queued",
		"workbench:task:started",
		"workbench:task:completed",
		"workbench:task:failed",
		"workbench:refresh:silent",
		"workbench:status:poll-started",
		"workbench:status:poll-completed",
		"workbench:status:stale-result-ignored",
		"workbench:selection:changed",
		"workbench:batch:started",
		"workbench:batch:completed",
		"workbench:batch:failed",

		"network:webrtc:api-supported",
		"network:webrtc:api-unavailable",
		"network:dns:check-started",
		"network:dns:check-completed",
		"network:dns:check-failed",
		"network:exit-ip:check-started",
		"network:exit-ip:check-completed",
		"network:exit-ip:changed",
		"network:geo:matched",
		"network:geo:mismatch",
		"network:latency:sampled",
		"network:proxy:sticky-session-bound",
		"network:proxy:sticky-session-expired",
		"network:proxy:rotation-blocked",
		"network:proxy:rotation-allowed",
		"network:proxy:auth-failed",
		"network:proxy:health-warning",
		"network:proxy:health-recovered",
		"network:proxy:datacenter-detected",
		"network:proxy:residential-detected",

		"automation:permission:ask-each-time",
		"automation:permission:auto-review",
		"automation:permission:full-access",
		"automation:guard:captcha-detected",
		"automation:guard:two-factor-detected",
		"automation:guard:password-detected",
		"automation:guard:delete-detected",
		"automation:guard:account-settings-detected",
		"automation:guard:switch-account-detected",
		"automation:guard:manual-required",
		"automation:target:confidence-high",
		"automation:target:confidence-medium",
		"automation:target:confidence-low",
		"automation:target:hit-test-pass",
		"automation:target:hit-test-fail",
		"automation:task:identity-risk-blocked",
		"automation:task:profile-lock-blocked",
		"automation:task:cookie-risk-blocked",
		"automation:task:proxy-risk-blocked",
		"automation:task:behavior-risk-blocked",
	}
}
