import type { SyncGroup, SyncOperation, LayoutPreset } from './types'

// Wails backend function bindings (auto-generated by wails build/dev).
// These are called via the global wails runtime.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const wailsCall = <T>(name: string, ...args: unknown[]): Promise<T> => {
  const w = window as unknown as Record<string, unknown>
  const go = w['go'] as Record<string, Record<string, (...a: unknown[]) => Promise<unknown>>> | undefined
  if (!go?.main?.App) {
    return Promise.reject(new Error('Wails runtime not available'))
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const fn = (go.main.App as any)[name]
  if (typeof fn !== 'function') {
    return Promise.reject(new Error(`Backend function ${name} not found`))
  }
  return fn(...args) as Promise<T>
}

export async function listSyncGroups(): Promise<SyncGroup[]> {
  return wailsCall<SyncGroup[]>('SynchronizerListGroups')
}

export async function getSyncGroup(id: string): Promise<SyncGroup> {
  return wailsCall<SyncGroup>('SynchronizerGetGroup', id)
}

export async function arrangeWindows(
  groupId: string,
  layout: LayoutPreset,
): Promise<void> {
  return wailsCall('SynchronizerArrange', groupId, layout)
}

export async function broadcastNavigate(groupId: string, url: string): Promise<void> {
  return wailsCall('SynchronizerBroadcastNavigate', groupId, url)
}

export async function broadcastScroll(groupId: string, deltaY: number): Promise<void> {
  return wailsCall('SynchronizerBroadcastScroll', groupId, deltaY)
}

export async function broadcastRefresh(groupId: string): Promise<void> {
  return wailsCall('SynchronizerBroadcastRefresh', groupId)
}

export async function focusWindow(windowId: string): Promise<void> {
  return wailsCall('SynchronizerFocusWindow', windowId)
}

export async function closeSyncWindow(windowId: string): Promise<void> {
  return wailsCall('SynchronizerCloseWindow', windowId)
}

export async function getSyncOperationLog(
  limit?: number,
): Promise<SyncOperation[]> {
  return wailsCall<SyncOperation[]>('SynchronizerGetOperationLog', limit ?? 50)
}

// Mock data for development when Wails backend isn't ready
export function getMockGroups(): SyncGroup[] {
  return [
    {
      id: 'group-1',
      name: '北美电商',
      layout: 'grid',
      createdAt: new Date().toISOString(),
      windows: [
        {
          id: 'win-1', profileId: 'p-1', profileName: 'buyer-001',
          title: 'Amazon - 订单页', url: 'https://amazon.com/orders',
          debugPort: 9222, isMain: true,
          position: { x: 0, y: 0 }, size: { width: 960, height: 600 },
          status: 'running', lastActiveAt: new Date().toISOString(), groupId: 'group-1',
        },
        {
          id: 'win-2', profileId: 'p-2', profileName: 'buyer-002',
          title: 'eBay - 搜索', url: 'https://ebay.com/sch',
          debugPort: 9223, isMain: false,
          position: { x: 970, y: 0 }, size: { width: 960, height: 600 },
          status: 'running', lastActiveAt: new Date().toISOString(), groupId: 'group-1',
        },
        {
          id: 'win-3', profileId: 'p-3', profileName: 'buyer-003',
          title: 'Walmart - 主页', url: 'https://walmart.com',
          debugPort: 9224, isMain: false,
          position: { x: 0, y: 610 }, size: { width: 960, height: 600 },
          status: 'idle', lastActiveAt: new Date().toISOString(), groupId: 'group-1',
        },
        {
          id: 'win-4', profileId: 'p-4', profileName: 'buyer-004',
          title: 'Target - 商品详情', url: 'https://target.com/p/item',
          debugPort: 9225, isMain: false,
          position: { x: 970, y: 610 }, size: { width: 960, height: 600 },
          status: 'running', lastActiveAt: new Date().toISOString(), groupId: 'group-1',
        },
      ],
    },
    {
      id: 'group-2',
      name: '社交媒体',
      layout: 'row',
      createdAt: new Date().toISOString(),
      windows: [
        {
          id: 'win-5', profileId: 'p-5', profileName: 'social-001',
          title: '小红书 - 推荐', url: 'https://xiaohongshu.com/explore',
          debugPort: 9230, isMain: true,
          position: { x: 0, y: 0 }, size: { width: 640, height: 480 },
          status: 'running', lastActiveAt: new Date().toISOString(), groupId: 'group-2',
        },
        {
          id: 'win-6', profileId: 'p-6', profileName: 'social-002',
          title: '小红书 - 消息', url: 'https://xiaohongshu.com/messages',
          debugPort: 9231, isMain: false,
          position: { x: 650, y: 0 }, size: { width: 640, height: 480 },
          status: 'running', lastActiveAt: new Date().toISOString(), groupId: 'group-2',
        },
      ],
    },
  ]
}
