/**
 * Dashboard 契约类型定义。
 * 这里集中声明 gateway dashboard 前端使用的关键返回结构，便于原生 JS 也保持可维护性。
 */
export {};

/** @typedef {{ token_label:string, path:string, model:(string|null), upstream_target:(string|null), status_code:number }} GatewayStatsRecentEvent */
/** @typedef {{ total_events:number, by_token:Record<string, number>, by_status:Record<string, number>, by_model:Record<string, number>, recent:GatewayStatsRecentEvent[] }} GatewayStatsSnapshot */
/** @typedef {{ id:string, name:string, version:number, status:string }} NamedResourceOption */
/** @typedef {{ id:string, provider:(string|null), region:(string|null), status:string, score:number }} ProxyOption */
/** @typedef {{ id:string, version:number, site_key:string, behavior_profile_id:string, status:string, page_archetype:(string|null), action_kind:(string|null), has_form_contract:boolean }} SitePolicyOption */
/** @typedef {{ id:string, kind:string, task_kind_display:string, status:string, form_action_status:(string|null), retry_count:(number|null), started_at:(string|null), finished_at:(string|null), site_key:(string|null), title:(string|null), final_url:(string|null), summary_raw:string, summary_zh:string, summary_compact_zh:string, summary_kind:string }} DashboardTaskListItem */
/** @typedef {{ event_type:string, severity:string, task_id:(string|null), site_key:(string|null), occurred_at:(string|null), detail_short:string }} DashboardContinuityEvent */
/** @typedef {{ draft_id:string, site_key:string, login_url:string, status:string, site_policy_id:(string|null), site_policy_version:(number|null), site_contract_present:boolean, shadow_task_id:(string|null), active_success_task_id:(string|null), active_failure_task_id:(string|null), continuity_task_id:(string|null), form_action_status:(string|null), retry_count:(number|null), failure_signal:(string|null), success_ready_selector_seen:boolean, post_login_actions_executed:boolean, session_persisted:boolean, summary_raw:string, summary_zh:string, summary_compact_zh:string, summary_kind:string }} DashboardSiteValidationRollup */
/** @typedef {{ source_label:string, source_kind:string, enabled:boolean, health_score:number, candidate_count:number, active_count:number, candidate_rejected_count:number, null_provider_count:number, null_region_count:number, promotion_rate:number }} ProxyHarvestSourceSummary */
/** @typedef {{ auth_runs:number, auth_success_runs:number, auth_failed_runs:number, auth_blocked_missing_contract:number, auth_transient_retries:number, auth_inline_secret_unavailable:number }} AuthMetrics */
/** @typedef {{ active_sessions:number, reused_sessions:number, created_sessions:number, cookie_restore_count:number, cookie_persist_count:number, local_storage_restore_count:number, local_storage_persist_count:number, session_storage_restore_count:number, session_storage_persist_count:number }} IdentitySessionMetrics */
/** @typedef {{ total:number, queued:number, running:number, succeeded:number, failed:number, timed_out:number, cancelled:number }} TaskStatusCounts */
/** @typedef {{ worker_count:number, queue_mode:string, reclaim_after_seconds:(number|null), heartbeat_interval_seconds:number, claim_retry_limit:number, idle_backoff_min_ms:number, idle_backoff_max_ms:number, fingerprint_medium_max_concurrency:number, fingerprint_heavy_max_concurrency:number }} WorkerStatus */
/** @typedef {{ verified_ok:number, verified_failed:number, geo_match_ok:number, stale_or_missing_verify:number }} VerifyMetrics */
/** @typedef {{ total:number, active:number, candidate:number, candidate_rejected:number, active_ratio_percent:number, hot_regions:string[], region_shortages:string[] }} ProxyPoolStatus */
/** @typedef {{ source_count:number, healthy_source_count:number, due_source_count:number, source_failures:number, source_summaries:ProxyHarvestSourceSummary[] }} ProxyHarvestMetrics */
/** @typedef {{ counts:TaskStatusCounts, worker:WorkerStatus, verify_metrics:VerifyMetrics, proxy_pool_status:ProxyPoolStatus, identity_session_metrics:IdentitySessionMetrics, auth_metrics:AuthMetrics, proxy_harvest_metrics:ProxyHarvestMetrics, latest_tasks:any[] }} StatusSnapshot */
/** @typedef {{ id:string, share_token:string, share_url:string, share_expires_at:string, status:string, login_url:string, site_key:string, success_hint:(string|null), behavior_profile_id:(string|null), identity_profile_id:(string|null), session_profile_id:(string|null), fingerprint_profile_id:(string|null), proxy_id:(string|null), credential_mode:string, credential_ref:(string|null), inferred_contract_json:any, final_contract_json:any, site_policy_id:(string|null), site_policy_version:(number|null), shadow_task_id:(string|null), active_success_task_id:(string|null), active_failure_task_id:(string|null), continuity_task_id:(string|null), evidence_summary_json:any, site_contract_present:boolean, created_at:string, updated_at:string }} DashboardOnboardingDraft */
/** @typedef {{ status:(StatusSnapshot|null), status_error:(string|null), runtime_mode:string, gateway_stats_snapshot:GatewayStatsSnapshot, behavior_profiles:NamedResourceOption[], identity_profiles:NamedResourceOption[], session_profiles:NamedResourceOption[], fingerprint_profiles:NamedResourceOption[], proxies:ProxyOption[], site_policies:SitePolicyOption[], overview_tasks:DashboardTaskListItem[], continuity_events:DashboardContinuityEvent[], site_validation_rollups:DashboardSiteValidationRollup[], drafts:DashboardOnboardingDraft[] }} DashboardBootstrap */
