package main

import (
	"ant-chrome/backend/internal/events"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	projRoot := findProjectRoot()

	// Generate TypeScript types
	tsPath := filepath.Join(projRoot, "frontend", "src", "wailsjs", "go", "events", "gen_types.ts")
	if err := os.MkdirAll(filepath.Dir(tsPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "create dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(tsPath, []byte(generateTSTypes()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write ts types: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated:", tsPath)

	// Generate event documentation
	docPath := filepath.Join(projRoot, "EVENTS.md")
	if err := os.WriteFile(docPath, []byte(generateDocs()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write docs: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated:", docPath)

	// Generate Go constants for new events (those without constants yet)
	goConstPath := filepath.Join(projRoot, "backend", "internal", "events", "gen_constants.go")
	if err := os.WriteFile(goConstPath, []byte(generateGoConstants()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write go constants: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated:", goConstPath)

	// Generate TypeScript listener hooks
	listenersPath := filepath.Join(projRoot, "frontend", "src", "wailsjs", "go", "events", "gen_listeners.ts")
	if err := os.WriteFile(listenersPath, []byte(generateTSListeners()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write ts listeners: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated:", listenersPath)

	// Generate YAML schema
	schemaPath := filepath.Join(projRoot, "backend", "internal", "events", "schema.yaml")
	if err := os.WriteFile(schemaPath, []byte(generateYAMLSchema()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write yaml schema: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated:", schemaPath)

	// Generate Go type-safe emitter functions
	emittersPath := filepath.Join(projRoot, "backend", "internal", "events", "gen_emitters.go")
	if err := os.WriteFile(emittersPath, []byte(generateGoEmitters()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write go emitters: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated:", emittersPath)
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func generateTSTypes() string {
	var b strings.Builder
	b.WriteString("// Auto-generated by backend/cmd/gen-events. DO NOT EDIT.\n")
	b.WriteString("// Source: backend/internal/events/registry.go\n\n")

	byNS := events.RegistryNamesByNamespace()
	namespaces := make([]string, 0, len(byNS))
	for ns := range byNS {
		namespaces = append(namespaces, ns)
	}
	sort.Strings(namespaces)

	b.WriteString("// EventName is the union of all known event name strings.\n")
	b.WriteString("export type EventName =\n")
	allNames := events.AllRegistryNames()
	sort.Strings(allNames)
	for i, name := range allNames {
		sep := " |"
		if i == len(allNames)-1 {
			sep = ";"
		}
		b.WriteString(fmt.Sprintf("  '%s'%s\n", name, sep))
	}
	b.WriteString("\n")

	for _, ns := range namespaces {
		names := byNS[ns]
		sort.Strings(names)

		b.WriteString(fmt.Sprintf("// ─── %s ──────────────────────────────────────────────\n", strings.ToUpper(ns)))

		for _, name := range names {
			def := events.Registry[name]
			if len(def.Payload) == 0 {
				continue
			}

			ifaceName := eventNameToTSIface(name) + "Payload"
			b.WriteString(fmt.Sprintf("export interface %s {\n", ifaceName))
			for _, field := range def.Payload {
				optional := ""
				if !field.Required {
					optional = "?"
				}
				tsType := goTypeToTS(field.Type)
				b.WriteString(fmt.Sprintf("  %s%s: %s;\n", field.Name, optional, tsType))
			}
			b.WriteString("}\n\n")
		}
	}

	b.WriteString("// EventPayloadMap maps each event name to its payload type.\n")
	b.WriteString("export type EventPayloadMap = {\n")
	for _, name := range allNames {
		def := events.Registry[name]
		if len(def.Payload) == 0 {
			b.WriteString(fmt.Sprintf("  '%s': Record<string, never>;\n", name))
		} else {
			b.WriteString(fmt.Sprintf("  '%s': %sPayload;\n", name, eventNameToTSIface(name)))
		}
	}
	b.WriteString("};\n\n")

	b.WriteString("// TypedEventPayload extracts the payload type for a given event name.\n")
	b.WriteString("export type TypedEventPayload<N extends EventName> = EventPayloadMap[N];\n")

	return b.String()
}

func generateDocs() string {
	var b strings.Builder
	b.WriteString("# Ant Browser Events Reference\n\n")
	b.WriteString("> Auto-generated by `backend/cmd/gen-events`. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("**Total events:** %d\n\n", len(events.Registry)))

	byNS := events.RegistryNamesByNamespace()
	namespaces := make([]string, 0, len(byNS))
	for ns := range byNS {
		namespaces = append(namespaces, ns)
	}
	sort.Strings(namespaces)

	b.WriteString("## Table of Contents\n\n")
	for _, ns := range namespaces {
		names := byNS[ns]
		b.WriteString(fmt.Sprintf("- [%s](#%s) (%d events)\n", ns, ns, len(names)))
	}
	b.WriteString("\n")

	severityIcon := func(s string) string {
		switch s {
		case "critical":
			return "🔴"
		case "error":
			return "🟠"
		case "warn":
			return "🟡"
		case "info":
			return "🔵"
		default:
			return "⚪"
		}
	}

	for _, ns := range namespaces {
		names := byNS[ns]
		sort.Strings(names)

		b.WriteString(fmt.Sprintf("## %s\n\n", ns))
		b.WriteString("| Event | Severity | Description | Payload |\n")
		b.WriteString("|-------|----------|-------------|--------|\n")

		for _, name := range names {
			def := events.Registry[name]
			sev := severityIcon(def.Severity) + " " + def.Severity
			payloadDesc := "-"
			if len(def.Payload) > 0 {
				var fields []string
				for _, f := range def.Payload {
					req := ""
					if f.Required {
						req = "*"
					}
					fields = append(fields, fmt.Sprintf("`%s` (%s)%s", f.Name, f.Type, req))
				}
				payloadDesc = strings.Join(fields, ", ")
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", name, sev, def.Description, payloadDesc))
		}
		b.WriteString("\n")
	}

	return b.String()
}

func generateGoConstants() string {
	var b strings.Builder
	b.WriteString("// Code generated by backend/cmd/gen-events. DO NOT EDIT.\n")
	b.WriteString("// Source: backend/internal/events/registry.go\n\n")
	b.WriteString("package events\n\n")
	b.WriteString("// Phase 2 event name constants (generated).\n")
	b.WriteString("const (\n")

	existingConstants := map[string]bool{
		events.EventBrowserInstanceStarted:          true,
		events.EventBrowserInstanceStopped:          true,
		events.EventBrowserInstanceCrashed:          true,
		events.EventBrowserInstanceUpdated:          true,
		events.EventProxyBridgeDied:                 true,
		events.EventProxyBridgeFailed:               true,
		events.EventProxySpeedResult:                true,
		events.EventProxyIPHealthResult:             true,
		events.EventRiskFingerprintMismatch:         true,
		events.EventRiskFingerprintTimezoneIP:       true,
		events.EventRiskProxyHighLatency:            true,
		events.EventRiskProxyHealthDrop:             true,
		events.EventRiskProxyDatacenter:             true,
		events.EventRiskProxyAuthFailure:            true,
		events.EventRiskWebRTCLeak:                  true,
		events.EventRiskDNSLeak:                     true,
		events.EventRiskCaptchaDetected:             true,
		events.EventRiskCaptchaFailed:               true,
		events.EventRiskBrowserCrashLoop:            true,
		events.EventRiskSessionRateLimit:            true,
		events.EventRiskSessionCookieCleared:        true,
		events.EventRiskSessionSecurityChallenge:    true,
		events.EventRiskSystemLowDisk:               true,
		events.EventRiskSystemMemoryPressure:        true,
		events.EventRiskProfileCorrupted:            true,
		events.EventRiskNodeBanned:                  true,
		events.EventRiskNodeGeoJump:                 true,
		events.EventRiskNodeOffline:                 true,
		events.EventAppRequestClose:                 true,
		events.EventDownloadProgress:                true,
	}

	allNames := events.AllRegistryNames()
	sort.Strings(allNames)

	for _, name := range allNames {
		if existingConstants[name] {
			continue
		}
		constName := eventNameToGoConst(name)
		b.WriteString(fmt.Sprintf("\t// %s is generated from registry.\n", constName))
		b.WriteString(fmt.Sprintf("\t%s = \"%s\"\n", constName, name))
	}

	b.WriteString(")\n")
	return b.String()
}

func generateTSListeners() string {
	var b strings.Builder
	b.WriteString("// Auto-generated by backend/cmd/gen-events. DO NOT EDIT.\n")
	b.WriteString("// Type-safe listener hooks for all registered events.\n")
	b.WriteString("// Usage:\n")
	b.WriteString("//   import { onAccountLoginSuccess } from '@wails/events';\n")
	b.WriteString("//   const unsub = onAccountLoginSuccess((payload) => { ... });\n")
	b.WriteString("//   // later: unsub();\n\n")
	b.WriteString("import { EventsOn } from '../../runtime/runtime';\n")
	b.WriteString("import type { EventName, EventPayloadMap } from './gen_types';\n\n")

	allNames := events.AllRegistryNames()
	sort.Strings(allNames)

	for _, name := range allNames {
		def := events.Registry[name]
		funcName := eventNameToTSListenerFn(name)
		if len(def.Payload) == 0 {
			b.WriteString(fmt.Sprintf(
				"/** %s */\nexport function %s(handler: () => void): () => void {\n  return EventsOn('%s', handler);\n}\n\n",
				def.Description, funcName, name,
			))
		} else {
			b.WriteString(fmt.Sprintf(
				"/** %s */\nexport function %s(handler: (payload: EventPayloadMap['%s']) => void): () => void {\n  return EventsOn('%s', handler);\n}\n\n",
				def.Description, funcName, name, name,
			))
		}
	}

	// Generic typed listener
	b.WriteString("// TypedOn is a generic listener that infers payload from the event name.\n")
	b.WriteString("export function TypedOn<N extends EventName>(\n")
	b.WriteString("  eventName: N,\n")
	b.WriteString("  handler: (payload: EventPayloadMap[N]) => void\n")
	b.WriteString("): () => void {\n")
	b.WriteString("  return EventsOn(eventName, handler as (payload: unknown) => void);\n")
	b.WriteString("}\n")

	return b.String()
}

func generateYAMLSchema() string {
	var b strings.Builder
	b.WriteString("# Auto-generated by backend/cmd/gen-events. DO NOT EDIT.\n")
	b.WriteString("# Source: backend/internal/events/registry.go\n\n")

	byNS := events.RegistryNamesByNamespace()
	namespaces := make([]string, 0, len(byNS))
	for ns := range byNS {
		namespaces = append(namespaces, ns)
	}
	sort.Strings(namespaces)

	b.WriteString("namespaces:\n")
	for _, ns := range namespaces {
		names := byNS[ns]
		sort.Strings(names)
		b.WriteString(fmt.Sprintf("  %s:\n", ns))
		b.WriteString("    events:\n")
		for _, name := range names {
			def := events.Registry[name]
			b.WriteString(fmt.Sprintf("      - name: \"%s\"\n", name))
			b.WriteString(fmt.Sprintf("        description: \"%s\"\n", def.Description))
			b.WriteString(fmt.Sprintf("        severity: \"%s\"\n", def.Severity))
			if len(def.Payload) > 0 {
				b.WriteString("        payload:\n")
				for _, f := range def.Payload {
					req := ""
					if f.Required {
						req = " (required)"
					}
					b.WriteString(fmt.Sprintf("          - field: \"%s\"\n", f.Name))
					b.WriteString(fmt.Sprintf("            type: \"%s\"%s\n", f.Type, req))
				}
			}
		}
	}
	return b.String()
}

func generateGoEmitters() string {
	var b strings.Builder
	b.WriteString("// Code generated by backend/cmd/gen-events. DO NOT EDIT.\n")
	b.WriteString("// Source: backend/internal/events/registry.go\n\n")
	b.WriteString("package events\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString(")\n\n")

	allNames := events.AllRegistryNames()
	sort.Strings(allNames)

	// Track generated struct names to avoid duplicates
	generatedStructs := make(map[string]bool)

	// Generate payload structs
	b.WriteString("// ─── Payload Types ──────────────────────────────────────────────\n\n")
	for _, name := range allNames {
		def := events.Registry[name]
		if len(def.Payload) == 0 {
			continue
		}
		structName := eventNameToTSIface(name) + "Payload"
		if generatedStructs[structName] {
			continue
		}
		generatedStructs[structName] = true

		b.WriteString(fmt.Sprintf("// %s is the payload for event \"%s\".\n", structName, name))
		b.WriteString(fmt.Sprintf("type %s struct {\n", structName))
		for _, field := range def.Payload {
			goField := camelToPascal(field.Name)
			goType := eventFieldGoType(field.Type)
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", goField, goType, field.Name))
		}
		b.WriteString("}\n\n")
	}

	// Generate Emit functions
	b.WriteString("// ─── Emitter Functions ──────────────────────────────────────────\n\n")
	b.WriteString("// toMap converts a struct to map[string]interface{} via JSON round-trip.\n")
	b.WriteString("func toMap(v interface{}) map[string]interface{} {\n")
	b.WriteString("\tdata, _ := json.Marshal(v)\n")
	b.WriteString("\tvar result map[string]interface{}\n")
	b.WriteString("\t_ = json.Unmarshal(data, &result)\n")
	b.WriteString("\treturn result\n")
	b.WriteString("}\n\n")

	for _, name := range allNames {
		def := events.Registry[name]
		funcName := "Emit" + eventNameToTSIface(name)

		b.WriteString(fmt.Sprintf("// %s emits a \"%s\" event.\n", funcName, name))
		b.WriteString(fmt.Sprintf("// %s\n", def.Description))

		if len(def.Payload) == 0 {
			b.WriteString(fmt.Sprintf(
				"func %s(ctx context.Context) {\n\tEmitAndLog(ctx, %s)\n}\n\n",
				funcName, eventConstName(name),
			))
		} else {
			structName := eventNameToTSIface(name) + "Payload"
			b.WriteString(fmt.Sprintf(
				"func %s(ctx context.Context, data %s) {\n\tEmitAndLog(ctx, %s, toMap(data))\n}\n\n",
				funcName, structName, eventConstName(name),
			))
		}
	}

	return b.String()
}

func eventNameToTSListenerFn(name string) string {
	return "on" + eventNameToTSIface(name)
}

func eventNameToTSIface(name string) string {
	parts := strings.Split(name, ":")
	var result strings.Builder
	for _, part := range parts {
		for _, segment := range strings.Split(part, "-") {
			if len(segment) > 0 {
				result.WriteString(strings.ToUpper(segment[:1]))
				result.WriteString(segment[1:])
			}
		}
	}
	return result.String()
}

func eventNameToGoConst(name string) string {
	return "Event" + eventNameToTSIface(name)
}

func goTypeToTS(goType string) string {
	switch goType {
	case "string":
		return "string"
	case "int", "int32", "int64", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "[]string":
		return "string[]"
	case "map[string]interface{}":
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}

// camelToPascal converts "profileId" → "ProfileId", "debugPort" → "DebugPort"
func camelToPascal(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// eventFieldGoType maps registry field types to Go types.
func eventFieldGoType(t string) string {
	switch t {
	case "string":
		return "string"
	case "int":
		return "int"
	case "int64":
		return "int64"
	case "float64":
		return "float64"
	case "bool":
		return "bool"
	case "[]string":
		return "[]string"
	case "map[string]interface{}":
		return "map[string]interface{}"
	default:
		return "interface{}"
	}
}

// eventConstName returns the Go constant name for an event.
// It checks the manually-defined constants first, falling back to auto-generation.
func eventConstName(name string) string {
	if cn, ok := manualEventConstants[name]; ok {
		return cn
	}
	return eventNameToGoConst(name)
}

// manualEventConstants maps event name strings to their manually-defined Go constant names
// from events.go. These take priority over auto-generated names.
var manualEventConstants = map[string]string{
	events.EventBrowserInstanceStarted:         "EventBrowserInstanceStarted",
	events.EventBrowserInstanceStopped:         "EventBrowserInstanceStopped",
	events.EventBrowserInstanceCrashed:         "EventBrowserInstanceCrashed",
	events.EventBrowserInstanceUpdated:         "EventBrowserInstanceUpdated",
	events.EventProxyBridgeDied:                "EventProxyBridgeDied",
	events.EventProxyBridgeFailed:              "EventProxyBridgeFailed",
	events.EventProxySpeedResult:               "EventProxySpeedResult",
	events.EventProxyIPHealthResult:            "EventProxyIPHealthResult",
	events.EventRiskFingerprintMismatch:        "EventRiskFingerprintMismatch",
	events.EventRiskFingerprintTimezoneIP:      "EventRiskFingerprintTimezoneIP",
	events.EventRiskProxyHighLatency:           "EventRiskProxyHighLatency",
	events.EventRiskProxyHealthDrop:            "EventRiskProxyHealthDrop",
	events.EventRiskProxyDatacenter:            "EventRiskProxyDatacenter",
	events.EventRiskProxyAuthFailure:           "EventRiskProxyAuthFailure",
	events.EventRiskWebRTCLeak:                 "EventRiskWebRTCLeak",
	events.EventRiskDNSLeak:                    "EventRiskDNSLeak",
	events.EventRiskCaptchaDetected:            "EventRiskCaptchaDetected",
	events.EventRiskCaptchaFailed:              "EventRiskCaptchaFailed",
	events.EventRiskBrowserCrashLoop:           "EventRiskBrowserCrashLoop",
	events.EventRiskSessionRateLimit:           "EventRiskSessionRateLimit",
	events.EventRiskSessionCookieCleared:       "EventRiskSessionCookieCleared",
	events.EventRiskSessionSecurityChallenge:   "EventRiskSessionSecurityChallenge",
	events.EventRiskSystemLowDisk:              "EventRiskSystemLowDisk",
	events.EventRiskSystemMemoryPressure:       "EventRiskSystemMemoryPressure",
	events.EventRiskProfileCorrupted:           "EventRiskProfileCorrupted",
	events.EventRiskNodeBanned:                 "EventRiskNodeBanned",
	events.EventRiskNodeGeoJump:                "EventRiskNodeGeoJump",
	events.EventRiskNodeOffline:                "EventRiskNodeOffline",
	events.EventAppRequestClose:                "EventAppRequestClose",
	events.EventDownloadProgress:               "EventDownloadProgress",
}
