#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import statistics
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from prod_live_presets import infer_provider_supply_class
from release_prod_live_gate import Thresholds, evaluate_report_payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sample /status or summarize pre-collected long-run proxy/session samples.",
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:3000",
        help="Control-plane base URL",
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("PERSONA_PILOT_API_KEY", ""),
        help="Optional API key for protected control-plane endpoints",
    )
    parser.add_argument(
        "--samples",
        type=int,
        default=5,
        help="Number of /status samples to capture when --input-json is not provided",
    )
    parser.add_argument(
        "--interval-seconds",
        type=int,
        default=60,
        help="Delay between samples in seconds when --input-json is not provided",
    )
    parser.add_argument(
        "--input-json",
        help="Optional pre-collected sample payload generated by proxy_real_longrun_driver.py",
    )
    parser.add_argument(
        "--txt-output",
        default="reports/proxy_longrun_latest.txt",
        help="Text report output path",
    )
    parser.add_argument(
        "--json-output",
        default="reports/proxy_longrun_latest.json",
        help="JSON report output path",
    )
    return parser.parse_args()


def fetch_status(base_url: str, api_key: str = "") -> dict[str, object]:
    url = f"{base_url.rstrip('/')}/status"
    headers = {"Accept": "application/json"}
    if api_key:
        headers["x-api-key"] = api_key
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=15) as response:
        return json.loads(response.read().decode("utf-8"))


def to_int(value: object, default: int = 0) -> int:
    try:
        return int(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return default


def to_float(value: object, default: float = 0.0) -> float:
    try:
        return float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return default


def normalize_mode(value: object, default: str = "demo_public") -> str:
    raw = str(value or "").strip().lower().replace("-", "_")
    if raw == "prod_live":
        return "prod_live"
    if raw == "demo_public":
        return "demo_public"
    return default


def median_or_zero(values: list[float], digits: int = 4) -> float:
    if not values:
        return 0.0
    return round(float(statistics.median(values)), digits)


def summarize_metric(values: list[float]) -> dict[str, float]:
    return {
        "median": median_or_zero(values),
        "min": min(values) if values else 0.0,
        "max": max(values) if values else 0.0,
    }


def derive_active_ratio_percent(active: int, total: int) -> float:
    if total <= 0:
        return 0.0
    return round((active / total) * 100.0, 4)


def summarize_source_balance_from_sources(
    source_summaries: list[dict[str, object]],
) -> dict[str, float | int]:
    active_counts = [
        max(to_int(item.get("active_count")), 0)
        for item in source_summaries
    ]
    active_total = sum(active_counts)
    if active_total <= 0:
        return {
            "source_concentration_top1_percent": 0.0,
            "source_concentration_top3_percent": 0.0,
            "active_sources_with_min_inventory": 0,
        }
    ranked_counts = sorted(active_counts, reverse=True)
    top1 = round((ranked_counts[0] / active_total) * 100.0, 4)
    top3 = round((sum(ranked_counts[:3]) / active_total) * 100.0, 4)
    active_sources_with_min_inventory = sum(1 for count in active_counts if count >= 5)
    return {
        "source_concentration_top1_percent": top1,
        "source_concentration_top3_percent": top3,
        "active_sources_with_min_inventory": active_sources_with_min_inventory,
    }


def delta_or_zero(samples: list[dict[str, object]], key: str) -> int:
    if len(samples) < 2:
        return 0
    return to_int(samples[-1].get(key)) - to_int(samples[0].get(key))


def build_sample(
    status: dict[str, object],
    *,
    captured_at: int | None = None,
    fallback_mode: str = "",
) -> dict[str, object]:
    pool = dict(status.get("proxy_pool_status") or {})
    replenish = dict(status.get("proxy_replenish_metrics") or {})
    harvest = dict(status.get("proxy_harvest_metrics") or {})
    sessions = dict(status.get("identity_session_metrics") or {})
    sites = dict(status.get("proxy_site_metrics") or {})
    pool_total = to_int(pool.get("total"))
    pool_active = to_int(pool.get("active"))
    mode = normalize_mode(status.get("mode") or pool.get("mode") or fallback_mode)
    source_summaries = [
        dict(item)
        for item in (harvest.get("source_summaries") or [])
        if isinstance(item, dict)
    ]
    source_balance = summarize_source_balance_from_sources(source_summaries)
    reported_active_ratio_percent = to_float(
        pool.get("reported_active_ratio_percent", pool.get("active_ratio_percent"))
    )
    effective_active_ratio_percent = to_float(
        pool.get("effective_active_ratio_percent", pool.get("active_ratio_percent"))
    )
    derived_active_ratio_percent = derive_active_ratio_percent(pool_active, pool_total)
    return {
        "captured_at": captured_at if captured_at is not None else int(time.time()),
        "mode": mode,
        "queue_len": to_int(status.get("queue_len")),
        "active_ratio_percent": effective_active_ratio_percent,
        "effective_active_ratio_percent": effective_active_ratio_percent,
        "reported_active_ratio_percent": reported_active_ratio_percent,
        "derived_active_ratio_percent": derived_active_ratio_percent,
        "pool_total": pool_total,
        "pool_active": pool_active,
        "pool_candidate": to_int(pool.get("candidate")),
        "pool_candidate_rejected": to_int(pool.get("candidate_rejected")),
        "eligible_pool_total": to_int(pool.get("eligible_pool_total")),
        "fresh_candidate_total": to_int(pool.get("fresh_candidate_total")),
        "recent_rejected_total": to_int(pool.get("recent_rejected_total")),
        "region_shortages": list(pool.get("region_shortages") or []),
        "hot_regions": list(pool.get("hot_regions") or []),
        "recent_hot_regions": list(pool.get("recent_hot_regions") or []),
        "recent_hot_region_counts": dict(pool.get("recent_hot_region_counts") or {}),
        "hot_region_window_seconds": to_int(pool.get("hot_region_window_seconds")),
        "source_concentration_top1_percent": to_float(
            pool.get("source_concentration_top1_percent"),
            to_float(source_balance.get("source_concentration_top1_percent")),
        ),
        "source_concentration_top3_percent": to_float(
            pool.get("source_concentration_top3_percent"),
            to_float(source_balance.get("source_concentration_top3_percent")),
        ),
        "active_sources_with_min_inventory": to_int(
            pool.get("active_sources_with_min_inventory"),
            to_int(source_balance.get("active_sources_with_min_inventory")),
        ),
        "active_regions_with_min_inventory": to_int(pool.get("active_regions_with_min_inventory")),
        "promotion_rate": to_float(replenish.get("promotion_rate")),
        "reject_rate": to_float(replenish.get("reject_rate")),
        "fallback_rate": to_float(replenish.get("fallback_rate")),
        "recent_batches": to_int(replenish.get("recent_batches")),
        "source_count": to_int(harvest.get("source_count")),
        "healthy_source_count": to_int(harvest.get("healthy_source_count")),
        "due_source_count": to_int(harvest.get("due_source_count")),
        "source_failures": to_int(harvest.get("source_failures")),
        "effective_geo_quality_summary": summarize_geo_quality_from_sources(source_summaries),
        "active_sessions": to_int(sessions.get("active_sessions")),
        "reused_sessions": to_int(sessions.get("reused_sessions")),
        "created_sessions": to_int(sessions.get("created_sessions")),
        "cookie_restore_count": to_int(sessions.get("cookie_restore_count")),
        "cookie_persist_count": to_int(sessions.get("cookie_persist_count")),
        "local_storage_restore_count": to_int(sessions.get("local_storage_restore_count")),
        "local_storage_persist_count": to_int(sessions.get("local_storage_persist_count")),
        "session_storage_restore_count": to_int(sessions.get("session_storage_restore_count")),
        "session_storage_persist_count": to_int(sessions.get("session_storage_persist_count")),
        "tracked_sites": to_int(sites.get("tracked_sites")),
        "site_records": to_int(sites.get("site_records")),
        "top_failing_sites": list(sites.get("top_failing_sites") or []),
    }


def load_samples_from_input(
    input_path: str,
) -> tuple[
    str,
    list[dict[str, object]],
    list[str],
    list[dict[str, object]],
    list[dict[str, object]],
    dict[str, object],
]:
    payload = json.loads(Path(input_path).read_text(encoding="utf-8"))
    base_url = str(payload.get("base_url") or "http://127.0.0.1:3000")
    events = list(payload.get("events") or [])
    errors = [str(item) for item in (payload.get("errors") or [])]
    run_context = {
        "mode": payload.get("mode"),
        "preset": payload.get("preset"),
        "stateful_followup_count": payload.get("stateful_followup_count"),
        "sticky_stateful_region": payload.get("sticky_stateful_region"),
        "pool_hygiene_extra_args": list(payload.get("pool_hygiene_extra_args") or []),
    }

    raw_samples = list(payload.get("samples") or [])
    snapshots = list(payload.get("status_snapshots") or [])
    if raw_samples:
        return base_url, raw_samples, errors, events, snapshots, run_context

    samples = [
        build_sample(
            dict(item.get("status") or {}),
            captured_at=to_int(item.get("captured_at"), int(time.time())),
            fallback_mode=str(run_context.get("mode") or ""),
        )
        for item in snapshots
    ]
    return base_url, samples, errors, events, snapshots, run_context


def summarize_events(events: list[dict[str, object]]) -> dict[str, int]:
    summary: dict[str, object] = {
        "harvest_total": 0,
        "harvest_completed": 0,
        "harvest_partial": 0,
        "harvest_failed": 0,
        "geo_enrich_total": 0,
        "geo_enrich_succeeded": 0,
        "geo_enrich_failed": 0,
        "geo_enrich_updated_proxy_rows_total": 0,
        "geo_enrich_updated_source_rows_total": 0,
        "geo_enrich_lookup_succeeded_total": 0,
        "geo_enrich_lookup_failed_total": 0,
        "geo_enrich_active_region_count_before_last": 0,
        "geo_enrich_active_region_count_after_last": 0,
        "geo_enrich_active_regions_after_last": [],
        "hygiene_total": 0,
        "hygiene_succeeded": 0,
        "hygiene_failed": 0,
        "hygiene_deleted_proxy_rows_total": 0,
        "hygiene_quarantined_sources_total": 0,
        "hygiene_ratio_before_last": 0.0,
        "hygiene_ratio_after_last": 0.0,
        "browser_total": 0,
        "browser_succeeded": 0,
        "browser_failed": 0,
        "browser_timed_out": 0,
        "browser_cancelled": 0,
        "external_browser_total": 0,
        "external_browser_succeeded": 0,
        "stateful_browser_total": 0,
        "stateful_browser_succeeded": 0,
        "stateful_primary_total": 0,
        "stateful_primary_succeeded": 0,
        "stateful_followup_total": 0,
        "stateful_followup_succeeded": 0,
        "browser_distinct_proxy_count": 0,
        "browser_distinct_url_count": 0,
        "browser_requested_regions": {},
        "browser_hot_regions_observed": {},
        "browser_recent_hot_regions_observed": {},
        "browser_region_shortages_observed": {},
        "browser_identity_session_statuses": {},
        "browser_proxy_not_found_failures": 0,
        "browser_proxy_claim_lost_failures": 0,
        "browser_cookie_restore_total": 0,
        "browser_cookie_persist_total": 0,
        "browser_local_storage_restore_total": 0,
        "browser_local_storage_persist_total": 0,
        "browser_session_storage_restore_total": 0,
        "browser_session_storage_persist_total": 0,
    }
    browser_proxy_ids: set[str] = set()
    browser_urls: set[str] = set()
    requested_region_counts: dict[str, int] = {}
    hot_region_counts: dict[str, int] = {}
    recent_hot_region_counts: dict[str, int] = {}
    region_shortage_counts: dict[str, int] = {}
    identity_status_counts: dict[str, int] = {}
    for event in events:
        event_type = str(event.get("type") or "")
        status = str(event.get("status") or "")
        if event_type == "harvest":
            summary["harvest_total"] = int(summary["harvest_total"]) + 1
            if status == "completed":
                summary["harvest_completed"] = int(summary["harvest_completed"]) + 1
            elif status == "partial":
                summary["harvest_partial"] = int(summary["harvest_partial"]) + 1
            else:
                summary["harvest_failed"] = int(summary["harvest_failed"]) + 1
        elif event_type == "geo_enrich":
            summary["geo_enrich_total"] = int(summary["geo_enrich_total"]) + 1
            if status == "completed":
                summary["geo_enrich_succeeded"] = int(summary["geo_enrich_succeeded"]) + 1
            else:
                summary["geo_enrich_failed"] = int(summary["geo_enrich_failed"]) + 1
            summary["geo_enrich_updated_proxy_rows_total"] = int(
                summary["geo_enrich_updated_proxy_rows_total"]
            ) + to_int(event.get("updated_proxy_rows"))
            summary["geo_enrich_updated_source_rows_total"] = int(
                summary["geo_enrich_updated_source_rows_total"]
            ) + to_int(event.get("updated_source_rows"))
            summary["geo_enrich_lookup_succeeded_total"] = int(
                summary["geo_enrich_lookup_succeeded_total"]
            ) + to_int(event.get("lookup_succeeded"))
            summary["geo_enrich_lookup_failed_total"] = int(
                summary["geo_enrich_lookup_failed_total"]
            ) + to_int(event.get("lookup_failed"))
            summary["geo_enrich_active_region_count_before_last"] = to_int(
                event.get("active_region_count_before")
            )
            summary["geo_enrich_active_region_count_after_last"] = to_int(
                event.get("active_region_count_after")
            )
            summary["geo_enrich_active_regions_after_last"] = list(event.get("active_regions_after") or [])
        elif event_type == "hygiene":
            summary["hygiene_total"] = int(summary["hygiene_total"]) + 1
            if status == "completed":
                summary["hygiene_succeeded"] = int(summary["hygiene_succeeded"]) + 1
            else:
                summary["hygiene_failed"] = int(summary["hygiene_failed"]) + 1
            summary["hygiene_deleted_proxy_rows_total"] = int(summary["hygiene_deleted_proxy_rows_total"]) + to_int(
                event.get("deleted_proxy_rows")
            )
            summary["hygiene_quarantined_sources_total"] = int(
                summary["hygiene_quarantined_sources_total"]
            ) + to_int(event.get("quarantined_sources"))
            summary["hygiene_ratio_before_last"] = round(
                to_float(event.get("effective_active_ratio_percent_before")),
                4,
            )
            summary["hygiene_ratio_after_last"] = round(
                to_float(event.get("effective_active_ratio_percent_after")),
                4,
            )
        elif event_type == "browser":
            summary["browser_total"] = int(summary["browser_total"]) + 1
            workload = str(event.get("workload") or "external")
            if status == "succeeded":
                summary["browser_succeeded"] = int(summary["browser_succeeded"]) + 1
            elif status == "timed_out":
                summary["browser_timed_out"] = int(summary["browser_timed_out"]) + 1
            elif status == "cancelled":
                summary["browser_cancelled"] = int(summary["browser_cancelled"]) + 1
            else:
                summary["browser_failed"] = int(summary["browser_failed"]) + 1
            if workload.startswith("stateful"):
                summary["stateful_browser_total"] = int(summary["stateful_browser_total"]) + 1
                if status == "succeeded":
                    summary["stateful_browser_succeeded"] = int(summary["stateful_browser_succeeded"]) + 1
                if workload == "stateful":
                    summary["stateful_primary_total"] = int(summary["stateful_primary_total"]) + 1
                    if status == "succeeded":
                        summary["stateful_primary_succeeded"] = int(
                            summary["stateful_primary_succeeded"]
                        ) + 1
                elif workload == "stateful_followup":
                    summary["stateful_followup_total"] = int(summary["stateful_followup_total"]) + 1
                    if status == "succeeded":
                        summary["stateful_followup_succeeded"] = int(
                            summary["stateful_followup_succeeded"]
                        ) + 1
            else:
                summary["external_browser_total"] = int(summary["external_browser_total"]) + 1
                if status == "succeeded":
                    summary["external_browser_succeeded"] = int(summary["external_browser_succeeded"]) + 1

            proxy_id = str(event.get("proxy_id") or "").strip()
            target_url = str(event.get("url") or "").strip()
            identity_status = str(event.get("identity_session_status") or "").strip()
            if proxy_id:
                browser_proxy_ids.add(proxy_id)
            if target_url:
                browser_urls.add(target_url)
            requested_region = str(event.get("requested_region") or "").strip()
            if requested_region:
                requested_region_counts[requested_region] = requested_region_counts.get(requested_region, 0) + 1
            for hot_region in list(event.get("hot_regions_during_request") or []):
                hot_region_text = str(hot_region).strip()
                if hot_region_text:
                    hot_region_counts[hot_region_text] = hot_region_counts.get(hot_region_text, 0) + 1
            for recent_hot_region in list(event.get("recent_hot_regions_during_request") or []):
                recent_hot_region_text = str(recent_hot_region).strip()
                if recent_hot_region_text:
                    recent_hot_region_counts[recent_hot_region_text] = (
                        recent_hot_region_counts.get(recent_hot_region_text, 0) + 1
                    )
            for shortage in list(event.get("region_shortages_during_request") or []):
                shortage_text = str(shortage).strip()
                if shortage_text:
                    region_shortage_counts[shortage_text] = region_shortage_counts.get(shortage_text, 0) + 1
            if identity_status:
                identity_status_counts[identity_status] = identity_status_counts.get(identity_status, 0) + 1
            browser_error_blob = " ".join(
                str(event.get(key) or "")
                for key in ("error_message", "error", "selection_reason_summary", "browser_failure_signal")
            ).lower()
            if "proxy not found" in browser_error_blob:
                summary["browser_proxy_not_found_failures"] = int(
                    summary["browser_proxy_not_found_failures"]
                ) + 1
            if "proxy not found after selection claim" in browser_error_blob or "claim_lost" in browser_error_blob:
                summary["browser_proxy_claim_lost_failures"] = int(
                    summary["browser_proxy_claim_lost_failures"]
                ) + 1
            summary["browser_cookie_restore_total"] = int(summary["browser_cookie_restore_total"]) + to_int(event.get("cookie_restore_count"))
            summary["browser_cookie_persist_total"] = int(summary["browser_cookie_persist_total"]) + to_int(event.get("cookie_persist_count"))
            summary["browser_local_storage_restore_total"] = int(summary["browser_local_storage_restore_total"]) + to_int(event.get("local_storage_restore_count"))
            summary["browser_local_storage_persist_total"] = int(summary["browser_local_storage_persist_total"]) + to_int(event.get("local_storage_persist_count"))
            summary["browser_session_storage_restore_total"] = int(summary["browser_session_storage_restore_total"]) + to_int(event.get("session_storage_restore_count"))
            summary["browser_session_storage_persist_total"] = int(summary["browser_session_storage_persist_total"]) + to_int(event.get("session_storage_persist_count"))

    summary["browser_distinct_proxy_count"] = len(browser_proxy_ids)
    summary["browser_distinct_url_count"] = len(browser_urls)
    summary["browser_requested_regions"] = requested_region_counts
    summary["browser_hot_regions_observed"] = hot_region_counts
    summary["browser_recent_hot_regions_observed"] = recent_hot_region_counts
    summary["browser_region_shortages_observed"] = region_shortage_counts
    summary["browser_identity_session_statuses"] = identity_status_counts
    return summary  # type: ignore[return-value]


def summarize_geo_quality_from_sources(source_summaries: list[dict[str, object]]) -> dict[str, object]:
    declared_counts: dict[str, int] = {}
    effective_counts: dict[str, int] = {}
    active_share_by_effective: dict[str, float] = {}
    coverage_values: list[float] = []
    for item in source_summaries:
        declared_key = str(
            item.get("declared_geo_quality") or item.get("expected_geo_quality") or ""
        ).strip() or "unknown"
        effective_key = str(item.get("effective_geo_quality") or "").strip() or "unknown"
        declared_counts[declared_key] = declared_counts.get(declared_key, 0) + 1
        effective_counts[effective_key] = effective_counts.get(effective_key, 0) + 1
        active_share_by_effective[effective_key] = active_share_by_effective.get(effective_key, 0.0) + to_float(
            item.get("active_share_percent")
        )
        coverage_values.append(round(to_float(item.get("geo_coverage_percent")), 4))
    avg_geo_coverage_percent = round(
        sum(coverage_values) / len(coverage_values),
        4,
    ) if coverage_values else 0.0
    return {
        "declared_geo_quality_counts": dict(
            sorted(declared_counts.items(), key=lambda item: (-item[1], item[0]))
        ),
        "effective_geo_quality_counts": dict(
            sorted(effective_counts.items(), key=lambda item: (-item[1], item[0]))
        ),
        "externally_verified_source_count": to_int(effective_counts.get("externally_verified")),
        "host_geo_inferred_source_count": to_int(effective_counts.get("host_geo_inferred")),
        "mixed_degraded_source_count": to_int(effective_counts.get("mixed_degraded")),
        "unknown_geo_source_count": to_int(effective_counts.get("unknown")),
        "avg_geo_coverage_percent": avg_geo_coverage_percent,
        "median_geo_coverage_percent": median_or_zero(coverage_values),
        "max_geo_coverage_percent": max(coverage_values) if coverage_values else 0.0,
        "active_share_percent_by_effective_geo_quality": {
            key: round(value, 2)
            for key, value in sorted(
                active_share_by_effective.items(),
                key=lambda item: (-item[1], item[0]),
            )
        },
    }


def build_source_quality_summary(status_snapshots: list[dict[str, object]]) -> dict[str, object]:
    latest_status = dict((status_snapshots[-1] or {}).get("status") or {}) if status_snapshots else {}
    harvest = dict(latest_status.get("proxy_harvest_metrics") or {})
    source_summaries = [
        dict(item)
        for item in (harvest.get("source_summaries") or [])
        if isinstance(item, dict)
    ]
    source_summaries.sort(
        key=lambda item: (
            -to_int(item.get("active_count")),
            -to_float(item.get("promotion_rate")),
            -to_float(item.get("health_score")),
            str(item.get("source_label") or ""),
        )
    )
    low_promotion_threshold = 0.05
    quarantined_count = sum(1 for item in source_summaries if str(item.get("quarantine_until") or "").strip())
    healthy_count = sum(1 for item in source_summaries if to_float(item.get("health_score")) >= 60.0)
    active_source_count = sum(1 for item in source_summaries if to_int(item.get("active_count")) > 0)
    prod_source_count = sum(1 for item in source_summaries if bool(item.get("for_prod")))
    demo_source_count = sum(1 for item in source_summaries if bool(item.get("for_demo")))
    controlled_source_count = sum(
        1 for item in source_summaries if str(item.get("source_tier") or "").strip().lower() == "controlled"
    )
    private_paid_source_count = sum(
        1
        for item in source_summaries
        if str(item.get("source_tier") or "").strip().lower() == "private_paid"
        or str(item.get("cost_class") or "").strip().lower() in {"private_paid", "private", "paid", "commercial"}
    )
    geo_quality_summary = summarize_geo_quality_from_sources(source_summaries)
    low_promotion_count = sum(
        1
        for item in source_summaries
        if to_int(item.get("active_count")) + to_int(item.get("candidate_rejected_count")) > 0
        and to_float(item.get("promotion_rate")) < low_promotion_threshold
    )
    top_sources = [
        {
            "source_label": item.get("source_label"),
            "source_tier": item.get("source_tier"),
            "for_demo": bool(item.get("for_demo")),
            "for_prod": bool(item.get("for_prod")),
            "validation_mode": item.get("validation_mode"),
            "expected_geo_quality": item.get("expected_geo_quality"),
            "declared_geo_quality": item.get("declared_geo_quality"),
            "effective_geo_quality": item.get("effective_geo_quality"),
            "cost_class": item.get("cost_class"),
            "geo_coverage_percent": round(to_float(item.get("geo_coverage_percent")), 4),
            "active_share_percent": round(to_float(item.get("active_share_percent")), 4),
            "health_score": round(to_float(item.get("health_score")), 4),
            "promotion_rate": round(to_float(item.get("promotion_rate")), 6),
            "active_count": to_int(item.get("active_count")),
            "candidate_count": to_int(item.get("candidate_count")),
            "candidate_rejected_count": to_int(item.get("candidate_rejected_count")),
            "quarantine_until": item.get("quarantine_until"),
        }
        for item in source_summaries[:5]
    ]
    summary = {
        "source_count": len(source_summaries),
        "healthy_source_count": healthy_count,
        "active_source_count": active_source_count,
        "prod_source_count": prod_source_count,
        "demo_source_count": demo_source_count,
        "controlled_source_count": controlled_source_count,
        "private_paid_source_count": private_paid_source_count,
        "quarantined_source_count": quarantined_count,
        "low_promotion_source_count": low_promotion_count,
        "geo_inferred_source_count": to_int(
            dict(geo_quality_summary.get("effective_geo_quality_counts") or {}).get("host_geo_inferred")
        ),
        "unknown_geo_source_count": to_int(
            dict(geo_quality_summary.get("effective_geo_quality_counts") or {}).get("unknown")
        ),
        "geo_quality_counts": dict(geo_quality_summary.get("declared_geo_quality_counts") or {}),
        "declared_geo_quality_counts": dict(geo_quality_summary.get("declared_geo_quality_counts") or {}),
        "effective_geo_quality_counts": dict(geo_quality_summary.get("effective_geo_quality_counts") or {}),
        "effective_geo_quality_summary": geo_quality_summary,
        "top_sources": top_sources,
    }
    summary["provider_supply_class"] = infer_provider_supply_class(summary)
    return summary


def build_session_continuity_summary(summary: dict[str, object]) -> dict[str, object]:
    trend_flags = dict(summary.get("trend_flags") or {})
    event_summary = dict(summary.get("event_summary") or {})
    session_deltas = dict(summary.get("session_deltas") or {})
    latest = dict(summary.get("latest") or {})
    identity_statuses = dict(event_summary.get("browser_identity_session_statuses") or {})
    auto_created_observed = to_int(identity_statuses.get("auto_created")) > 0
    auto_reused_observed = to_int(identity_statuses.get("auto_reused")) > 0
    storage_restored_observed = any(
        to_int(event_summary.get(key)) > 0
        for key in (
            "browser_cookie_restore_total",
            "browser_local_storage_restore_total",
            "browser_session_storage_restore_total",
        )
    )
    storage_persisted_observed = any(
        to_int(event_summary.get(key)) > 0
        for key in (
            "browser_cookie_persist_total",
            "browser_local_storage_persist_total",
            "browser_session_storage_persist_total",
        )
    )
    continuity_level = "none"
    if bool(trend_flags.get("stateful_continuity_observed")):
        continuity_level = "storage_continuity"
    elif bool(trend_flags.get("session_reuse_observed")):
        continuity_level = "session_reuse"
    return {
        "mode": summary.get("mode") or latest.get("mode") or "demo_public",
        "continuity_level": continuity_level,
        "stateful_continuity_observed": bool(trend_flags.get("stateful_continuity_observed")),
        "session_reuse_observed": bool(trend_flags.get("session_reuse_observed")),
        "auto_created_observed": auto_created_observed,
        "auto_reused_observed": auto_reused_observed,
        "storage_restored_observed": storage_restored_observed,
        "storage_persisted_observed": storage_persisted_observed,
        "continuity_chain_observed": auto_created_observed and auto_reused_observed and storage_restored_observed,
        "identity_session_statuses": identity_statuses,
        "event_totals": {
            "stateful_browser_total": to_int(event_summary.get("stateful_browser_total")),
            "stateful_browser_succeeded": to_int(event_summary.get("stateful_browser_succeeded")),
            "browser_cookie_restore_total": to_int(event_summary.get("browser_cookie_restore_total")),
            "browser_cookie_persist_total": to_int(event_summary.get("browser_cookie_persist_total")),
            "browser_local_storage_restore_total": to_int(event_summary.get("browser_local_storage_restore_total")),
            "browser_local_storage_persist_total": to_int(event_summary.get("browser_local_storage_persist_total")),
            "browser_session_storage_restore_total": to_int(event_summary.get("browser_session_storage_restore_total")),
            "browser_session_storage_persist_total": to_int(event_summary.get("browser_session_storage_persist_total")),
        },
        "session_deltas": {
            "reused_sessions": to_int(session_deltas.get("reused_sessions")),
            "created_sessions": to_int(session_deltas.get("created_sessions")),
            "cookie_restore_count": to_int(session_deltas.get("cookie_restore_count")),
            "cookie_persist_count": to_int(session_deltas.get("cookie_persist_count")),
            "local_storage_restore_count": to_int(session_deltas.get("local_storage_restore_count")),
            "local_storage_persist_count": to_int(session_deltas.get("local_storage_persist_count")),
            "session_storage_restore_count": to_int(session_deltas.get("session_storage_restore_count")),
            "session_storage_persist_count": to_int(session_deltas.get("session_storage_persist_count")),
        },
        "latest_counters": {
            "reused_sessions": to_int(latest.get("reused_sessions")),
            "created_sessions": to_int(latest.get("created_sessions")),
            "cookie_restore_count": to_int(latest.get("cookie_restore_count")),
            "cookie_persist_count": to_int(latest.get("cookie_persist_count")),
            "local_storage_restore_count": to_int(latest.get("local_storage_restore_count")),
            "local_storage_persist_count": to_int(latest.get("local_storage_persist_count")),
            "session_storage_restore_count": to_int(latest.get("session_storage_restore_count")),
            "session_storage_persist_count": to_int(latest.get("session_storage_persist_count")),
        },
    }


def build_real_live_evidence_summary(
    summary: dict[str, object],
    session_summary: dict[str, object],
    events: list[dict[str, object]] | None = None,
) -> dict[str, object]:
    latest = dict(summary.get("latest") or {})
    trend_flags = dict(summary.get("trend_flags") or {})
    event_summary = dict(summary.get("event_summary") or {})
    concentration_summary = dict(summary.get("source_concentration_top1_percent") or {})
    recent_hot_regions_union = [
        str(item).strip()
        for item in list(summary.get("recent_hot_regions_union") or [])
        if str(item).strip()
    ]
    requested_regions = sorted(
        key
        for key in dict(event_summary.get("browser_requested_regions") or {}).keys()
        if str(key).strip()
    )
    observed_hot_regions = sorted(
        key
        for key in dict(event_summary.get("browser_hot_regions_observed") or {}).keys()
        if str(key).strip()
    )
    observed_recent_hot_regions = sorted(
        key
        for key in dict(event_summary.get("browser_recent_hot_regions_observed") or {}).keys()
        if str(key).strip()
    )
    site_host_evidence = build_site_host_evidence(events or [])
    cookie_restore_total = to_int(event_summary.get("browser_cookie_restore_total"))
    cookie_persist_total = to_int(event_summary.get("browser_cookie_persist_total"))
    local_restore_total = to_int(event_summary.get("browser_local_storage_restore_total"))
    local_persist_total = to_int(event_summary.get("browser_local_storage_persist_total"))
    session_restore_total = to_int(event_summary.get("browser_session_storage_restore_total"))
    session_persist_total = to_int(event_summary.get("browser_session_storage_persist_total"))
    storage_restore_positive = {
        "cookie": cookie_restore_total > 0,
        "local_storage": local_restore_total > 0,
        "session_storage": session_restore_total > 0,
    }
    storage_persist_positive = {
        "cookie": cookie_persist_total > 0,
        "local_storage": local_persist_total > 0,
        "session_storage": session_persist_total > 0,
    }
    storage_any_positive = any(storage_restore_positive.values()) or any(
        storage_persist_positive.values()
    )
    storage_all_positive = all(storage_restore_positive.values()) and all(
        storage_persist_positive.values()
    )
    stateful_primary_total = to_int(event_summary.get("stateful_primary_total"))
    stateful_primary_succeeded = to_int(event_summary.get("stateful_primary_succeeded"))
    stateful_followup_total = to_int(event_summary.get("stateful_followup_total"))
    stateful_followup_succeeded = to_int(event_summary.get("stateful_followup_succeeded"))
    browser_total = to_int(event_summary.get("browser_total"))
    sample_sufficient = (
        browser_total >= 6
        and stateful_primary_total >= 2
        and stateful_followup_total >= 1
    )
    continuity_chain_observed = bool(session_summary.get("continuity_chain_observed"))
    evidence_reasons: list[str] = []
    if browser_total < 6:
        evidence_reasons.append("browser_total_below_min")
    if stateful_primary_total < 2:
        evidence_reasons.append("stateful_primary_samples_below_min")
    if stateful_followup_total < 1:
        evidence_reasons.append("stateful_followup_samples_below_min")
    if not bool(trend_flags.get("stateful_continuity_observed")):
        evidence_reasons.append("stateful_continuity_not_observed")
    if not continuity_chain_observed:
        evidence_reasons.append("continuity_chain_not_observed")
    if not storage_any_positive:
        evidence_reasons.append("storage_restore_or_persist_not_observed")
    if to_int(event_summary.get("browser_proxy_claim_lost_failures")) > 0:
        evidence_reasons.append("proxy_claim_lost_failures_detected")
    return {
        "mode": summary.get("mode") or latest.get("mode") or "demo_public",
        "sample_count": to_int(summary.get("sample_count")),
        "browser_total": browser_total,
        "browser_succeeded": to_int(event_summary.get("browser_succeeded")),
        "browser_success_rate_percent": to_float(summary.get("browser_success_rate_percent")),
        "stateful_continuity_observed": bool(trend_flags.get("stateful_continuity_observed")),
        "continuity_chain_observed": continuity_chain_observed,
        "session_reuse_observed": bool(trend_flags.get("session_reuse_observed")),
        "stateful_primary_total": stateful_primary_total,
        "stateful_primary_succeeded": stateful_primary_succeeded,
        "stateful_followup_total": stateful_followup_total,
        "stateful_followup_succeeded": stateful_followup_succeeded,
        "cookie_restore_total": cookie_restore_total,
        "cookie_persist_total": cookie_persist_total,
        "local_storage_restore_total": local_restore_total,
        "local_storage_persist_total": local_persist_total,
        "session_storage_restore_total": session_restore_total,
        "session_storage_persist_total": session_persist_total,
        "storage_restore_positive": storage_restore_positive,
        "storage_persist_positive": storage_persist_positive,
        "storage_any_restore_or_persist_positive": storage_any_positive,
        "storage_all_restore_and_persist_positive": storage_all_positive,
        "proxy_claim_lost_failures": to_int(event_summary.get("browser_proxy_claim_lost_failures")),
        "browser_proxy_not_found_failures": to_int(event_summary.get("browser_proxy_not_found_failures")),
        "source_concentration_top1_percent": {
            "latest": to_float(latest.get("source_concentration_top1_percent")),
            "median": to_float(concentration_summary.get("median")),
            "max": to_float(concentration_summary.get("max")),
        },
        "recent_hot_regions_union": recent_hot_regions_union,
        "unique_requested_regions": requested_regions,
        "observed_hot_regions": observed_hot_regions,
        "observed_recent_hot_regions": observed_recent_hot_regions,
        "site_host_count": to_int(site_host_evidence.get("site_host_count")),
        "stateful_site_host_count": to_int(
            site_host_evidence.get("stateful_site_host_count")
        ),
        "continuity_ready_site_host_count": to_int(
            site_host_evidence.get("continuity_ready_site_host_count")
        ),
        "continuity_ready_site_hosts": list(
            site_host_evidence.get("continuity_ready_site_hosts") or []
        ),
        "site_host_summaries": list(site_host_evidence.get("site_host_summaries") or []),
        "sample_sufficient": sample_sufficient,
        "evidence_ready": not evidence_reasons,
        "evidence_readiness_reasons": evidence_reasons,
    }


def format_counter(counter: dict[str, object]) -> str:
    items = [
        f"{key}={to_int(value)}"
        for key, value in sorted(counter.items(), key=lambda item: (-to_int(item[1]), item[0]))
    ]
    return ", ".join(items) if items else "none"


def format_float_counter(counter: dict[str, object]) -> str:
    items = [
        f"{key}={round(to_float(value), 2)}"
        for key, value in sorted(counter.items(), key=lambda item: (-to_float(item[1]), item[0]))
    ]
    return ", ".join(items) if items else "none"


def extract_event_host(event: dict[str, object]) -> str:
    for key in ("final_url", "url"):
        raw = str(event.get(key) or "").strip()
        if not raw:
            continue
        parsed = urllib.parse.urlparse(raw)
        host = (parsed.hostname or "").strip().lower()
        if host:
            return host
    return ""


def build_site_host_evidence(events: list[dict[str, object]]) -> dict[str, object]:
    host_rows: dict[str, dict[str, object]] = {}
    for event in events:
        if str(event.get("type") or "") != "browser":
            continue
        host = extract_event_host(event)
        if not host:
            continue
        row = host_rows.setdefault(
            host,
            {
                "host": host,
                "browser_total": 0,
                "browser_succeeded": 0,
                "external_total": 0,
                "external_succeeded": 0,
                "stateful_primary_total": 0,
                "stateful_primary_succeeded": 0,
                "stateful_followup_total": 0,
                "stateful_followup_succeeded": 0,
                "auto_created_total": 0,
                "auto_reused_total": 0,
                "storage_restore_observed": False,
                "storage_persist_observed": False,
                "requested_regions": set(),
                "observed_recent_hot_regions": set(),
                "proxy_ids": set(),
            },
        )
        workload = str(event.get("workload") or "external")
        status = str(event.get("status") or "")
        identity_status = str(event.get("identity_session_status") or "").strip()
        requested_region = str(event.get("requested_region") or "").strip()
        proxy_id = str(event.get("proxy_id") or "").strip()

        row["browser_total"] = to_int(row.get("browser_total")) + 1
        if status == "succeeded":
            row["browser_succeeded"] = to_int(row.get("browser_succeeded")) + 1
        if workload == "stateful":
            row["stateful_primary_total"] = to_int(row.get("stateful_primary_total")) + 1
            if status == "succeeded":
                row["stateful_primary_succeeded"] = to_int(
                    row.get("stateful_primary_succeeded")
                ) + 1
        elif workload == "stateful_followup":
            row["stateful_followup_total"] = to_int(row.get("stateful_followup_total")) + 1
            if status == "succeeded":
                row["stateful_followup_succeeded"] = to_int(
                    row.get("stateful_followup_succeeded")
                ) + 1
        else:
            row["external_total"] = to_int(row.get("external_total")) + 1
            if status == "succeeded":
                row["external_succeeded"] = to_int(row.get("external_succeeded")) + 1

        if identity_status == "auto_created":
            row["auto_created_total"] = to_int(row.get("auto_created_total")) + 1
        elif identity_status == "auto_reused":
            row["auto_reused_total"] = to_int(row.get("auto_reused_total")) + 1

        if (
            to_int(event.get("cookie_restore_count")) > 0
            or to_int(event.get("local_storage_restore_count")) > 0
            or to_int(event.get("session_storage_restore_count")) > 0
        ):
            row["storage_restore_observed"] = True
        if (
            to_int(event.get("cookie_persist_count")) > 0
            or to_int(event.get("local_storage_persist_count")) > 0
            or to_int(event.get("session_storage_persist_count")) > 0
        ):
            row["storage_persist_observed"] = True
        if requested_region:
            requested_regions = set(row.get("requested_regions") or set())
            requested_regions.add(requested_region)
            row["requested_regions"] = requested_regions
        if proxy_id:
            proxy_ids = set(row.get("proxy_ids") or set())
            proxy_ids.add(proxy_id)
            row["proxy_ids"] = proxy_ids
        observed_recent_hot_regions = set(row.get("observed_recent_hot_regions") or set())
        for region in list(event.get("recent_hot_regions_during_request") or []):
            region_text = str(region or "").strip()
            if region_text:
                observed_recent_hot_regions.add(region_text)
        row["observed_recent_hot_regions"] = observed_recent_hot_regions

    host_summaries: list[dict[str, object]] = []
    continuity_hosts: list[str] = []
    stateful_hosts: list[str] = []
    for host, row in host_rows.items():
        browser_total = to_int(row.get("browser_total"))
        success_rate_percent = round(
            (to_int(row.get("browser_succeeded")) / browser_total) * 100.0, 4
        ) if browser_total > 0 else 0.0
        continuity_chain_observed = (
            to_int(row.get("stateful_primary_total")) > 0
            and to_int(row.get("stateful_followup_total")) > 0
            and bool(row.get("storage_restore_observed"))
            and to_int(row.get("auto_reused_total")) > 0
        )
        if to_int(row.get("stateful_primary_total")) > 0 or to_int(
            row.get("stateful_followup_total")
        ) > 0:
            stateful_hosts.append(host)
        if continuity_chain_observed:
            continuity_hosts.append(host)
        host_summaries.append(
            {
                "host": host,
                "browser_total": browser_total,
                "browser_succeeded": to_int(row.get("browser_succeeded")),
                "browser_success_rate_percent": success_rate_percent,
                "external_total": to_int(row.get("external_total")),
                "external_succeeded": to_int(row.get("external_succeeded")),
                "stateful_primary_total": to_int(row.get("stateful_primary_total")),
                "stateful_primary_succeeded": to_int(
                    row.get("stateful_primary_succeeded")
                ),
                "stateful_followup_total": to_int(row.get("stateful_followup_total")),
                "stateful_followup_succeeded": to_int(
                    row.get("stateful_followup_succeeded")
                ),
                "auto_created_total": to_int(row.get("auto_created_total")),
                "auto_reused_total": to_int(row.get("auto_reused_total")),
                "storage_restore_observed": bool(row.get("storage_restore_observed")),
                "storage_persist_observed": bool(row.get("storage_persist_observed")),
                "continuity_chain_observed": continuity_chain_observed,
                "requested_regions": sorted(row.get("requested_regions") or []),
                "observed_recent_hot_regions": sorted(
                    row.get("observed_recent_hot_regions") or []
                ),
                "distinct_proxy_count": len(set(row.get("proxy_ids") or [])),
            }
        )
    host_summaries.sort(
        key=lambda item: (
            -(
                to_int(item.get("stateful_primary_total"))
                + to_int(item.get("stateful_followup_total"))
            ),
            -to_int(item.get("browser_total")),
            str(item.get("host") or ""),
        )
    )
    return {
        "site_host_count": len(host_summaries),
        "stateful_site_host_count": len(sorted(set(stateful_hosts))),
        "continuity_ready_site_host_count": len(sorted(set(continuity_hosts))),
        "continuity_ready_site_hosts": sorted(set(continuity_hosts)),
        "site_host_summaries": host_summaries[:5],
    }


def summarize(
    samples: list[dict[str, object]],
    errors: list[str],
    events: list[dict[str, object]],
    *,
    fallback_mode: str = "",
) -> dict[str, object]:
    modes = sorted({normalize_mode(sample.get("mode")) for sample in samples})
    latest = dict(samples[-1]) if samples else {}
    event_summary = summarize_events(events)
    event_recent_hot_regions = sorted(
        str(key).strip()
        for key in dict(event_summary.get("browser_recent_hot_regions_observed") or {}).keys()
        if str(key).strip()
    )
    event_requested_regions = sorted(
        str(key).strip()
        for key in dict(event_summary.get("browser_requested_regions") or {}).keys()
        if str(key).strip()
    )
    fallback_recent_hot_regions = event_recent_hot_regions or event_requested_regions
    if not list(latest.get("recent_hot_regions") or []) and fallback_recent_hot_regions:
        latest["recent_hot_regions"] = fallback_recent_hot_regions[:5]
    if to_int(latest.get("hot_region_window_seconds")) <= 0 and fallback_recent_hot_regions:
        latest["hot_region_window_seconds"] = 600
    primary_mode = str(
        latest.get("mode")
        or normalize_mode(fallback_mode, "")
        or (modes[0] if len(modes) == 1 else ("mixed" if len(modes) > 1 else ""))
        or "demo_public"
    )
    ratios = [float(sample["active_ratio_percent"]) for sample in samples]
    reported_ratios = [to_float(sample.get("reported_active_ratio_percent")) for sample in samples]
    derived_ratios = [to_float(sample.get("derived_active_ratio_percent")) for sample in samples]
    promotions = [float(sample["promotion_rate"]) for sample in samples]
    rejects = [float(sample["reject_rate"]) for sample in samples]
    fallbacks = [float(sample["fallback_rate"]) for sample in samples]
    source_top1_values = [to_float(sample.get("source_concentration_top1_percent")) for sample in samples]
    source_top3_values = [to_float(sample.get("source_concentration_top3_percent")) for sample in samples]
    recent_hot_regions_union_set = {
        str(region).strip()
        for sample in samples
        for region in list(sample.get("recent_hot_regions") or [])
        if str(region).strip()
    }
    recent_hot_regions_union_set.update(fallback_recent_hot_regions)
    recent_hot_regions_union = sorted(recent_hot_regions_union_set)
    recent_hot_region_lengths = [
        len(list(sample.get("recent_hot_regions") or []))
        for sample in samples
    ]
    if samples and fallback_recent_hot_regions:
        recent_hot_region_lengths[-1] = max(
            recent_hot_region_lengths[-1],
            len(fallback_recent_hot_regions[:5]),
        )
    recent_hot_region_count_max = max(recent_hot_region_lengths, default=0)
    starvation_events = sum(1 for sample in samples if int(sample["pool_active"]) == 0)
    shortage_events = sum(1 for sample in samples if sample["region_shortages"])
    browser_total = to_int(event_summary.get("browser_total"))
    browser_success_rate_percent = round(
        (to_int(event_summary.get("browser_succeeded")) / browser_total) * 100.0,
        4,
    ) if browser_total > 0 else 0.0
    return {
        "mode": primary_mode,
        "modes": modes,
        "sample_count": len(samples),
        "error_count": len(errors),
        "errors": errors,
        "active_ratio_percent": summarize_metric(ratios),
        "effective_active_ratio_percent": summarize_metric(ratios),
        "active_ratio_percent_reported": summarize_metric(reported_ratios),
        "reported_active_ratio_percent": summarize_metric(reported_ratios),
        "active_ratio_percent_derived": summarize_metric(derived_ratios),
        "derived_active_ratio_percent": summarize_metric(derived_ratios),
        "promotion_rate": summarize_metric(promotions),
        "reject_rate": summarize_metric(rejects),
        "fallback_rate": summarize_metric(fallbacks),
        "source_concentration_top1_percent": summarize_metric(source_top1_values),
        "source_concentration_top3_percent": summarize_metric(source_top3_values),
        "browser_success_rate_percent": browser_success_rate_percent,
        "recent_hot_regions_union": recent_hot_regions_union,
        "recent_hot_region_count_max": recent_hot_region_count_max,
        "starvation_events": starvation_events,
        "region_shortage_events": shortage_events,
        "session_deltas": {
            "reused_sessions": delta_or_zero(samples, "reused_sessions"),
            "created_sessions": delta_or_zero(samples, "created_sessions"),
            "cookie_restore_count": delta_or_zero(samples, "cookie_restore_count"),
            "cookie_persist_count": delta_or_zero(samples, "cookie_persist_count"),
            "local_storage_restore_count": delta_or_zero(samples, "local_storage_restore_count"),
            "local_storage_persist_count": delta_or_zero(samples, "local_storage_persist_count"),
            "session_storage_restore_count": delta_or_zero(samples, "session_storage_restore_count"),
            "session_storage_persist_count": delta_or_zero(samples, "session_storage_persist_count"),
        },
        "site_deltas": {
            "tracked_sites": delta_or_zero(samples, "tracked_sites"),
            "site_records": delta_or_zero(samples, "site_records"),
        },
        "trend_flags": {
            "active_ratio_ever_positive": any(value > 0 for value in ratios),
            "active_ratio_reported_ever_positive": any(value > 0 for value in reported_ratios),
            "active_pool_ever_positive": any(to_int(sample.get("pool_active")) > 0 for sample in samples),
            "promotion_ever_positive": any(value > 0 for value in promotions),
            "site_records_grew": delta_or_zero(samples, "site_records") > 0,
            "session_reuse_observed": delta_or_zero(samples, "reused_sessions") > 0 or to_int(latest.get("reused_sessions")) > 0,
            "stateful_continuity_observed": (
                to_int(event_summary.get("stateful_browser_succeeded")) > 0
                and (
                    to_int(event_summary.get("browser_cookie_restore_total")) > 0
                    or to_int(event_summary.get("browser_local_storage_restore_total")) > 0
                    or to_int(event_summary.get("browser_session_storage_restore_total")) > 0
                )
            ),
            "hot_regions_observed": bool(dict(event_summary.get("browser_hot_regions_observed") or {})),
            "recent_hot_regions_observed": bool(recent_hot_regions_union),
        },
        "event_summary": event_summary,
        "latest": latest,
    }


def render_text(
    base_url: str,
    summary: dict[str, object],
    samples: list[dict[str, object]],
    events: list[dict[str, object]],
) -> str:
    latest = dict(summary.get("latest") or {})
    session_deltas = dict(summary.get("session_deltas") or {})
    site_deltas = dict(summary.get("site_deltas") or {})
    trend_flags = dict(summary.get("trend_flags") or {})
    event_summary = dict(summary.get("event_summary") or {})
    lines = [
        "proxy longrun report",
        f"base_url: {base_url}",
        f"mode: {summary.get('mode', 'demo_public')}",
        f"preset: {summary.get('preset') or 'unknown'}",
        f"provider_supply_class: {summary.get('provider_supply_class') or 'lab_only'}",
        f"strict_verdict: {summary.get('strict_verdict') or 'unknown'}",
        f"operational_verdict: {summary.get('operational_verdict') or 'unknown'}",
        f"provider_cap_reason: {summary.get('provider_cap_reason') or 'none'}",
        f"modes: {', '.join(summary.get('modes', [])) or 'unknown'}",
        f"samples: {summary.get('sample_count', 0)}",
        f"errors: {summary.get('error_count', 0)}",
        "",
        "run context:",
        f"  stateful_followup_count: {summary.get('stateful_followup_count', 0)}",
        f"  sticky_stateful_region: {summary.get('sticky_stateful_region') or 'none'}",
        f"  pool_hygiene_extra_args: {' '.join(summary.get('pool_hygiene_extra_args', [])) or 'none'}",
        "",
        "aggregate:",
        f"  effective_active_ratio_percent median/min/max: {summary['effective_active_ratio_percent']['median']} / {summary['effective_active_ratio_percent']['min']} / {summary['effective_active_ratio_percent']['max']}",
        f"  reported_active_ratio_percent median/min/max: {summary['reported_active_ratio_percent']['median']} / {summary['reported_active_ratio_percent']['min']} / {summary['reported_active_ratio_percent']['max']}",
        f"  derived_active_ratio_percent median/min/max: {summary['derived_active_ratio_percent']['median']} / {summary['derived_active_ratio_percent']['min']} / {summary['derived_active_ratio_percent']['max']}",
        f"  promotion_rate median/min/max: {summary['promotion_rate']['median']} / {summary['promotion_rate']['min']} / {summary['promotion_rate']['max']}",
        f"  reject_rate median/min/max: {summary['reject_rate']['median']} / {summary['reject_rate']['min']} / {summary['reject_rate']['max']}",
        f"  fallback_rate median/min/max: {summary['fallback_rate']['median']} / {summary['fallback_rate']['min']} / {summary['fallback_rate']['max']}",
        f"  source_concentration_top1_percent median/min/max: {summary['source_concentration_top1_percent']['median']} / {summary['source_concentration_top1_percent']['min']} / {summary['source_concentration_top1_percent']['max']}",
        f"  source_concentration_top3_percent median/min/max: {summary['source_concentration_top3_percent']['median']} / {summary['source_concentration_top3_percent']['min']} / {summary['source_concentration_top3_percent']['max']}",
        f"  browser_success_rate_percent: {summary.get('browser_success_rate_percent', 0.0)}",
        f"  recent_hot_regions_union: {', '.join(summary.get('recent_hot_regions_union', [])) or 'none'}",
        f"  recent_hot_region_count_max: {summary.get('recent_hot_region_count_max', 0)}",
        f"  starvation_events: {summary.get('starvation_events', 0)}",
        f"  region_shortage_events: {summary.get('region_shortage_events', 0)}",
        "",
        "continuity deltas:",
        f"  reused_sessions delta: {session_deltas.get('reused_sessions', 0)}",
        f"  created_sessions delta: {session_deltas.get('created_sessions', 0)}",
        f"  cookie restore/persist delta: {session_deltas.get('cookie_restore_count', 0)} / {session_deltas.get('cookie_persist_count', 0)}",
        f"  local_storage restore/persist delta: {session_deltas.get('local_storage_restore_count', 0)} / {session_deltas.get('local_storage_persist_count', 0)}",
        f"  session_storage restore/persist delta: {session_deltas.get('session_storage_restore_count', 0)} / {session_deltas.get('session_storage_persist_count', 0)}",
        "",
        "site deltas:",
        f"  tracked_sites delta: {site_deltas.get('tracked_sites', 0)}",
        f"  site_records delta: {site_deltas.get('site_records', 0)}",
        "",
        "trend flags:",
        f"  active_ratio_ever_positive: {trend_flags.get('active_ratio_ever_positive', False)}",
        f"  active_ratio_reported_ever_positive: {trend_flags.get('active_ratio_reported_ever_positive', False)}",
        f"  active_pool_ever_positive: {trend_flags.get('active_pool_ever_positive', False)}",
        f"  promotion_ever_positive: {trend_flags.get('promotion_ever_positive', False)}",
        f"  site_records_grew: {trend_flags.get('site_records_grew', False)}",
        f"  session_reuse_observed: {trend_flags.get('session_reuse_observed', False)}",
        f"  stateful_continuity_observed: {trend_flags.get('stateful_continuity_observed', False)}",
        f"  recent_hot_regions_observed: {trend_flags.get('recent_hot_regions_observed', False)}",
        "",
        "driver events:",
        f"  harvest total/completed/partial/failed: {event_summary.get('harvest_total', 0)} / {event_summary.get('harvest_completed', 0)} / {event_summary.get('harvest_partial', 0)} / {event_summary.get('harvest_failed', 0)}",
        f"  hygiene total/succeeded/failed: {event_summary.get('hygiene_total', 0)} / {event_summary.get('hygiene_succeeded', 0)} / {event_summary.get('hygiene_failed', 0)}",
        f"  hygiene deleted rows/quarantined sources: {event_summary.get('hygiene_deleted_proxy_rows_total', 0)} / {event_summary.get('hygiene_quarantined_sources_total', 0)}",
        f"  hygiene last ratio before/after: {event_summary.get('hygiene_ratio_before_last', 0.0)} / {event_summary.get('hygiene_ratio_after_last', 0.0)}",
        f"  browser total/succeeded/failed/timed_out/cancelled: {event_summary.get('browser_total', 0)} / {event_summary.get('browser_succeeded', 0)} / {event_summary.get('browser_failed', 0)} / {event_summary.get('browser_timed_out', 0)} / {event_summary.get('browser_cancelled', 0)}",
        f"  browser proxy_not_found_failures/claim_lost_failures: {event_summary.get('browser_proxy_not_found_failures', 0)} / {event_summary.get('browser_proxy_claim_lost_failures', 0)}",
        f"  external browser total/succeeded: {event_summary.get('external_browser_total', 0)} / {event_summary.get('external_browser_succeeded', 0)}",
        f"  stateful browser total/succeeded: {event_summary.get('stateful_browser_total', 0)} / {event_summary.get('stateful_browser_succeeded', 0)}",
        f"  browser distinct urls/proxies: {event_summary.get('browser_distinct_url_count', 0)} / {event_summary.get('browser_distinct_proxy_count', 0)}",
        f"  browser requested_regions: {format_counter(dict(event_summary.get('browser_requested_regions') or {}))}",
        f"  browser hot_regions_observed: {format_counter(dict(event_summary.get('browser_hot_regions_observed') or {}))}",
        f"  browser recent_hot_regions_observed: {format_counter(dict(event_summary.get('browser_recent_hot_regions_observed') or {}))}",
        f"  browser region_shortages_observed: {format_counter(dict(event_summary.get('browser_region_shortages_observed') or {}))}",
        f"  browser identity_session_statuses: {format_counter(dict(event_summary.get('browser_identity_session_statuses') or {}))}",
        f"  browser cookie restore/persist totals: {event_summary.get('browser_cookie_restore_total', 0)} / {event_summary.get('browser_cookie_persist_total', 0)}",
        f"  browser local_storage restore/persist totals: {event_summary.get('browser_local_storage_restore_total', 0)} / {event_summary.get('browser_local_storage_persist_total', 0)}",
        f"  browser session_storage restore/persist totals: {event_summary.get('browser_session_storage_restore_total', 0)} / {event_summary.get('browser_session_storage_persist_total', 0)}",
        f"  geo_enrich total/succeeded/failed: {event_summary.get('geo_enrich_total', 0)} / {event_summary.get('geo_enrich_succeeded', 0)} / {event_summary.get('geo_enrich_failed', 0)}",
        f"  geo_enrich updated proxies/sources: {event_summary.get('geo_enrich_updated_proxy_rows_total', 0)} / {event_summary.get('geo_enrich_updated_source_rows_total', 0)}",
        f"  geo_enrich lookup succeeded/failed: {event_summary.get('geo_enrich_lookup_succeeded_total', 0)} / {event_summary.get('geo_enrich_lookup_failed_total', 0)}",
        f"  geo_enrich active regions before/after: {event_summary.get('geo_enrich_active_region_count_before_last', 0)} / {event_summary.get('geo_enrich_active_region_count_after_last', 0)}",
        f"  geo_enrich active_regions_after_last: {', '.join(event_summary.get('geo_enrich_active_regions_after_last', [])) or 'none'}",
        "",
        "latest snapshot:",
        f"  mode: {latest.get('mode', 'demo_public')}",
        f"  pool active/total: {latest.get('pool_active', 0)} / {latest.get('pool_total', 0)}",
        f"  active_ratio reported/effective: {latest.get('reported_active_ratio_percent', 0.0)} / {latest.get('active_ratio_percent', 0.0)}",
        f"  eligible_pool/fresh_candidate/recent_rejected: {latest.get('eligible_pool_total', 0)} / {latest.get('fresh_candidate_total', 0)} / {latest.get('recent_rejected_total', 0)}",
        f"  candidates/rejected: {latest.get('pool_candidate', 0)} / {latest.get('pool_candidate_rejected', 0)}",
        f"  region_shortages: {', '.join(latest.get('region_shortages', [])) or 'none'}",
        f"  hot_regions: {', '.join(latest.get('hot_regions', [])) or 'none'}",
        f"  recent_hot_regions(window={latest.get('hot_region_window_seconds', 0)}s): {', '.join(latest.get('recent_hot_regions', [])) or 'none'}",
        f"  source_concentration top1/top3: {latest.get('source_concentration_top1_percent', 0.0)} / {latest.get('source_concentration_top3_percent', 0.0)}",
        f"  active_sources_with_min_inventory / active_regions_with_min_inventory: {latest.get('active_sources_with_min_inventory', 0)} / {latest.get('active_regions_with_min_inventory', 0)}",
        f"  source_count healthy/due/failures: {latest.get('source_count', 0)} / {latest.get('healthy_source_count', 0)} / {latest.get('due_source_count', 0)} / {latest.get('source_failures', 0)}",
        f"  effective_geo_quality_summary: {json.dumps(latest.get('effective_geo_quality_summary', {}), ensure_ascii=False)}",
        f"  sessions active/reused/created: {latest.get('active_sessions', 0)} / {latest.get('reused_sessions', 0)} / {latest.get('created_sessions', 0)}",
        f"  cookies restore/persist: {latest.get('cookie_restore_count', 0)} / {latest.get('cookie_persist_count', 0)}",
        f"  local_storage restore/persist: {latest.get('local_storage_restore_count', 0)} / {latest.get('local_storage_persist_count', 0)}",
        f"  session_storage restore/persist: {latest.get('session_storage_restore_count', 0)} / {latest.get('session_storage_persist_count', 0)}",
        f"  tracked_sites/site_records: {latest.get('tracked_sites', 0)} / {latest.get('site_records', 0)}",
        f"  top_failing_sites: {', '.join(latest.get('top_failing_sites', [])) or 'none'}",
        "",
        "sample trace:",
    ]
    for sample in samples:
        lines.append(
            "  "
            + (
                "ts={captured_at} mode={mode} ratio={active_ratio_percent} reported_ratio={reported_active_ratio_percent} "
                "promotion={promotion_rate} reject={reject_rate} "
                "fallback={fallback_rate} active={pool_active}/{pool_total} reused={reused_sessions} "
                "sites={tracked_sites}/{site_records} shortages={shortages}"
            ).format(
                captured_at=sample["captured_at"],
                mode=sample.get("mode", "demo_public"),
                active_ratio_percent=sample["active_ratio_percent"],
                reported_active_ratio_percent=sample.get("reported_active_ratio_percent", 0.0),
                promotion_rate=sample["promotion_rate"],
                reject_rate=sample["reject_rate"],
                fallback_rate=sample["fallback_rate"],
                pool_active=sample["pool_active"],
                pool_total=sample["pool_total"],
                reused_sessions=sample["reused_sessions"],
                tracked_sites=sample["tracked_sites"],
                site_records=sample["site_records"],
                shortages=",".join(sample["region_shortages"]) or "none",
            )
        )
    if events:
        lines.extend(["", "recent driver events:"])
        for event in events[-10:]:
            event_type = str(event.get("type") or "event")
            status = str(event.get("status") or "unknown")
            timestamp = to_int(event.get("timestamp"))
            if event_type == "harvest":
                lines.append(
                    f"  ts={timestamp} type=harvest status={status} "
                    f"accepted={to_int(event.get('accepted_count'))} deduped={to_int(event.get('deduped_count'))} rejected={to_int(event.get('rejected_count'))}"
                )
            elif event_type == "hygiene":
                lines.append(
                    f"  ts={timestamp} type=hygiene status={status} "
                    f"deleted={to_int(event.get('deleted_proxy_rows'))} "
                    f"quarantined={to_int(event.get('quarantined_sources'))} "
                    f"ratio={to_float(event.get('effective_active_ratio_percent_before'))}"
                    f"->{to_float(event.get('effective_active_ratio_percent_after'))}"
                )
            elif event_type == "geo_enrich":
                lines.append(
                    f"  ts={timestamp} type=geo_enrich status={status} "
                    f"updated_proxies={to_int(event.get('updated_proxy_rows'))} "
                    f"updated_sources={to_int(event.get('updated_source_rows'))} "
                    f"lookup={to_int(event.get('lookup_succeeded'))}/{to_int(event.get('lookup_failed'))} "
                    f"regions={to_int(event.get('active_region_count_before'))}->{to_int(event.get('active_region_count_after'))}"
                )
            else:
                lines.append(
                    f"  ts={timestamp} type=browser workload={event.get('workload', 'external')} status={status} "
                    f"url={event.get('url', '')} proxy={event.get('proxy_id', '') or 'none'} "
                    f"region={event.get('requested_region', '') or 'none'} "
                    f"hot_regions={','.join(event.get('hot_regions_during_request', []) or []) or 'none'} "
                    f"recent_hot_regions={','.join(event.get('recent_hot_regions_during_request', []) or []) or 'none'} "
                    f"failure_scope={event.get('failure_scope', '') or 'none'} "
                    f"browser_failure_signal={event.get('browser_failure_signal', '') or 'none'} "
                    f"selection_reason={event.get('selection_reason_summary', '') or 'none'} "
                    f"error_message={event.get('error_message', '') or 'none'} "
                    f"identity={event.get('identity_session_status', '') or 'none'} "
                    f"cookies={to_int(event.get('cookie_restore_count'))}/{to_int(event.get('cookie_persist_count'))} "
                    f"local={to_int(event.get('local_storage_restore_count'))}/{to_int(event.get('local_storage_persist_count'))} "
                    f"session={to_int(event.get('session_storage_restore_count'))}/{to_int(event.get('session_storage_persist_count'))}"
                )
    if summary.get("errors"):
        lines.extend(["", "errors:"])
        for item in summary["errors"]:
            lines.append(f"  - {item}")
    return "\n".join(lines) + "\n"


def render_source_quality_text(source_summary: dict[str, object]) -> str:
    effective_geo_quality_summary = dict(source_summary.get("effective_geo_quality_summary") or {})
    lines = [
        "source quality summary",
        f"source_count: {to_int(source_summary.get('source_count'))}",
        f"healthy_source_count: {to_int(source_summary.get('healthy_source_count'))}",
        f"active_source_count: {to_int(source_summary.get('active_source_count'))}",
        f"prod_source_count: {to_int(source_summary.get('prod_source_count'))}",
        f"demo_source_count: {to_int(source_summary.get('demo_source_count'))}",
        f"controlled_source_count: {to_int(source_summary.get('controlled_source_count'))}",
        f"private_paid_source_count: {to_int(source_summary.get('private_paid_source_count'))}",
        f"provider_supply_class: {source_summary.get('provider_supply_class') or 'lab_only'}",
        f"quarantined_source_count: {to_int(source_summary.get('quarantined_source_count'))}",
        f"low_promotion_source_count: {to_int(source_summary.get('low_promotion_source_count'))}",
        f"geo_inferred_source_count: {to_int(source_summary.get('geo_inferred_source_count'))}",
        f"unknown_geo_source_count: {to_int(source_summary.get('unknown_geo_source_count'))}",
        f"declared_geo_quality_counts: {format_counter(dict(source_summary.get('declared_geo_quality_counts') or {}))}",
        f"effective_geo_quality_counts: {format_counter(dict(source_summary.get('effective_geo_quality_counts') or {}))}",
        f"effective_geo_quality active_share_percent: {format_float_counter(dict(effective_geo_quality_summary.get('active_share_percent_by_effective_geo_quality') or {}))}",
        f"avg/median/max_geo_coverage_percent: {effective_geo_quality_summary.get('avg_geo_coverage_percent', 0.0)} / {effective_geo_quality_summary.get('median_geo_coverage_percent', 0.0)} / {effective_geo_quality_summary.get('max_geo_coverage_percent', 0.0)}",
        "",
        "top_sources:",
    ]
    for item in source_summary.get("top_sources") or []:
        if not isinstance(item, dict):
            continue
        lines.append(
            "  "
            + (
                "source={source_label} tier={source_tier} prod={for_prod} demo={for_demo} "
                "cost_class={cost_class} "
                "declared_geo={declared_geo_quality} effective_geo={effective_geo_quality} "
                "geo_coverage={geo_coverage_percent} active_share={active_share_percent} "
                "health={health_score} promotion={promotion_rate} active={active_count} "
                "candidate={candidate_count} rejected={candidate_rejected_count} quarantine_until={quarantine_until}"
            ).format(
                source_label=item.get("source_label") or "unknown",
                source_tier=item.get("source_tier") or "none",
                for_prod=bool(item.get("for_prod")),
                for_demo=bool(item.get("for_demo")),
                cost_class=item.get("cost_class") or "none",
                declared_geo_quality=item.get("declared_geo_quality") or item.get("expected_geo_quality") or "unknown",
                effective_geo_quality=item.get("effective_geo_quality") or "unknown",
                geo_coverage_percent=item.get("geo_coverage_percent", 0.0),
                active_share_percent=item.get("active_share_percent", 0.0),
                health_score=item.get("health_score", 0.0),
                promotion_rate=item.get("promotion_rate", 0.0),
                active_count=to_int(item.get("active_count")),
                candidate_count=to_int(item.get("candidate_count")),
                candidate_rejected_count=to_int(item.get("candidate_rejected_count")),
                quarantine_until=item.get("quarantine_until") or "none",
            )
        )
    return "\n".join(lines) + "\n"


def render_session_continuity_text(session_summary: dict[str, object]) -> str:
    event_totals = dict(session_summary.get("event_totals") or {})
    session_deltas = dict(session_summary.get("session_deltas") or {})
    latest_counters = dict(session_summary.get("latest_counters") or {})
    lines = [
        "session continuity summary",
        f"mode: {session_summary.get('mode', 'demo_public')}",
        f"continuity_level: {session_summary.get('continuity_level', 'none')}",
        f"stateful_continuity_observed: {bool(session_summary.get('stateful_continuity_observed'))}",
        f"session_reuse_observed: {bool(session_summary.get('session_reuse_observed'))}",
        f"auto_created_observed: {bool(session_summary.get('auto_created_observed'))}",
        f"auto_reused_observed: {bool(session_summary.get('auto_reused_observed'))}",
        f"storage_restored_observed: {bool(session_summary.get('storage_restored_observed'))}",
        f"storage_persisted_observed: {bool(session_summary.get('storage_persisted_observed'))}",
        f"continuity_chain_observed: {bool(session_summary.get('continuity_chain_observed'))}",
        f"identity_session_statuses: {format_counter(dict(session_summary.get('identity_session_statuses') or {}))}",
        "",
        "event_totals:",
        f"  stateful_browser total/succeeded: {to_int(event_totals.get('stateful_browser_total'))} / {to_int(event_totals.get('stateful_browser_succeeded'))}",
        f"  cookie restore/persist totals: {to_int(event_totals.get('browser_cookie_restore_total'))} / {to_int(event_totals.get('browser_cookie_persist_total'))}",
        f"  local_storage restore/persist totals: {to_int(event_totals.get('browser_local_storage_restore_total'))} / {to_int(event_totals.get('browser_local_storage_persist_total'))}",
        f"  session_storage restore/persist totals: {to_int(event_totals.get('browser_session_storage_restore_total'))} / {to_int(event_totals.get('browser_session_storage_persist_total'))}",
        "",
        "session_deltas:",
        f"  reused/created: {to_int(session_deltas.get('reused_sessions'))} / {to_int(session_deltas.get('created_sessions'))}",
        f"  cookie restore/persist: {to_int(session_deltas.get('cookie_restore_count'))} / {to_int(session_deltas.get('cookie_persist_count'))}",
        f"  local_storage restore/persist: {to_int(session_deltas.get('local_storage_restore_count'))} / {to_int(session_deltas.get('local_storage_persist_count'))}",
        f"  session_storage restore/persist: {to_int(session_deltas.get('session_storage_restore_count'))} / {to_int(session_deltas.get('session_storage_persist_count'))}",
        "",
        "latest_counters:",
        f"  reused/created: {to_int(latest_counters.get('reused_sessions'))} / {to_int(latest_counters.get('created_sessions'))}",
        f"  cookie restore/persist: {to_int(latest_counters.get('cookie_restore_count'))} / {to_int(latest_counters.get('cookie_persist_count'))}",
        f"  local_storage restore/persist: {to_int(latest_counters.get('local_storage_restore_count'))} / {to_int(latest_counters.get('local_storage_persist_count'))}",
        f"  session_storage restore/persist: {to_int(latest_counters.get('session_storage_restore_count'))} / {to_int(latest_counters.get('session_storage_persist_count'))}",
    ]
    return "\n".join(lines) + "\n"


def render_real_live_evidence_text(evidence_summary: dict[str, object]) -> str:
    source_top1 = dict(evidence_summary.get("source_concentration_top1_percent") or {})
    lines = [
        "real live evidence summary",
        f"mode: {evidence_summary.get('mode', 'demo_public')}",
        f"sample_count: {to_int(evidence_summary.get('sample_count'))}",
        f"browser total/succeeded/success_rate_percent: {to_int(evidence_summary.get('browser_total'))} / {to_int(evidence_summary.get('browser_succeeded'))} / {to_float(evidence_summary.get('browser_success_rate_percent'))}",
        f"stateful_continuity_observed: {bool(evidence_summary.get('stateful_continuity_observed'))}",
        f"continuity_chain_observed: {bool(evidence_summary.get('continuity_chain_observed'))}",
        f"session_reuse_observed: {bool(evidence_summary.get('session_reuse_observed'))}",
        f"stateful primary total/succeeded: {to_int(evidence_summary.get('stateful_primary_total'))} / {to_int(evidence_summary.get('stateful_primary_succeeded'))}",
        f"stateful followup total/succeeded: {to_int(evidence_summary.get('stateful_followup_total'))} / {to_int(evidence_summary.get('stateful_followup_succeeded'))}",
        f"cookie restore/persist totals: {to_int(evidence_summary.get('cookie_restore_total'))} / {to_int(evidence_summary.get('cookie_persist_total'))}",
        f"local_storage restore/persist totals: {to_int(evidence_summary.get('local_storage_restore_total'))} / {to_int(evidence_summary.get('local_storage_persist_total'))}",
        f"session_storage restore/persist totals: {to_int(evidence_summary.get('session_storage_restore_total'))} / {to_int(evidence_summary.get('session_storage_persist_total'))}",
        f"storage_any_restore_or_persist_positive: {bool(evidence_summary.get('storage_any_restore_or_persist_positive'))}",
        f"storage_all_restore_and_persist_positive: {bool(evidence_summary.get('storage_all_restore_and_persist_positive'))}",
        f"proxy_claim_lost_failures: {to_int(evidence_summary.get('proxy_claim_lost_failures'))}",
        f"browser_proxy_not_found_failures: {to_int(evidence_summary.get('browser_proxy_not_found_failures'))}",
        f"source_concentration_top1_percent latest/median/max: {to_float(source_top1.get('latest'))} / {to_float(source_top1.get('median'))} / {to_float(source_top1.get('max'))}",
        f"recent_hot_regions_union: {', '.join(evidence_summary.get('recent_hot_regions_union', [])) or 'none'}",
        f"unique_requested_regions: {', '.join(evidence_summary.get('unique_requested_regions', [])) or 'none'}",
        f"observed_hot_regions: {', '.join(evidence_summary.get('observed_hot_regions', [])) or 'none'}",
        f"observed_recent_hot_regions: {', '.join(evidence_summary.get('observed_recent_hot_regions', [])) or 'none'}",
        f"site_host_count: {to_int(evidence_summary.get('site_host_count'))}",
        f"stateful_site_host_count: {to_int(evidence_summary.get('stateful_site_host_count'))}",
        f"continuity_ready_site_host_count: {to_int(evidence_summary.get('continuity_ready_site_host_count'))}",
        f"continuity_ready_site_hosts: {', '.join(evidence_summary.get('continuity_ready_site_hosts', [])) or 'none'}",
        f"sample_sufficient: {bool(evidence_summary.get('sample_sufficient'))}",
        f"evidence_ready: {bool(evidence_summary.get('evidence_ready'))}",
        f"evidence_readiness_reasons: {', '.join(evidence_summary.get('evidence_readiness_reasons', [])) or 'none'}",
    ]
    host_summaries = list(evidence_summary.get("site_host_summaries") or [])
    if host_summaries:
        lines.extend(["", "site_host_summaries:"])
        for item in host_summaries:
            if not isinstance(item, dict):
                continue
            lines.append(
                "  "
                + (
                    "host={host} browser={browser_total}/{browser_succeeded} success_rate={browser_success_rate_percent} "
                    "stateful_primary={stateful_primary_total}/{stateful_primary_succeeded} "
                    "followup={stateful_followup_total}/{stateful_followup_succeeded} "
                    "auto_created={auto_created_total} auto_reused={auto_reused_total} "
                    "storage_restore={storage_restore_observed} storage_persist={storage_persist_observed} "
                    "continuity_chain={continuity_chain_observed} "
                    "regions={requested_regions} recent_hot={observed_recent_hot_regions} proxies={distinct_proxy_count}"
                ).format(
                    host=item.get("host") or "unknown",
                    browser_total=to_int(item.get("browser_total")),
                    browser_succeeded=to_int(item.get("browser_succeeded")),
                    browser_success_rate_percent=to_float(item.get("browser_success_rate_percent")),
                    stateful_primary_total=to_int(item.get("stateful_primary_total")),
                    stateful_primary_succeeded=to_int(item.get("stateful_primary_succeeded")),
                    stateful_followup_total=to_int(item.get("stateful_followup_total")),
                    stateful_followup_succeeded=to_int(item.get("stateful_followup_succeeded")),
                    auto_created_total=to_int(item.get("auto_created_total")),
                    auto_reused_total=to_int(item.get("auto_reused_total")),
                    storage_restore_observed=bool(item.get("storage_restore_observed")),
                    storage_persist_observed=bool(item.get("storage_persist_observed")),
                    continuity_chain_observed=bool(item.get("continuity_chain_observed")),
                    requested_regions=",".join(item.get("requested_regions") or []) or "none",
                    observed_recent_hot_regions=",".join(item.get("observed_recent_hot_regions") or [])
                    or "none",
                    distinct_proxy_count=to_int(item.get("distinct_proxy_count")),
                )
            )
    return "\n".join(lines) + "\n"


def collect_live_samples(
    args: argparse.Namespace,
) -> tuple[
    str,
    list[dict[str, object]],
    list[str],
    list[dict[str, object]],
    list[dict[str, object]],
    dict[str, object],
]:
    samples: list[dict[str, object]] = []
    errors: list[str] = []
    status_snapshots: list[dict[str, object]] = []
    fallback_mode = str(os.environ.get("PERSONA_PILOT_PROXY_MODE") or "")
    total_samples = max(args.samples, 1)
    for index in range(total_samples):
        try:
            status = fetch_status(args.base_url, args.api_key)
            status_snapshots.append(
                {
                    "captured_at": int(time.time()),
                    "status": status,
                }
            )
            samples.append(build_sample(status, fallback_mode=fallback_mode))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            errors.append(f"sample {index + 1}: {exc}")
        if index + 1 < total_samples:
            time.sleep(max(args.interval_seconds, 1))
    return args.base_url, samples, errors, [], status_snapshots, {}


def main() -> int:
    args = parse_args()
    if args.input_json:
        base_url, samples, errors, events, status_snapshots, run_context = load_samples_from_input(args.input_json)
        if args.base_url and args.base_url != "http://127.0.0.1:3000":
            base_url = args.base_url
    else:
        base_url, samples, errors, events, status_snapshots, run_context = collect_live_samples(args)

    summary = summarize(
        samples,
        errors,
        events,
        fallback_mode=str(run_context.get("mode") or os.environ.get("PERSONA_PILOT_PROXY_MODE") or ""),
    )
    source_summary = build_source_quality_summary(status_snapshots)
    summary["preset"] = str(run_context.get("preset") or "unknown")
    summary["stateful_followup_count"] = to_int(run_context.get("stateful_followup_count"))
    summary["sticky_stateful_region"] = run_context.get("sticky_stateful_region")
    summary["pool_hygiene_extra_args"] = list(run_context.get("pool_hygiene_extra_args") or [])
    session_summary = build_session_continuity_summary(summary)
    real_live_evidence_summary = build_real_live_evidence_summary(
        summary,
        session_summary,
        events,
    )
    payload = {
        "base_url": base_url,
        "generated_at": int(time.time()),
        "mode": summary.get("mode"),
        "preset": summary.get("preset"),
        "summary": summary,
        "source_quality_summary": source_summary,
        "session_continuity_summary": session_summary,
        "real_live_evidence_summary": real_live_evidence_summary,
        "samples": samples,
        "events": events,
    }
    gate_result = evaluate_report_payload(payload, Thresholds())
    summary["provider_supply_class"] = gate_result.provider_supply_class
    summary["strict_verdict"] = gate_result.strict_verdict
    summary["operational_verdict"] = gate_result.operational_verdict
    summary["provider_cap_reason"] = gate_result.provider_cap_reason
    payload["provider_supply_class"] = gate_result.provider_supply_class
    payload["strict_verdict"] = gate_result.strict_verdict
    payload["operational_verdict"] = gate_result.operational_verdict
    payload["provider_cap_reason"] = gate_result.provider_cap_reason
    payload["reason_code"] = gate_result.reason_code
    payload["failure_scope"] = gate_result.failure_scope
    payload["detail"] = gate_result.detail

    txt_output = Path(args.txt_output)
    json_output = Path(args.json_output)
    source_summary_txt_output = txt_output.parent / "source_quality_summary_latest.txt"
    source_summary_json_output = json_output.parent / "source_quality_summary_latest.json"
    session_summary_txt_output = txt_output.parent / "session_continuity_summary_latest.txt"
    session_summary_json_output = json_output.parent / "session_continuity_summary_latest.json"
    real_live_evidence_txt_output = txt_output.parent / "real_live_evidence_summary_latest.txt"
    real_live_evidence_json_output = json_output.parent / "real_live_evidence_summary_latest.json"
    txt_output.parent.mkdir(parents=True, exist_ok=True)
    json_output.parent.mkdir(parents=True, exist_ok=True)
    txt_output.write_text(render_text(base_url, summary, samples, events), encoding="utf-8")
    json_output.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    source_summary_txt_output.write_text(render_source_quality_text(source_summary), encoding="utf-8")
    source_summary_json_output.write_text(
        json.dumps(source_summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    session_summary_txt_output.write_text(render_session_continuity_text(session_summary), encoding="utf-8")
    session_summary_json_output.write_text(
        json.dumps(session_summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    real_live_evidence_txt_output.write_text(
        render_real_live_evidence_text(real_live_evidence_summary),
        encoding="utf-8",
    )
    real_live_evidence_json_output.write_text(
        json.dumps(real_live_evidence_summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(txt_output.read_text(encoding="utf-8"), end="")
    return 0 if samples else 1


if __name__ == "__main__":
    sys.exit(main())
